; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/atomic-rmw-cap-ptr-arg.ll
; Check that we can generate sensible code for atomic operations using capability pointers on capabilities
; See https://github.com/CTSRD-CHERI/llvm-project/issues/470
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -mattr=+a < %s | FileCheck %s --check-prefixes=PURECAP,PURECAP-ATOMICS --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -mattr=-a < %s | FileCheck %s --check-prefixes=PURECAP,PURECAP-LIBCALLS --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -mattr=+a < %s | FileCheck %s --check-prefixes=HYBRID,HYBRID-ATOMICS --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -mattr=-a < %s | FileCheck %s --check-prefixes=HYBRID,HYBRID-LIBCALLS --allow-unused-prefixes

define i32 addrspace(200)* @atomic_cap_ptr_xchg_sc(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg_sc:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.c.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg_sc:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg_sc:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_exchange_cap_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_xchg_relaxed(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg_relaxed:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.c a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg_relaxed:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg_relaxed:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 0
; HYBRID-NEXT:    call __atomic_exchange_cap_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val monotonic
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_xchg_acquire(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg_acquire:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.c.aq a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg_acquire:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg_acquire:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 2
; HYBRID-NEXT:    call __atomic_exchange_cap_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val acquire
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_xchg_rel(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg_rel:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.c.rl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg_rel:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 3
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg_rel:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 3
; HYBRID-NEXT:    call __atomic_exchange_cap_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val release
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_xchg_acq_rel(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg_acq_rel:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.c.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg_acq_rel:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 4
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg_acq_rel:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 4
; HYBRID-NEXT:    call __atomic_exchange_cap_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val acq_rel
  ret i32 addrspace(200)* %tmp
}

; Also check non-i8* xchg:
define i32 addrspace(200)* @atomic_cap_ptr_xchg_i32ptr(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg_i32ptr:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.c.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg_i32ptr:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 4
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg_i32ptr:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 4
; HYBRID-NEXT:    call __atomic_exchange_cap_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val acq_rel
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_add(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_add:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB6_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    cincoffset a3, a2, a1
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB6_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_add:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:  .LBB6_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    add a0, a1, s0
; PURECAP-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB6_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_add:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:  .LBB6_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    add a0, a3, a0
; HYBRID-ATOMICS-NEXT:    csetaddr a2, a3, a0
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB6_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_add:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:  .LBB6_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    add a0, a1, a0
; HYBRID-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB6_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw add i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_sub(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_sub:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB7_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    sub a3, a2, a1
; PURECAP-ATOMICS-NEXT:    csetaddr a3, a2, a3
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB7_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_sub:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:  .LBB7_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    sub a0, a1, s0
; PURECAP-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB7_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_sub:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:  .LBB7_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    sub a0, a3, a0
; HYBRID-ATOMICS-NEXT:    csetaddr a2, a3, a0
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB7_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_sub:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:  .LBB7_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    sub a0, a1, a0
; HYBRID-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB7_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw sub i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_and(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_and:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB8_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    and a3, a2, a1
; PURECAP-ATOMICS-NEXT:    csetaddr a3, a2, a3
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB8_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_and:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:  .LBB8_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    and a0, a1, s0
; PURECAP-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB8_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_and:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:  .LBB8_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    and a0, a3, a0
; HYBRID-ATOMICS-NEXT:    csetaddr a2, a3, a0
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB8_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_and:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:  .LBB8_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    and a0, a1, a0
; HYBRID-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB8_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw and i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_nand(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_nand:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB9_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    and a3, a2, a1
; PURECAP-ATOMICS-NEXT:    not a3, a3
; PURECAP-ATOMICS-NEXT:    csetaddr a3, a2, a3
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB9_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_nand:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:  .LBB9_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    and a0, a1, s0
; PURECAP-LIBCALLS-NEXT:    not a0, a0
; PURECAP-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB9_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_nand:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:  .LBB9_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    and a0, a3, a0
; HYBRID-ATOMICS-NEXT:    not a0, a0
; HYBRID-ATOMICS-NEXT:    csetaddr a2, a3, a0
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB9_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_nand:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:  .LBB9_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    and a0, a1, a0
; HYBRID-LIBCALLS-NEXT:    not a0, a0
; HYBRID-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB9_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw nand i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_or(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_or:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB10_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    or a3, a2, a1
; PURECAP-ATOMICS-NEXT:    csetaddr a3, a2, a3
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB10_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_or:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:  .LBB10_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    or a0, a1, s0
; PURECAP-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB10_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_or:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:  .LBB10_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    or a0, a3, a0
; HYBRID-ATOMICS-NEXT:    csetaddr a2, a3, a0
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB10_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_or:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:  .LBB10_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    or a0, a1, a0
; HYBRID-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB10_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw or i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_xor(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xor:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB11_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    xor a3, a2, a1
; PURECAP-ATOMICS-NEXT:    csetaddr a3, a2, a3
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB11_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xor:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:  .LBB11_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    xor a0, a1, s0
; PURECAP-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB11_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_xor:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:  .LBB11_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    xor a0, a3, a0
; HYBRID-ATOMICS-NEXT:    csetaddr a2, a3, a0
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB11_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_xor:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:  .LBB11_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    xor a0, a1, a0
; HYBRID-LIBCALLS-NEXT:    csetaddr a2, a1, a0
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB11_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw xor i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_max(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_max:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB12_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:    bge a3, a1, .LBB12_3
; PURECAP-ATOMICS-NEXT:  # %bb.2: # in Loop: Header=BB12_1 Depth=1
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:  .LBB12_3: # in Loop: Header=BB12_1 Depth=1
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB12_1
; PURECAP-ATOMICS-NEXT:  # %bb.4:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_max:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:    j .LBB12_2
; PURECAP-LIBCALLS-NEXT:  .LBB12_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB12_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB12_4
; PURECAP-LIBCALLS-NEXT:  .LBB12_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, a1
; PURECAP-LIBCALLS-NEXT:    blt s0, a1, .LBB12_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB12_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB12_1
; PURECAP-LIBCALLS-NEXT:  .LBB12_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_max:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    j .LBB12_2
; HYBRID-ATOMICS-NEXT:  .LBB12_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB12_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB12_4
; HYBRID-ATOMICS-NEXT:  .LBB12_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    cmove a2, a3
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    blt a0, a3, .LBB12_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB12_2 Depth=1
; HYBRID-ATOMICS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    j .LBB12_1
; HYBRID-ATOMICS-NEXT:  .LBB12_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_max:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB12_2
; HYBRID-LIBCALLS-NEXT:  .LBB12_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB12_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB12_4
; HYBRID-LIBCALLS-NEXT:  .LBB12_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    cmove a2, a1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    blt a0, a1, .LBB12_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB12_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    j .LBB12_1
; HYBRID-LIBCALLS-NEXT:  .LBB12_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw max i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_min(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_min:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB13_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:    bge a1, a3, .LBB13_3
; PURECAP-ATOMICS-NEXT:  # %bb.2: # in Loop: Header=BB13_1 Depth=1
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:  .LBB13_3: # in Loop: Header=BB13_1 Depth=1
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB13_1
; PURECAP-ATOMICS-NEXT:  # %bb.4:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_min:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:    j .LBB13_2
; PURECAP-LIBCALLS-NEXT:  .LBB13_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB13_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB13_4
; PURECAP-LIBCALLS-NEXT:  .LBB13_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, a1
; PURECAP-LIBCALLS-NEXT:    bge s0, a1, .LBB13_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB13_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB13_1
; PURECAP-LIBCALLS-NEXT:  .LBB13_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_min:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    j .LBB13_2
; HYBRID-ATOMICS-NEXT:  .LBB13_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB13_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB13_4
; HYBRID-ATOMICS-NEXT:  .LBB13_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    cmove a2, a3
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    bge a0, a3, .LBB13_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB13_2 Depth=1
; HYBRID-ATOMICS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    j .LBB13_1
; HYBRID-ATOMICS-NEXT:  .LBB13_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_min:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB13_2
; HYBRID-LIBCALLS-NEXT:  .LBB13_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB13_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB13_4
; HYBRID-LIBCALLS-NEXT:  .LBB13_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    cmove a2, a1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    bge a0, a1, .LBB13_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB13_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    j .LBB13_1
; HYBRID-LIBCALLS-NEXT:  .LBB13_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw min i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_umax(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_umax:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB14_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:    bgeu a3, a1, .LBB14_3
; PURECAP-ATOMICS-NEXT:  # %bb.2: # in Loop: Header=BB14_1 Depth=1
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:  .LBB14_3: # in Loop: Header=BB14_1 Depth=1
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB14_1
; PURECAP-ATOMICS-NEXT:  # %bb.4:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_umax:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:    j .LBB14_2
; PURECAP-LIBCALLS-NEXT:  .LBB14_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB14_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB14_4
; PURECAP-LIBCALLS-NEXT:  .LBB14_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, a1
; PURECAP-LIBCALLS-NEXT:    bltu s0, a1, .LBB14_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB14_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB14_1
; PURECAP-LIBCALLS-NEXT:  .LBB14_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_umax:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    j .LBB14_2
; HYBRID-ATOMICS-NEXT:  .LBB14_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB14_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB14_4
; HYBRID-ATOMICS-NEXT:  .LBB14_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    cmove a2, a3
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    bltu a0, a3, .LBB14_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB14_2 Depth=1
; HYBRID-ATOMICS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    j .LBB14_1
; HYBRID-ATOMICS-NEXT:  .LBB14_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_umax:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB14_2
; HYBRID-LIBCALLS-NEXT:  .LBB14_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB14_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB14_4
; HYBRID-LIBCALLS-NEXT:  .LBB14_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    cmove a2, a1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    bltu a0, a1, .LBB14_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB14_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    j .LBB14_1
; HYBRID-LIBCALLS-NEXT:  .LBB14_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw umax i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}

define i32 addrspace(200)* @atomic_cap_ptr_umin(i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_umin:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB15_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.c.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:    bgeu a1, a3, .LBB15_3
; PURECAP-ATOMICS-NEXT:  # %bb.2: # in Loop: Header=BB15_1 Depth=1
; PURECAP-ATOMICS-NEXT:    cmove a3, a2
; PURECAP-ATOMICS-NEXT:  .LBB15_3: # in Loop: Header=BB15_1 Depth=1
; PURECAP-ATOMICS-NEXT:    csc.c.aqrl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB15_1
; PURECAP-ATOMICS-NEXT:  # %bb.4:
; PURECAP-ATOMICS-NEXT:    cmove a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_umin:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cmove s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_cap
; PURECAP-LIBCALLS-NEXT:    cmove a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 0
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 16
; PURECAP-LIBCALLS-NEXT:    j .LBB15_2
; PURECAP-LIBCALLS-NEXT:  .LBB15_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB15_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_cap
; PURECAP-LIBCALLS-NEXT:    clc a1, 0(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB15_4
; PURECAP-LIBCALLS-NEXT:  .LBB15_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, a1
; PURECAP-LIBCALLS-NEXT:    bgeu s0, a1, .LBB15_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB15_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    cmove a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB15_1
; PURECAP-LIBCALLS-NEXT:  .LBB15_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    cmove a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_umin:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -64
; HYBRID-ATOMICS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lc.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    j .LBB15_2
; HYBRID-ATOMICS-NEXT:  .LBB15_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB15_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 32
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-ATOMICS-NEXT:    lc a3, 32(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB15_4
; HYBRID-ATOMICS-NEXT:  .LBB15_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    cmove a2, a3
; HYBRID-ATOMICS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    bgeu a0, a3, .LBB15_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB15_2 Depth=1
; HYBRID-ATOMICS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    j .LBB15_1
; HYBRID-ATOMICS-NEXT:  .LBB15_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    cmove a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 64
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_umin:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -64
; HYBRID-LIBCALLS-NEXT:    sd ra, 56(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a1, 16(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_cap_c
; HYBRID-LIBCALLS-NEXT:    cmove a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB15_2
; HYBRID-LIBCALLS-NEXT:  .LBB15_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB15_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 32
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_cap_c
; HYBRID-LIBCALLS-NEXT:    lc a1, 32(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB15_4
; HYBRID-LIBCALLS-NEXT:  .LBB15_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    cmove a2, a1
; HYBRID-LIBCALLS-NEXT:    lc a0, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    bgeu a0, a1, .LBB15_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB15_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    lc a2, 16(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    j .LBB15_1
; HYBRID-LIBCALLS-NEXT:  .LBB15_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    cmove a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 56(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 64
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw umin i32 addrspace(200)* addrspace(200)* %ptr, i32 addrspace(200)* %val seq_cst
  ret i32 addrspace(200)* %tmp
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; PURECAP: {{.*}}
