; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/atomic-rmw-cap-ptr.ll
; Check that we can generate sensible code for atomic operations using capability pointers
; https://github.com/CTSRD-CHERI/llvm-project/issues/470
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -mattr=+a < %s | FileCheck %s --check-prefixes=PURECAP,PURECAP-ATOMICS --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi l64pc128d -mattr=+xcheri,+xcheripurecap,+f,+d -mattr=-a < %s | FileCheck %s --check-prefixes=PURECAP,PURECAP-LIBCALLS --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -mattr=+a < %s | FileCheck %s --check-prefixes=HYBRID,HYBRID-ATOMICS --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 --relocation-model=pic -target-abi lp64d -mattr=+xcheri,+f,+d -mattr=-a < %s | FileCheck %s --check-prefixes=HYBRID,HYBRID-LIBCALLS --allow-unused-prefixes

define i64 @atomic_cap_ptr_xchg(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xchg:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoswap.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xchg:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_exchange_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xchg:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_exchange_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xchg i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_add(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_add:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoadd.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_add:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_fetch_add_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_add:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_fetch_add_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw add i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_sub(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_sub:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    neg a1, a1
; PURECAP-ATOMICS-NEXT:    camoadd.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_sub:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_fetch_sub_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_sub:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_fetch_sub_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw sub i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_and(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_and:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoand.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_and:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_fetch_and_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_and:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_fetch_and_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw and i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_nand(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_nand:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:  .LBB4_1: # =>This Inner Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    clr.d.aqrl a2, (a0)
; PURECAP-ATOMICS-NEXT:    and a3, a2, a1
; PURECAP-ATOMICS-NEXT:    not a3, a3
; PURECAP-ATOMICS-NEXT:    csc.d.rl a3, a3, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a3, .LBB4_1
; PURECAP-ATOMICS-NEXT:  # %bb.2:
; PURECAP-ATOMICS-NEXT:    mv a0, a2
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_nand:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_fetch_nand_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_nand:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_fetch_nand_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw nand i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_or(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_or:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoor.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_or:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_fetch_or_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_or:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_fetch_or_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw or i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_xor(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_xor:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camoxor.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_xor:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -16
; PURECAP-LIBCALLS-NEXT:    csc ra, 0(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    li a2, 5
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_fetch_xor_8
; PURECAP-LIBCALLS-NEXT:    clc ra, 0(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 16
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-LABEL: atomic_cap_ptr_xor:
; HYBRID:       # %bb.0:
; HYBRID-NEXT:    addi sp, sp, -16
; HYBRID-NEXT:    sd ra, 8(sp) # 8-byte Folded Spill
; HYBRID-NEXT:    li a2, 5
; HYBRID-NEXT:    call __atomic_fetch_xor_8_c
; HYBRID-NEXT:    ld ra, 8(sp) # 8-byte Folded Reload
; HYBRID-NEXT:    addi sp, sp, 16
; HYBRID-NEXT:    ret
  %tmp = atomicrmw xor i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_max(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_max:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camomax.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_max:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    mv s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_8
; PURECAP-LIBCALLS-NEXT:    mv a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 8
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 8
; PURECAP-LIBCALLS-NEXT:    j .LBB7_2
; PURECAP-LIBCALLS-NEXT:  .LBB7_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB7_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csd a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_8
; PURECAP-LIBCALLS-NEXT:    cld a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB7_4
; PURECAP-LIBCALLS-NEXT:  .LBB7_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, a1
; PURECAP-LIBCALLS-NEXT:    blt s0, a1, .LBB7_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB7_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB7_1
; PURECAP-LIBCALLS-NEXT:  .LBB7_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    mv a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_max:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -48
; HYBRID-ATOMICS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    ld.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    mv s0, a1
; HYBRID-ATOMICS-NEXT:    j .LBB7_2
; HYBRID-ATOMICS-NEXT:  .LBB7_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB7_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sd a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 24
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-ATOMICS-NEXT:    ld a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB7_4
; HYBRID-ATOMICS-NEXT:  .LBB7_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, a3
; HYBRID-ATOMICS-NEXT:    blt s0, a3, .LBB7_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB7_2 Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, s0
; HYBRID-ATOMICS-NEXT:    j .LBB7_1
; HYBRID-ATOMICS-NEXT:  .LBB7_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    mv a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 48
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_max:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -48
; HYBRID-LIBCALLS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    mv s0, a1
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_8_c
; HYBRID-LIBCALLS-NEXT:    mv a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB7_2
; HYBRID-LIBCALLS-NEXT:  .LBB7_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB7_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sd a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 24
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-LIBCALLS-NEXT:    ld a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB7_4
; HYBRID-LIBCALLS-NEXT:  .LBB7_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, a1
; HYBRID-LIBCALLS-NEXT:    blt s0, a1, .LBB7_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB7_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, s0
; HYBRID-LIBCALLS-NEXT:    j .LBB7_1
; HYBRID-LIBCALLS-NEXT:  .LBB7_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    mv a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 48
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw max i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_min(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_min:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camomin.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_min:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    mv s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_8
; PURECAP-LIBCALLS-NEXT:    mv a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 8
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 8
; PURECAP-LIBCALLS-NEXT:    j .LBB8_2
; PURECAP-LIBCALLS-NEXT:  .LBB8_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB8_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csd a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_8
; PURECAP-LIBCALLS-NEXT:    cld a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB8_4
; PURECAP-LIBCALLS-NEXT:  .LBB8_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, a1
; PURECAP-LIBCALLS-NEXT:    bge s0, a1, .LBB8_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB8_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB8_1
; PURECAP-LIBCALLS-NEXT:  .LBB8_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    mv a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_min:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -48
; HYBRID-ATOMICS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    ld.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    mv s0, a1
; HYBRID-ATOMICS-NEXT:    j .LBB8_2
; HYBRID-ATOMICS-NEXT:  .LBB8_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB8_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sd a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 24
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-ATOMICS-NEXT:    ld a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB8_4
; HYBRID-ATOMICS-NEXT:  .LBB8_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, a3
; HYBRID-ATOMICS-NEXT:    bge s0, a3, .LBB8_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB8_2 Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, s0
; HYBRID-ATOMICS-NEXT:    j .LBB8_1
; HYBRID-ATOMICS-NEXT:  .LBB8_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    mv a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 48
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_min:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -48
; HYBRID-LIBCALLS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    mv s0, a1
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_8_c
; HYBRID-LIBCALLS-NEXT:    mv a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB8_2
; HYBRID-LIBCALLS-NEXT:  .LBB8_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB8_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sd a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 24
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-LIBCALLS-NEXT:    ld a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB8_4
; HYBRID-LIBCALLS-NEXT:  .LBB8_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, a1
; HYBRID-LIBCALLS-NEXT:    bge s0, a1, .LBB8_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB8_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, s0
; HYBRID-LIBCALLS-NEXT:    j .LBB8_1
; HYBRID-LIBCALLS-NEXT:  .LBB8_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    mv a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 48
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw min i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_umax(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_umax:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camomaxu.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_umax:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    mv s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_8
; PURECAP-LIBCALLS-NEXT:    mv a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 8
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 8
; PURECAP-LIBCALLS-NEXT:    j .LBB9_2
; PURECAP-LIBCALLS-NEXT:  .LBB9_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB9_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csd a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_8
; PURECAP-LIBCALLS-NEXT:    cld a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB9_4
; PURECAP-LIBCALLS-NEXT:  .LBB9_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, a1
; PURECAP-LIBCALLS-NEXT:    bltu s0, a1, .LBB9_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB9_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB9_1
; PURECAP-LIBCALLS-NEXT:  .LBB9_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    mv a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_umax:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -48
; HYBRID-ATOMICS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    ld.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    mv s0, a1
; HYBRID-ATOMICS-NEXT:    j .LBB9_2
; HYBRID-ATOMICS-NEXT:  .LBB9_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB9_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sd a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 24
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-ATOMICS-NEXT:    ld a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB9_4
; HYBRID-ATOMICS-NEXT:  .LBB9_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, a3
; HYBRID-ATOMICS-NEXT:    bltu s0, a3, .LBB9_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB9_2 Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, s0
; HYBRID-ATOMICS-NEXT:    j .LBB9_1
; HYBRID-ATOMICS-NEXT:  .LBB9_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    mv a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 48
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_umax:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -48
; HYBRID-LIBCALLS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    mv s0, a1
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_8_c
; HYBRID-LIBCALLS-NEXT:    mv a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB9_2
; HYBRID-LIBCALLS-NEXT:  .LBB9_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB9_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sd a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 24
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-LIBCALLS-NEXT:    ld a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB9_4
; HYBRID-LIBCALLS-NEXT:  .LBB9_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, a1
; HYBRID-LIBCALLS-NEXT:    bltu s0, a1, .LBB9_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB9_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, s0
; HYBRID-LIBCALLS-NEXT:    j .LBB9_1
; HYBRID-LIBCALLS-NEXT:  .LBB9_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    mv a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 48
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw umax i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define i64 @atomic_cap_ptr_umin(i64 addrspace(200)* %ptr, i64 %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_umin:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    camominu.d.aqrl a0, a1, (a0)
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_umin:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -80
; PURECAP-LIBCALLS-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    mv s0, a1
; PURECAP-LIBCALLS-NEXT:    cmove s1, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_8
; PURECAP-LIBCALLS-NEXT:    mv a1, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 8
; PURECAP-LIBCALLS-NEXT:    csetbounds s2, a0, 8
; PURECAP-LIBCALLS-NEXT:    j .LBB10_2
; PURECAP-LIBCALLS-NEXT:  .LBB10_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB10_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    csd a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s1
; PURECAP-LIBCALLS-NEXT:    cmove a1, s2
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_8
; PURECAP-LIBCALLS-NEXT:    cld a1, 8(sp)
; PURECAP-LIBCALLS-NEXT:    bnez a0, .LBB10_4
; PURECAP-LIBCALLS-NEXT:  .LBB10_2: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, a1
; PURECAP-LIBCALLS-NEXT:    bgeu s0, a1, .LBB10_1
; PURECAP-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # in Loop: Header=BB10_2 Depth=1
; PURECAP-LIBCALLS-NEXT:    mv a2, s0
; PURECAP-LIBCALLS-NEXT:    j .LBB10_1
; PURECAP-LIBCALLS-NEXT:  .LBB10_4: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    mv a0, a1
; PURECAP-LIBCALLS-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 80
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_umin:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -48
; HYBRID-ATOMICS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    ld.cap a3, (a0)
; HYBRID-ATOMICS-NEXT:    mv s0, a1
; HYBRID-ATOMICS-NEXT:    j .LBB10_2
; HYBRID-ATOMICS-NEXT:  .LBB10_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB10_2 Depth=1
; HYBRID-ATOMICS-NEXT:    sd a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 24
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-ATOMICS-NEXT:    ld a3, 24(sp)
; HYBRID-ATOMICS-NEXT:    bnez a0, .LBB10_4
; HYBRID-ATOMICS-NEXT:  .LBB10_2: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, a3
; HYBRID-ATOMICS-NEXT:    bgeu s0, a3, .LBB10_1
; HYBRID-ATOMICS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # in Loop: Header=BB10_2 Depth=1
; HYBRID-ATOMICS-NEXT:    mv a2, s0
; HYBRID-ATOMICS-NEXT:    j .LBB10_1
; HYBRID-ATOMICS-NEXT:  .LBB10_4: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    mv a0, a3
; HYBRID-ATOMICS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 48
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_umin:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -48
; HYBRID-LIBCALLS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    sd s0, 32(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    mv s0, a1
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_8_c
; HYBRID-LIBCALLS-NEXT:    mv a1, a0
; HYBRID-LIBCALLS-NEXT:    j .LBB10_2
; HYBRID-LIBCALLS-NEXT:  .LBB10_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB10_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    sd a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 24
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_8_c
; HYBRID-LIBCALLS-NEXT:    ld a1, 24(sp)
; HYBRID-LIBCALLS-NEXT:    bnez a0, .LBB10_4
; HYBRID-LIBCALLS-NEXT:  .LBB10_2: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, a1
; HYBRID-LIBCALLS-NEXT:    bgeu s0, a1, .LBB10_1
; HYBRID-LIBCALLS-NEXT:  # %bb.3: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # in Loop: Header=BB10_2 Depth=1
; HYBRID-LIBCALLS-NEXT:    mv a2, s0
; HYBRID-LIBCALLS-NEXT:    j .LBB10_1
; HYBRID-LIBCALLS-NEXT:  .LBB10_4: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    mv a0, a1
; HYBRID-LIBCALLS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    ld s0, 32(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 48
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw umin i64 addrspace(200)* %ptr, i64 %val seq_cst
  ret i64 %tmp
}

define float @atomic_cap_ptr_fadd(float addrspace(200)* %ptr, float %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_fadd:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    clw a1, 0(a0)
; PURECAP-ATOMICS-NEXT:    fmv.w.x fa5, a1
; PURECAP-ATOMICS-NEXT:  .LBB11_1: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # =>This Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    # Child Loop BB11_3 Depth 2
; PURECAP-ATOMICS-NEXT:    fadd.s fa4, fa5, fa0
; PURECAP-ATOMICS-NEXT:    fmv.x.w a1, fa4
; PURECAP-ATOMICS-NEXT:    fmv.x.w a2, fa5
; PURECAP-ATOMICS-NEXT:  .LBB11_3: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # Parent Loop BB11_1 Depth=1
; PURECAP-ATOMICS-NEXT:    # => This Inner Loop Header: Depth=2
; PURECAP-ATOMICS-NEXT:    clr.w.aqrl a3, (a0)
; PURECAP-ATOMICS-NEXT:    bne a3, a2, .LBB11_5
; PURECAP-ATOMICS-NEXT:  # %bb.4: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # in Loop: Header=BB11_3 Depth=2
; PURECAP-ATOMICS-NEXT:    csc.w.rl a4, a1, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a4, .LBB11_3
; PURECAP-ATOMICS-NEXT:  .LBB11_5: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # in Loop: Header=BB11_1 Depth=1
; PURECAP-ATOMICS-NEXT:    fmv.w.x fa5, a3
; PURECAP-ATOMICS-NEXT:    bne a3, a2, .LBB11_1
; PURECAP-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-ATOMICS-NEXT:    fmv.s fa0, fa5
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_fadd:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -64
; PURECAP-LIBCALLS-NEXT:    csc ra, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cfsd fs0, 8(sp) # 8-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    fmv.s fs0, fa0
; PURECAP-LIBCALLS-NEXT:    cmove s0, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_4
; PURECAP-LIBCALLS-NEXT:    fmv.w.x fa0, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 4
; PURECAP-LIBCALLS-NEXT:    csetbounds s1, a0, 4
; PURECAP-LIBCALLS-NEXT:  .LBB11_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    fadd.s fa5, fa0, fs0
; PURECAP-LIBCALLS-NEXT:    fmv.x.w a2, fa5
; PURECAP-LIBCALLS-NEXT:    cfsw fa0, 4(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s0
; PURECAP-LIBCALLS-NEXT:    cmove a1, s1
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_4
; PURECAP-LIBCALLS-NEXT:    cflw fa0, 4(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB11_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    clc ra, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cfld fs0, 8(sp) # 8-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 64
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_fadd:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -48
; HYBRID-ATOMICS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    fsd fs0, 32(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lw.cap a0, (a0)
; HYBRID-ATOMICS-NEXT:    fmv.w.x fa5, a0
; HYBRID-ATOMICS-NEXT:    fmv.s fs0, fa0
; HYBRID-ATOMICS-NEXT:  .LBB11_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    fadd.s fa4, fa5, fs0
; HYBRID-ATOMICS-NEXT:    fmv.x.w a2, fa4
; HYBRID-ATOMICS-NEXT:    fsw fa5, 28(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 28
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_4_c
; HYBRID-ATOMICS-NEXT:    flw fa5, 28(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB11_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    fmv.s fa0, fa5
; HYBRID-ATOMICS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    fld fs0, 32(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 48
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_fadd:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -48
; HYBRID-LIBCALLS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    fsd fs0, 32(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    fmv.s fs0, fa0
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_4_c
; HYBRID-LIBCALLS-NEXT:    fmv.w.x fa0, a0
; HYBRID-LIBCALLS-NEXT:  .LBB11_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    fadd.s fa5, fa0, fs0
; HYBRID-LIBCALLS-NEXT:    fmv.x.w a2, fa5
; HYBRID-LIBCALLS-NEXT:    fsw fa0, 28(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 28
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_4_c
; HYBRID-LIBCALLS-NEXT:    flw fa0, 28(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB11_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    fld fs0, 32(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 48
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw fadd float addrspace(200)* %ptr, float %val seq_cst
  ret float %tmp
}

define float @atomic_cap_ptr_fsub(float addrspace(200)* %ptr, float %val) nounwind {
; PURECAP-ATOMICS-LABEL: atomic_cap_ptr_fsub:
; PURECAP-ATOMICS:       # %bb.0:
; PURECAP-ATOMICS-NEXT:    clw a1, 0(a0)
; PURECAP-ATOMICS-NEXT:    fmv.w.x fa5, a1
; PURECAP-ATOMICS-NEXT:  .LBB12_1: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # =>This Loop Header: Depth=1
; PURECAP-ATOMICS-NEXT:    # Child Loop BB12_3 Depth 2
; PURECAP-ATOMICS-NEXT:    fsub.s fa4, fa5, fa0
; PURECAP-ATOMICS-NEXT:    fmv.x.w a1, fa4
; PURECAP-ATOMICS-NEXT:    fmv.x.w a2, fa5
; PURECAP-ATOMICS-NEXT:  .LBB12_3: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # Parent Loop BB12_1 Depth=1
; PURECAP-ATOMICS-NEXT:    # => This Inner Loop Header: Depth=2
; PURECAP-ATOMICS-NEXT:    clr.w.aqrl a3, (a0)
; PURECAP-ATOMICS-NEXT:    bne a3, a2, .LBB12_5
; PURECAP-ATOMICS-NEXT:  # %bb.4: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # in Loop: Header=BB12_3 Depth=2
; PURECAP-ATOMICS-NEXT:    csc.w.rl a4, a1, (a0)
; PURECAP-ATOMICS-NEXT:    bnez a4, .LBB12_3
; PURECAP-ATOMICS-NEXT:  .LBB12_5: # %atomicrmw.start
; PURECAP-ATOMICS-NEXT:    # in Loop: Header=BB12_1 Depth=1
; PURECAP-ATOMICS-NEXT:    fmv.w.x fa5, a3
; PURECAP-ATOMICS-NEXT:    bne a3, a2, .LBB12_1
; PURECAP-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-ATOMICS-NEXT:    fmv.s fa0, fa5
; PURECAP-ATOMICS-NEXT:    cret
;
; PURECAP-LIBCALLS-LABEL: atomic_cap_ptr_fsub:
; PURECAP-LIBCALLS:       # %bb.0:
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, -64
; PURECAP-LIBCALLS-NEXT:    csc ra, 48(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s0, 32(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    csc s1, 16(sp) # 16-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    cfsd fs0, 8(sp) # 8-byte Folded Spill
; PURECAP-LIBCALLS-NEXT:    fmv.s fs0, fa0
; PURECAP-LIBCALLS-NEXT:    cmove s0, a0
; PURECAP-LIBCALLS-NEXT:    li a1, 0
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_load_4
; PURECAP-LIBCALLS-NEXT:    fmv.w.x fa0, a0
; PURECAP-LIBCALLS-NEXT:    cincoffset a0, sp, 4
; PURECAP-LIBCALLS-NEXT:    csetbounds s1, a0, 4
; PURECAP-LIBCALLS-NEXT:  .LBB12_1: # %atomicrmw.start
; PURECAP-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; PURECAP-LIBCALLS-NEXT:    fsub.s fa5, fa0, fs0
; PURECAP-LIBCALLS-NEXT:    fmv.x.w a2, fa5
; PURECAP-LIBCALLS-NEXT:    cfsw fa0, 4(sp)
; PURECAP-LIBCALLS-NEXT:    li a3, 5
; PURECAP-LIBCALLS-NEXT:    li a4, 5
; PURECAP-LIBCALLS-NEXT:    cmove a0, s0
; PURECAP-LIBCALLS-NEXT:    cmove a1, s1
; PURECAP-LIBCALLS-NEXT:    ccall __atomic_compare_exchange_4
; PURECAP-LIBCALLS-NEXT:    cflw fa0, 4(sp)
; PURECAP-LIBCALLS-NEXT:    beqz a0, .LBB12_1
; PURECAP-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; PURECAP-LIBCALLS-NEXT:    clc ra, 48(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s0, 32(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    clc s1, 16(sp) # 16-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cfld fs0, 8(sp) # 8-byte Folded Reload
; PURECAP-LIBCALLS-NEXT:    cincoffset sp, sp, 64
; PURECAP-LIBCALLS-NEXT:    cret
;
; HYBRID-ATOMICS-LABEL: atomic_cap_ptr_fsub:
; HYBRID-ATOMICS:       # %bb.0:
; HYBRID-ATOMICS-NEXT:    addi sp, sp, -48
; HYBRID-ATOMICS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    fsd fs0, 32(sp) # 8-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-ATOMICS-NEXT:    lw.cap a0, (a0)
; HYBRID-ATOMICS-NEXT:    fmv.w.x fa5, a0
; HYBRID-ATOMICS-NEXT:    fmv.s fs0, fa0
; HYBRID-ATOMICS-NEXT:  .LBB12_1: # %atomicrmw.start
; HYBRID-ATOMICS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-ATOMICS-NEXT:    fsub.s fa4, fa5, fs0
; HYBRID-ATOMICS-NEXT:    fmv.x.w a2, fa4
; HYBRID-ATOMICS-NEXT:    fsw fa5, 28(sp)
; HYBRID-ATOMICS-NEXT:    addi a1, sp, 28
; HYBRID-ATOMICS-NEXT:    li a3, 5
; HYBRID-ATOMICS-NEXT:    li a4, 5
; HYBRID-ATOMICS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    call __atomic_compare_exchange_4_c
; HYBRID-ATOMICS-NEXT:    flw fa5, 28(sp)
; HYBRID-ATOMICS-NEXT:    beqz a0, .LBB12_1
; HYBRID-ATOMICS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-ATOMICS-NEXT:    fmv.s fa0, fa5
; HYBRID-ATOMICS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    fld fs0, 32(sp) # 8-byte Folded Reload
; HYBRID-ATOMICS-NEXT:    addi sp, sp, 48
; HYBRID-ATOMICS-NEXT:    ret
;
; HYBRID-LIBCALLS-LABEL: atomic_cap_ptr_fsub:
; HYBRID-LIBCALLS:       # %bb.0:
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, -48
; HYBRID-LIBCALLS-NEXT:    sd ra, 40(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    fsd fs0, 32(sp) # 8-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    fmv.s fs0, fa0
; HYBRID-LIBCALLS-NEXT:    sc a0, 0(sp) # 16-byte Folded Spill
; HYBRID-LIBCALLS-NEXT:    li a1, 0
; HYBRID-LIBCALLS-NEXT:    call __atomic_load_4_c
; HYBRID-LIBCALLS-NEXT:    fmv.w.x fa0, a0
; HYBRID-LIBCALLS-NEXT:  .LBB12_1: # %atomicrmw.start
; HYBRID-LIBCALLS-NEXT:    # =>This Inner Loop Header: Depth=1
; HYBRID-LIBCALLS-NEXT:    fsub.s fa5, fa0, fs0
; HYBRID-LIBCALLS-NEXT:    fmv.x.w a2, fa5
; HYBRID-LIBCALLS-NEXT:    fsw fa0, 28(sp)
; HYBRID-LIBCALLS-NEXT:    addi a1, sp, 28
; HYBRID-LIBCALLS-NEXT:    li a3, 5
; HYBRID-LIBCALLS-NEXT:    li a4, 5
; HYBRID-LIBCALLS-NEXT:    lc a0, 0(sp) # 16-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    call __atomic_compare_exchange_4_c
; HYBRID-LIBCALLS-NEXT:    flw fa0, 28(sp)
; HYBRID-LIBCALLS-NEXT:    beqz a0, .LBB12_1
; HYBRID-LIBCALLS-NEXT:  # %bb.2: # %atomicrmw.end
; HYBRID-LIBCALLS-NEXT:    ld ra, 40(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    fld fs0, 32(sp) # 8-byte Folded Reload
; HYBRID-LIBCALLS-NEXT:    addi sp, sp, 48
; HYBRID-LIBCALLS-NEXT:    ret
  %tmp = atomicrmw fsub float addrspace(200)* %ptr, float %val seq_cst
  ret float %tmp
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; PURECAP: {{.*}}
