; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/bn_x931p-regression.ll
;; After a C13==NULL optimization in the MIPS backend,
;; openssl/crypto/bn/bn_x931p.c was failing.
;; Check that it works as expected
; RUN: llc -mtriple=mips64 -mcpu=cheri128 -mattr=+cheri128 --relocation-model=pic -target-abi purecap -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=PURECAP

declare i32 @b() addrspace(200)

; Calling a function with 9+ capability parameters would previously cause verification errors
define i32 @a(ptr addrspace(200) %0, ptr addrspace(200) %1, ptr addrspace(200) %2, ptr addrspace(200) %3, ptr addrspace(200) %4, ptr addrspace(200) %5, ptr addrspace(200) %6, ptr addrspace(200) %7, ptr addrspace(200) %8) addrspace(200) nounwind {
; PURECAP-LABEL: a:
; PURECAP:       # %bb.0:
; PURECAP-NEXT:    cincoffset $c11, $c11, -16
; PURECAP-NEXT:    csc $c17, $zero, 0($c11) # 16-byte Folded Spill
; PURECAP-NEXT:    lui $1, %pcrel_hi(_CHERI_CAPABILITY_TABLE_-8)
; PURECAP-NEXT:    daddiu $1, $1, %pcrel_lo(_CHERI_CAPABILITY_TABLE_-4)
; PURECAP-NEXT:    cgetpccincoffset $c1, $1
; PURECAP-NEXT:    clcbi $c12, %capcall20(b)($c1)
; PURECAP-NEXT:    cjalr $c12, $c17
; PURECAP-NEXT:    cgetnull $c13
; PURECAP-NEXT:    cgetnull $c13
; PURECAP-NEXT:    clc $c17, $zero, 0($c11) # 16-byte Folded Reload
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    cincoffset $c11, $c11, 16
  %ret = call i32 @b()
  ret i32 %ret
}
