runners:
  - name: cirun-gcp
    cloud: gcp
    instance_type: n4a-standard-32
    machine_image: ubuntu-minimal-2404-noble-arm64-v20260507
    region: us-east1-b
    preemptible: true
    extra_config:
      baseDisk:
        diskSizeGb: 60
    labels:
      - cirun-gcp-arm64x32
