; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=gvn %s -S -o - | FileCheck %s
source_filename = "std.593181b22e8ee5f3-cgu.14"
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

; Previously crashed when trying to coerce i64 0 to a CHERI nullptr

; Function Attrs: inlinehint nounwind uwtable
define fastcc void @_RNCINvMNtNtCs7EM0oBsqMk9_3std4sync9once_lockINtB5_8OnceLockINtNtB7_14reentrant_lock13ReentrantLockINtNtCsi5kCOIVVOQy_4core4cell7RefCellINtNtNtNtB9_2io8buffered10linewriter10LineWriterNtNtB2g_5stdio9StdoutRawEEEE10initializeNCINvB4_11get_or_initNCNvB2X_6stdout0E0zE0B9_(ptr addrspace(200) noundef nonnull writeonly align 8 captures(none) %0) addrspace(200) #0 {
; CHECK-LABEL: define fastcc void @_RNCINvMNtNtCs7EM0oBsqMk9_3std4sync9once_lockINtB5_8OnceLockINtNtB7_14reentrant_lock13ReentrantLockINtNtCsi5kCOIVVOQy_4core4cell7RefCellINtNtNtNtB9_2io8buffered10linewriter10LineWriterNtNtB2g_5stdio9StdoutRawEEEE10initializeNCINvB4_11get_or_initNCNvB2X_6stdout0E0zE0B9_(
; CHECK-SAME: ptr addrspace(200) noundef nonnull writeonly align 8 captures(none) [[TMP0:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    store i64 0, ptr addrspace(200) null, align 8
; CHECK-NEXT:    store ptr addrspace(200) null, ptr addrspace(200) [[TMP0]], align 8
; CHECK-NEXT:    ret void
;
  store i64 0, ptr addrspace(200) null, align 8
  %2 = load ptr addrspace(200), ptr addrspace(200) null, align 8
  store ptr addrspace(200) %2, ptr addrspace(200) %0, align 8
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p200(i64 immarg, ptr addrspace(200) captures(none)) addrspace(200) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p200(i64 immarg, ptr addrspace(200) captures(none)) addrspace(200) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite)
declare void @llvm.experimental.noalias.scope.decl(metadata) addrspace(200) #2

attributes #0 = { inlinehint nounwind uwtable "frame-pointer"="all" "target-cpu"="cheriot" "target-features"="+32bit,+c,+zca,+e,+m,+xcheriot" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: readwrite) }
