; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=gvn %s -S -o - | FileCheck %s
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

; Previously crashed when trying to coerce between i64 0 to a CHERI nullptr

define fastcc void @int2ptr(ptr addrspace(200) noundef nonnull writeonly align 8 captures(none) %0) addrspace(200) #0 {
; CHECK-LABEL: define fastcc void @int2ptr(
; CHECK-SAME: ptr addrspace(200) noundef nonnull writeonly align 8 captures(none) [[TMP0:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    store i64 0, ptr addrspace(200) null, align 8
; CHECK-NEXT:    store ptr addrspace(200) null, ptr addrspace(200) [[TMP0]], align 8
; CHECK-NEXT:    ret void
;
  store i64 0, ptr addrspace(200) null, align 8
  %2 = load ptr addrspace(200), ptr addrspace(200) null, align 8
  store ptr addrspace(200) %2, ptr addrspace(200) %0, align 8
  ret void
}

define fastcc void @ptr2int() addrspace(200) #0 {
; CHECK-LABEL: define fastcc void @ptr2int(
; CHECK-SAME: ) addrspace(200) #[[ATTR0]] {
; CHECK-NEXT:    store ptr addrspace(200) null, ptr addrspace(200) null, align 8
; CHECK-NEXT:    ret void
;
  store ptr addrspace(200) null, ptr addrspace(200) null, align 8
  %x = load i64, ptr addrspace(200) null, align 8
  %1 = trunc nuw nsw i64 %x to i32
  ret void
}

attributes #0 = { inlinehint nounwind uwtable "frame-pointer"="all" "target-cpu"="cheriot" "target-features"="+32bit,+c,+zca,+e,+m,+xcheriot" }
