// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 5
// RUN: llvm-mc %s -triple=riscv32 -mcpu=cheriot -mattr=+xcheri,+xcheriot | FileCheck %s -check-prefixes=CHERIOT

foo:
// CHERIOT: foo:
    auipcc ct3, %cheriot_compartment_hi(foo)
// CHERIOT: ct.auipcc	t3, %cheriot_compartment_code_hi(foo)
    auipcc ct3, %cheriot_compartment_code_hi(foo)
// CHERIOT: ct.auipcc	t3, %cheriot_compartment_code_hi(foo)
    clc  ct2, %cheriot_compartment_lo_i(foo)(ct2)
// CHERIOT: ct.clc	t2, %cheriot_compartment_lo_i(foo)(t2)
