// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %cheri_purecap_cc1 -emit-llvm -o - %s | FileCheck %s

// Check that arguments that are passed indirectly by pointer have the correct
// address space

// CHECK-LABEL: define dso_local void @_Z25notify_all_at_thread_exit11unique_lock(
// CHECK-SAME: ptr addrspace(200) nofree noundef align 1 dead_on_return dereferenceable(1) [[LK:%.*]]) addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[LK_INDIRECT_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[LK]], ptr addrspace(200) [[LK_INDIRECT_ADDR]], align 16
// CHECK-NEXT:    ret void
//

// CHECK-LABEL: define dso_local noundef signext i32 @main(
// CHECK-SAME: ) addrspace(200) #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4, addrspace(200)
// CHECK-NEXT:    [[L:%.*]] = alloca [[CLASS_UNIQUE_LOCK:%.*]], align 1, addrspace(200)
// CHECK-NEXT:    [[AGG_TMP:%.*]] = alloca [[CLASS_UNIQUE_LOCK]], align 1, addrspace(200)
// CHECK-NEXT:    store i32 0, ptr addrspace(200) [[RETVAL]], align 4
// CHECK-NEXT:    call addrspace(200) void @_ZN11unique_lockC1Ev(ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[L]])
// CHECK-NEXT:    call addrspace(200) void @_ZN11unique_lockC1ERKS_(ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[AGG_TMP]], ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[L]])
// CHECK-NEXT:    call addrspace(200) void @_Z25notify_all_at_thread_exit11unique_lock(ptr addrspace(200) nofree noundef align 1 dead_on_return dereferenceable(1) [[AGG_TMP]])
// CHECK-NEXT:    ret i32 0
//

class unique_lock {
  public:

// CHECK-LABEL: define linkonce_odr void @_ZN11unique_lockC1Ev(
// CHECK-SAME: ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[THIS:%.*]]) unnamed_addr addrspace(200) #[[ATTR0]] comdat align 2 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[THIS]], ptr addrspace(200) [[THIS_ADDR]], align 16
// CHECK-NEXT:    [[THIS1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[THIS_ADDR]], align 16
// CHECK-NEXT:    call addrspace(200) void @_ZN11unique_lockC2Ev(ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[THIS1]])
// CHECK-NEXT:    ret void
//
    unique_lock() { }

// CHECK-LABEL: define linkonce_odr void @_ZN11unique_lockC1ERKS_(
// CHECK-SAME: ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[THIS:%.*]], ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[TMP0:%.*]]) unnamed_addr addrspace(200) #[[ATTR0]] comdat align 2 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[DOTADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[THIS]], ptr addrspace(200) [[THIS_ADDR]], align 16
// CHECK-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[DOTADDR]], align 16
// CHECK-NEXT:    [[THIS1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[THIS_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[DOTADDR]], align 16
// CHECK-NEXT:    call addrspace(200) void @_ZN11unique_lockC2ERKS_(ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[THIS1]], ptr addrspace(200) noundef nonnull align 1 dereferenceable(1) [[TMP1]])
// CHECK-NEXT:    ret void
//
    unique_lock(unique_lock const&) { }
};

void notify_all_at_thread_exit(unique_lock lk) { }

int main(void) {
  unique_lock l;
  notify_all_at_thread_exit(l);
  return 0;
}

