// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %cheri_purecap_cc1 -O2 -std=c++11 -fcxx-exceptions -fexceptions -o -  %s -emit-llvm | FileCheck %s
/// Check that __tls_guard is emitted in AS200. This previously caused selection
/// failures (see https://github.com/CTSRD-CHERI/llvm/issues/269) but was fixed
/// by adding real TLS support, so keep checking that we emit it in AS200.

struct m {};
struct n {
  n() {}
};
thread_local m f;
thread_local n h;


// CHECK-LABEL: define dso_local void @_Z1rv(
// CHECK-SAME: ) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void r() {
  (void)f;
}
