// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 %s -o - "-triple" "riscv32-unknown-unknown" "-emit-llvm" "-mframe-pointer=none" "-mcmodel=small" "-target-abi" "cheriot-baremetal" "-target-feature" "+xcheriot" "-Oz" "-Werror" -std=c2x | FileCheck %s

// Check that we can generate code for C11 atomic increment of uintptr

// CHECK-LABEL: define dso_local void @test1(
// CHECK-SAME: ) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[P:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
// CHECK-NEXT:    call addrspace(200) void @llvm.lifetime.start.p200(ptr addrspace(200) nonnull [[P]]) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic ptr addrspace(200), ptr addrspace(200) [[P]] seq_cst, align 8, !tbaa [[TBAA11:![0-9]+]]
// CHECK-NEXT:    br label %[[ATOMIC_OP:.*]]
// CHECK:       [[ATOMIC_OP]]:
// CHECK-NEXT:    [[TMP0:%.*]] = phi ptr addrspace(200) [ [[ATOMIC_LOAD]], %[[ENTRY]] ], [ [[TMP3:%.*]], %[[ATOMIC_OP]] ]
// CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr addrspace(200) [[TMP0]], i32 1
// CHECK-NEXT:    [[TMP2:%.*]] = cmpxchg ptr addrspace(200) [[P]], ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[TMP1]] seq_cst seq_cst, align 8
// CHECK-NEXT:    [[TMP3]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { ptr addrspace(200), i1 } [[TMP2]], 1
// CHECK-NEXT:    br i1 [[TMP4]], label %[[ATOMIC_CONT:.*]], label %[[ATOMIC_OP]]
// CHECK:       [[ATOMIC_CONT]]:
// CHECK-NEXT:    call addrspace(200) void @llvm.lifetime.end.p200(ptr addrspace(200) nonnull [[P]]) #[[ATTR2]]
// CHECK-NEXT:    ret void
//
void test1() {
  _Atomic(__UINTPTR_TYPE__) p;
  ++p;
}
//.
// CHECK: [[META9:![0-9]+]] = !{!"omnipotent char", [[META10:![0-9]+]], i64 0}
// CHECK: [[META10]] = !{!"Simple C/C++ TBAA"}
// CHECK: [[TBAA11]] = !{[[META9]], [[META9]], i64 0}

