; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: %cheri_llc %s -o - | FileCheck %s -check-prefixes CHECK,MIPS
; RUN: %cheri_purecap_llc %s -o - | FileCheck %s -check-prefixes CHECK,PURECAP
; ModuleID = '/Users/alex/cheri/llvm-project/clang/test/Sema/cheri/strtol-regression.c'
; This previously crashed due to the use of getPointerTy instead of getPointerRangeTy

; Check that we generate the same code as MIPS
define void @b(i8 %a) local_unnamed_addr addrspace(200) {
; MIPS-LABEL: b:
; MIPS:       # %bb.0: # %entry
; MIPS-NEXT:    sll $1, $4, 0
; MIPS-NEXT:    andi $1, $1, 255
; MIPS-NEXT:    addiu $1, $1, -65
; MIPS-NEXT:    sltiu $3, $1, 38
; MIPS-NEXT:    dsll $2, $1, 32
; MIPS-NEXT:    beqz $3, .LBB0_2
; MIPS-NEXT:    nop
; MIPS-NEXT:  # %bb.1: # %entry
; MIPS-NEXT:    dsrl $1, $2, 32
; MIPS-NEXT:    daddiu $2, $zero, 1
; MIPS-NEXT:    dsllv $1, $2, $1
; MIPS-NEXT:    daddiu $2, $zero, 63
; MIPS-NEXT:    dsll $2, $2, 32
; MIPS-NEXT:    daddiu $2, $2, 63
; MIPS-NEXT:    and $1, $1, $2
; MIPS-NEXT:    bnez $1, .LBB0_3
; MIPS-NEXT:    nop
; MIPS-NEXT:  .LBB0_2: # %if.end
; MIPS-NEXT:    jr $ra
; MIPS-NEXT:    nop
; MIPS-NEXT:  .LBB0_3: # %for.cond.preheader
; MIPS-NEXT:    .insn
;
; PURECAP-LABEL: b:
; PURECAP:       # %bb.0: # %entry
; PURECAP-NEXT:    sll $1, $4, 0
; PURECAP-NEXT:    andi $1, $1, 255
; PURECAP-NEXT:    addiu $1, $1, -65
; PURECAP-NEXT:    sltiu $3, $1, 38
; PURECAP-NEXT:    dsll $2, $1, 32
; PURECAP-NEXT:    beqz $3, .LBB0_2
; PURECAP-NEXT:    nop
; PURECAP-NEXT:  # %bb.1: # %entry
; PURECAP-NEXT:    dsrl $1, $2, 32
; PURECAP-NEXT:    daddiu $2, $zero, 1
; PURECAP-NEXT:    dsllv $1, $2, $1
; PURECAP-NEXT:    daddiu $2, $zero, 63
; PURECAP-NEXT:    dsll $2, $2, 32
; PURECAP-NEXT:    daddiu $2, $2, 63
; PURECAP-NEXT:    and $1, $1, $2
; PURECAP-NEXT:    bnez $1, .LBB0_3
; PURECAP-NEXT:    nop
; PURECAP-NEXT:  .LBB0_2: # %if.end
; PURECAP-NEXT:    cjr $c17
; PURECAP-NEXT:    nop
; PURECAP-NEXT:  .LBB0_3: # %for.cond.preheader
; PURECAP-NEXT:    .insn
entry:
  switch i8 %a, label %if.end [
    i8 102, label %for.cond.preheader
    i8 101, label %for.cond.preheader
    i8 100, label %for.cond.preheader
    i8 99, label %for.cond.preheader
    i8 98, label %for.cond.preheader
    i8 97, label %for.cond.preheader
    i8 70, label %for.cond.preheader
    i8 69, label %for.cond.preheader
    i8 68, label %for.cond.preheader
    i8 67, label %for.cond.preheader
    i8 66, label %for.cond.preheader
    i8 65, label %for.cond.preheader
  ]

for.cond.preheader:                               ; preds = %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry, %entry
  unreachable

if.end:                                           ; preds = %entry
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
