; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s | FileCheck %s -check-prefixes=RV64I
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s | FileCheck %s -check-prefixes=RV32I


define void @lshr_32bytes(ptr %src.ptr, ptr %bitOff.ptr, ptr %dst) nounwind {
; RV64I-LABEL: lshr_32bytes:
; RV64I:       # %bb.0:
; RV64I-NEXT:    addi sp, sp, -224
; RV64I-NEXT:    sd ra, 216(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s0, 208(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s1, 200(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s2, 192(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s3, 184(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s4, 176(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s5, 168(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s6, 160(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s7, 152(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s8, 144(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s9, 136(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s10, 128(sp) # 8-byte Folded Spill
; RV64I-NEXT:    sd s11, 120(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu a3, 0(a0)
; RV64I-NEXT:    sd a3, 48(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu a3, 1(a0)
; RV64I-NEXT:    sd a3, 40(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu a3, 2(a0)
; RV64I-NEXT:    sd a3, 32(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu a3, 3(a0)
; RV64I-NEXT:    sd a3, 24(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu a3, 4(a0)
; RV64I-NEXT:    sd a3, 16(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu a3, 5(a0)
; RV64I-NEXT:    sd a3, 8(sp) # 8-byte Folded Spill
; RV64I-NEXT:    lbu t1, 6(a0)
; RV64I-NEXT:    lbu t2, 7(a0)
; RV64I-NEXT:    lbu t3, 8(a0)
; RV64I-NEXT:    lbu t4, 9(a0)
; RV64I-NEXT:    lbu t5, 10(a0)
; RV64I-NEXT:    lbu t6, 11(a0)
; RV64I-NEXT:    lbu s0, 12(a0)
; RV64I-NEXT:    lbu s1, 13(a0)
; RV64I-NEXT:    lbu s2, 14(a0)
; RV64I-NEXT:    lbu s3, 15(a0)
; RV64I-NEXT:    lbu s4, 16(a0)
; RV64I-NEXT:    lbu s5, 17(a0)
; RV64I-NEXT:    lbu s6, 18(a0)
; RV64I-NEXT:    lbu s7, 19(a0)
; RV64I-NEXT:    lbu s8, 20(a0)
; RV64I-NEXT:    lbu s9, 21(a0)
; RV64I-NEXT:    lbu s10, 1(a1)
; RV64I-NEXT:    lbu s11, 0(a1)
; RV64I-NEXT:    lbu ra, 2(a1)
; RV64I-NEXT:    lbu a3, 3(a1)
; RV64I-NEXT:    slli s10, s10, 8
; RV64I-NEXT:    or s10, s10, s11
; RV64I-NEXT:    slli ra, ra, 16
; RV64I-NEXT:    slli a3, a3, 24
; RV64I-NEXT:    lbu s11, 5(a1)
; RV64I-NEXT:    or a3, a3, ra
; RV64I-NEXT:    or a3, a3, s10
; RV64I-NEXT:    lbu s10, 4(a1)
; RV64I-NEXT:    slli s11, s11, 8
; RV64I-NEXT:    lbu ra, 6(a1)
; RV64I-NEXT:    lbu a1, 7(a1)
; RV64I-NEXT:    or s11, s11, s10
; RV64I-NEXT:    lbu s10, 22(a0)
; RV64I-NEXT:    slli ra, ra, 16
; RV64I-NEXT:    slli a1, a1, 24
; RV64I-NEXT:    or a1, a1, ra
; RV64I-NEXT:    lbu ra, 23(a0)
; RV64I-NEXT:    or a1, a1, s11
; RV64I-NEXT:    lbu s11, 24(a0)
; RV64I-NEXT:    slli a1, a1, 32
; RV64I-NEXT:    or t0, a1, a3
; RV64I-NEXT:    lbu a7, 25(a0)
; RV64I-NEXT:    lbu a6, 26(a0)
; RV64I-NEXT:    lbu a5, 27(a0)
; RV64I-NEXT:    lbu a1, 31(a0)
; RV64I-NEXT:    lbu a3, 30(a0)
; RV64I-NEXT:    lbu a4, 29(a0)
; RV64I-NEXT:    lbu a0, 28(a0)
; RV64I-NEXT:    sb a1, 87(sp)
; RV64I-NEXT:    sb a3, 86(sp)
; RV64I-NEXT:    sb a4, 85(sp)
; RV64I-NEXT:    sb a0, 84(sp)
; RV64I-NEXT:    sb a5, 83(sp)
; RV64I-NEXT:    sb a6, 82(sp)
; RV64I-NEXT:    sb a7, 81(sp)
; RV64I-NEXT:    sb s11, 80(sp)
; RV64I-NEXT:    sb ra, 79(sp)
; RV64I-NEXT:    sb s10, 78(sp)
; RV64I-NEXT:    sb s9, 77(sp)
; RV64I-NEXT:    sb s8, 76(sp)
; RV64I-NEXT:    sb s7, 75(sp)
; RV64I-NEXT:    sb s6, 74(sp)
; RV64I-NEXT:    sb s5, 73(sp)
; RV64I-NEXT:    sb s4, 72(sp)
; RV64I-NEXT:    sb s3, 71(sp)
; RV64I-NEXT:    sb s2, 70(sp)
; RV64I-NEXT:    sb s1, 69(sp)
; RV64I-NEXT:    sb s0, 68(sp)
; RV64I-NEXT:    sb t6, 67(sp)
; RV64I-NEXT:    sb t5, 66(sp)
; RV64I-NEXT:    sb t4, 65(sp)
; RV64I-NEXT:    sb zero, 119(sp)
; RV64I-NEXT:    sb zero, 118(sp)
; RV64I-NEXT:    sb zero, 117(sp)
; RV64I-NEXT:    sb zero, 116(sp)
; RV64I-NEXT:    sb zero, 115(sp)
; RV64I-NEXT:    sb zero, 114(sp)
; RV64I-NEXT:    sb zero, 113(sp)
; RV64I-NEXT:    sb zero, 112(sp)
; RV64I-NEXT:    sb zero, 111(sp)
; RV64I-NEXT:    sb zero, 110(sp)
; RV64I-NEXT:    sb zero, 109(sp)
; RV64I-NEXT:    sb zero, 108(sp)
; RV64I-NEXT:    sb zero, 107(sp)
; RV64I-NEXT:    sb zero, 106(sp)
; RV64I-NEXT:    sb zero, 105(sp)
; RV64I-NEXT:    sb zero, 104(sp)
; RV64I-NEXT:    sb zero, 103(sp)
; RV64I-NEXT:    sb zero, 102(sp)
; RV64I-NEXT:    sb zero, 101(sp)
; RV64I-NEXT:    sb zero, 100(sp)
; RV64I-NEXT:    sb zero, 99(sp)
; RV64I-NEXT:    sb zero, 98(sp)
; RV64I-NEXT:    sb zero, 97(sp)
; RV64I-NEXT:    sb zero, 96(sp)
; RV64I-NEXT:    sb zero, 95(sp)
; RV64I-NEXT:    sb zero, 94(sp)
; RV64I-NEXT:    sb zero, 93(sp)
; RV64I-NEXT:    sb zero, 92(sp)
; RV64I-NEXT:    sb zero, 91(sp)
; RV64I-NEXT:    sb zero, 90(sp)
; RV64I-NEXT:    sb zero, 89(sp)
; RV64I-NEXT:    sb zero, 88(sp)
; RV64I-NEXT:    sb t3, 64(sp)
; RV64I-NEXT:    sb t2, 63(sp)
; RV64I-NEXT:    sb t1, 62(sp)
; RV64I-NEXT:    ld a0, 8(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sb a0, 61(sp)
; RV64I-NEXT:    ld a0, 16(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sb a0, 60(sp)
; RV64I-NEXT:    ld a0, 24(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sb a0, 59(sp)
; RV64I-NEXT:    ld a0, 32(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sb a0, 58(sp)
; RV64I-NEXT:    ld a0, 40(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sb a0, 57(sp)
; RV64I-NEXT:    ld a0, 48(sp) # 8-byte Folded Reload
; RV64I-NEXT:    sb a0, 56(sp)
; RV64I-NEXT:    slli a0, t0, 56
; RV64I-NEXT:    srli a0, a0, 59
; RV64I-NEXT:    addi a3, sp, 56
; RV64I-NEXT:    add a3, a3, a0
; RV64I-NEXT:    lbu a0, 9(a3)
; RV64I-NEXT:    lbu a1, 8(a3)
; RV64I-NEXT:    lbu a4, 10(a3)
; RV64I-NEXT:    lbu a5, 11(a3)
; RV64I-NEXT:    slli a0, a0, 8
; RV64I-NEXT:    or a0, a0, a1
; RV64I-NEXT:    slli a4, a4, 16
; RV64I-NEXT:    slli a5, a5, 24
; RV64I-NEXT:    or a4, a5, a4
; RV64I-NEXT:    or a0, a4, a0
; RV64I-NEXT:    lbu a1, 13(a3)
; RV64I-NEXT:    lbu a4, 12(a3)
; RV64I-NEXT:    lbu a5, 14(a3)
; RV64I-NEXT:    lbu a6, 15(a3)
; RV64I-NEXT:    slli a1, a1, 8
; RV64I-NEXT:    or a1, a1, a4
; RV64I-NEXT:    slli a5, a5, 16
; RV64I-NEXT:    slli a6, a6, 24
; RV64I-NEXT:    or a4, a6, a5
; RV64I-NEXT:    or a1, a4, a1
; RV64I-NEXT:    slli a1, a1, 32
; RV64I-NEXT:    or a4, a1, a0
; RV64I-NEXT:    andi a1, t0, 7
; RV64I-NEXT:    lbu a0, 17(a3)
; RV64I-NEXT:    lbu a5, 16(a3)
; RV64I-NEXT:    lbu a6, 18(a3)
; RV64I-NEXT:    lbu a7, 19(a3)
; RV64I-NEXT:    slli a0, a0, 8
; RV64I-NEXT:    or a0, a0, a5
; RV64I-NEXT:    slli a6, a6, 16
; RV64I-NEXT:    slli a7, a7, 24
; RV64I-NEXT:    or a5, a7, a6
; RV64I-NEXT:    or a0, a5, a0
; RV64I-NEXT:    lbu a5, 21(a3)
; RV64I-NEXT:    lbu a6, 20(a3)
; RV64I-NEXT:    lbu a7, 22(a3)
; RV64I-NEXT:    lbu t0, 23(a3)
; RV64I-NEXT:    slli a5, a5, 8
; RV64I-NEXT:    or a5, a5, a6
; RV64I-NEXT:    slli a7, a7, 16
; RV64I-NEXT:    slli t0, t0, 24
; RV64I-NEXT:    or a6, t0, a7
; RV64I-NEXT:    or a5, a6, a5
; RV64I-NEXT:    slli a5, a5, 32
; RV64I-NEXT:    or a5, a5, a0
; RV64I-NEXT:    slli a0, a5, 1
; RV64I-NEXT:    not a6, a1
; RV64I-NEXT:    sll a0, a0, a6
; RV64I-NEXT:    lbu a6, 1(a3)
; RV64I-NEXT:    lbu a7, 0(a3)
; RV64I-NEXT:    lbu t0, 2(a3)
; RV64I-NEXT:    lbu t1, 3(a3)
; RV64I-NEXT:    slli a6, a6, 8
; RV64I-NEXT:    or a6, a6, a7
; RV64I-NEXT:    slli t0, t0, 16
; RV64I-NEXT:    slli t1, t1, 24
; RV64I-NEXT:    or a7, t1, t0
; RV64I-NEXT:    or a6, a7, a6
; RV64I-NEXT:    lbu a7, 5(a3)
; RV64I-NEXT:    lbu t0, 4(a3)
; RV64I-NEXT:    lbu t1, 6(a3)
; RV64I-NEXT:    lbu t2, 7(a3)
; RV64I-NEXT:    slli a7, a7, 8
; RV64I-NEXT:    or a7, a7, t0
; RV64I-NEXT:    slli t1, t1, 16
; RV64I-NEXT:    slli t2, t2, 24
; RV64I-NEXT:    or t0, t2, t1
; RV64I-NEXT:    or a7, t0, a7
; RV64I-NEXT:    slli a7, a7, 32
; RV64I-NEXT:    or a6, a7, a6
; RV64I-NEXT:    lbu a7, 25(a3)
; RV64I-NEXT:    lbu t0, 24(a3)
; RV64I-NEXT:    lbu t1, 26(a3)
; RV64I-NEXT:    lbu t2, 27(a3)
; RV64I-NEXT:    slli a7, a7, 8
; RV64I-NEXT:    or a7, a7, t0
; RV64I-NEXT:    slli t1, t1, 16
; RV64I-NEXT:    slli t2, t2, 24
; RV64I-NEXT:    or t0, t2, t1
; RV64I-NEXT:    or a7, t0, a7
; RV64I-NEXT:    lbu t0, 29(a3)
; RV64I-NEXT:    lbu t1, 28(a3)
; RV64I-NEXT:    lbu t2, 30(a3)
; RV64I-NEXT:    lbu a3, 31(a3)
; RV64I-NEXT:    slli t0, t0, 8
; RV64I-NEXT:    or t0, t0, t1
; RV64I-NEXT:    slli t2, t2, 16
; RV64I-NEXT:    slli a3, a3, 24
; RV64I-NEXT:    or a3, a3, t2
; RV64I-NEXT:    slli t1, a4, 1
; RV64I-NEXT:    or a3, a3, t0
; RV64I-NEXT:    xori t0, a1, 63
; RV64I-NEXT:    sll t1, t1, t0
; RV64I-NEXT:    slli a3, a3, 32
; RV64I-NEXT:    or a7, a3, a7
; RV64I-NEXT:    slli a3, a7, 1
; RV64I-NEXT:    sll t0, a3, t0
; RV64I-NEXT:    srl a3, a4, a1
; RV64I-NEXT:    srl a4, a6, a1
; RV64I-NEXT:    srl a5, a5, a1
; RV64I-NEXT:    srl a1, a7, a1
; RV64I-NEXT:    srli a6, a5, 48
; RV64I-NEXT:    sb a6, 22(a2)
; RV64I-NEXT:    srli a6, a5, 40
; RV64I-NEXT:    sb a6, 21(a2)
; RV64I-NEXT:    srli a6, a5, 32
; RV64I-NEXT:    sb a6, 20(a2)
; RV64I-NEXT:    srli a6, a5, 24
; RV64I-NEXT:    sb a6, 19(a2)
; RV64I-NEXT:    srli a6, a5, 16
; RV64I-NEXT:    sb a6, 18(a2)
; RV64I-NEXT:    or a6, a5, t0
; RV64I-NEXT:    sb a5, 16(a2)
; RV64I-NEXT:    srli a5, a5, 8
; RV64I-NEXT:    sb a5, 17(a2)
; RV64I-NEXT:    srli a5, a1, 56
; RV64I-NEXT:    sb a5, 31(a2)
; RV64I-NEXT:    srli a5, a1, 48
; RV64I-NEXT:    sb a5, 30(a2)
; RV64I-NEXT:    srli a5, a1, 40
; RV64I-NEXT:    sb a5, 29(a2)
; RV64I-NEXT:    srli a5, a1, 32
; RV64I-NEXT:    sb a5, 28(a2)
; RV64I-NEXT:    srli a5, a1, 24
; RV64I-NEXT:    sb a5, 27(a2)
; RV64I-NEXT:    srli a5, a1, 16
; RV64I-NEXT:    sb a5, 26(a2)
; RV64I-NEXT:    sb a1, 24(a2)
; RV64I-NEXT:    srli a1, a1, 8
; RV64I-NEXT:    sb a1, 25(a2)
; RV64I-NEXT:    srli a1, a4, 48
; RV64I-NEXT:    sb a1, 6(a2)
; RV64I-NEXT:    srli a1, a4, 40
; RV64I-NEXT:    sb a1, 5(a2)
; RV64I-NEXT:    srli a1, a4, 32
; RV64I-NEXT:    sb a1, 4(a2)
; RV64I-NEXT:    srli a1, a4, 24
; RV64I-NEXT:    sb a1, 3(a2)
; RV64I-NEXT:    srli a1, a4, 16
; RV64I-NEXT:    sb a1, 2(a2)
; RV64I-NEXT:    or a1, a4, t1
; RV64I-NEXT:    sb a4, 0(a2)
; RV64I-NEXT:    srli a4, a4, 8
; RV64I-NEXT:    sb a4, 1(a2)
; RV64I-NEXT:    srli a4, a3, 48
; RV64I-NEXT:    sb a4, 14(a2)
; RV64I-NEXT:    srli a4, a3, 40
; RV64I-NEXT:    sb a4, 13(a2)
; RV64I-NEXT:    srli a4, a3, 32
; RV64I-NEXT:    sb a4, 12(a2)
; RV64I-NEXT:    srli a4, a3, 24
; RV64I-NEXT:    sb a4, 11(a2)
; RV64I-NEXT:    srli a4, a3, 16
; RV64I-NEXT:    sb a4, 10(a2)
; RV64I-NEXT:    or a0, a3, a0
; RV64I-NEXT:    sb a3, 8(a2)
; RV64I-NEXT:    srli a3, a3, 8
; RV64I-NEXT:    sb a3, 9(a2)
; RV64I-NEXT:    srli a3, a6, 56
; RV64I-NEXT:    sb a3, 23(a2)
; RV64I-NEXT:    srli a1, a1, 56
; RV64I-NEXT:    sb a1, 7(a2)
; RV64I-NEXT:    srli a0, a0, 56
; RV64I-NEXT:    sb a0, 15(a2)
; RV64I-NEXT:    ld ra, 216(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s0, 208(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s1, 200(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s2, 192(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s3, 184(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s4, 176(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s5, 168(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s6, 160(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s7, 152(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s8, 144(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s9, 136(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s10, 128(sp) # 8-byte Folded Reload
; RV64I-NEXT:    ld s11, 120(sp) # 8-byte Folded Reload
; RV64I-NEXT:    addi sp, sp, 224
; RV64I-NEXT:    ret
;
; RV32I-LABEL: lshr_32bytes:
; RV32I:       # %bb.0:
; RV32I-NEXT:    addi sp, sp, -144
; RV32I-NEXT:    sw ra, 140(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s0, 136(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s1, 132(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s2, 128(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s3, 124(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s4, 120(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s5, 116(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s6, 112(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s7, 108(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s8, 104(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s9, 100(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s10, 96(sp) # 4-byte Folded Spill
; RV32I-NEXT:    sw s11, 92(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu a3, 0(a0)
; RV32I-NEXT:    sw a3, 24(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu a3, 1(a0)
; RV32I-NEXT:    sw a3, 20(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu a3, 2(a0)
; RV32I-NEXT:    sw a3, 16(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu a3, 3(a0)
; RV32I-NEXT:    sw a3, 12(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu a3, 4(a0)
; RV32I-NEXT:    sw a3, 8(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu a3, 5(a0)
; RV32I-NEXT:    sw a3, 4(sp) # 4-byte Folded Spill
; RV32I-NEXT:    lbu t1, 6(a0)
; RV32I-NEXT:    lbu t2, 7(a0)
; RV32I-NEXT:    lbu t3, 8(a0)
; RV32I-NEXT:    lbu t4, 9(a0)
; RV32I-NEXT:    lbu t5, 10(a0)
; RV32I-NEXT:    lbu t6, 11(a0)
; RV32I-NEXT:    lbu s0, 12(a0)
; RV32I-NEXT:    lbu s1, 13(a0)
; RV32I-NEXT:    lbu s2, 14(a0)
; RV32I-NEXT:    lbu s3, 15(a0)
; RV32I-NEXT:    lbu s4, 16(a0)
; RV32I-NEXT:    lbu s5, 17(a0)
; RV32I-NEXT:    lbu s6, 18(a0)
; RV32I-NEXT:    lbu s7, 19(a0)
; RV32I-NEXT:    lbu s8, 20(a0)
; RV32I-NEXT:    lbu s11, 1(a1)
; RV32I-NEXT:    lbu s9, 21(a0)
; RV32I-NEXT:    lbu s10, 22(a0)
; RV32I-NEXT:    lbu ra, 0(a1)
; RV32I-NEXT:    slli s11, s11, 8
; RV32I-NEXT:    lbu a3, 2(a1)
; RV32I-NEXT:    lbu a1, 3(a1)
; RV32I-NEXT:    or s11, s11, ra
; RV32I-NEXT:    lbu ra, 23(a0)
; RV32I-NEXT:    slli a3, a3, 16
; RV32I-NEXT:    slli a1, a1, 24
; RV32I-NEXT:    or a1, a1, a3
; RV32I-NEXT:    lbu a7, 24(a0)
; RV32I-NEXT:    or t0, a1, s11
; RV32I-NEXT:    lbu s11, 25(a0)
; RV32I-NEXT:    lbu a6, 26(a0)
; RV32I-NEXT:    lbu a5, 27(a0)
; RV32I-NEXT:    lbu a1, 31(a0)
; RV32I-NEXT:    lbu a3, 30(a0)
; RV32I-NEXT:    lbu a4, 29(a0)
; RV32I-NEXT:    lbu a0, 28(a0)
; RV32I-NEXT:    sb a1, 59(sp)
; RV32I-NEXT:    sb a3, 58(sp)
; RV32I-NEXT:    sb a4, 57(sp)
; RV32I-NEXT:    sb a0, 56(sp)
; RV32I-NEXT:    sb a5, 55(sp)
; RV32I-NEXT:    sb a6, 54(sp)
; RV32I-NEXT:    sb s11, 53(sp)
; RV32I-NEXT:    sb a7, 52(sp)
; RV32I-NEXT:    sb ra, 51(sp)
; RV32I-NEXT:    sb s10, 50(sp)
; RV32I-NEXT:    sb s9, 49(sp)
; RV32I-NEXT:    sb s8, 48(sp)
; RV32I-NEXT:    sb s7, 47(sp)
; RV32I-NEXT:    sb s6, 46(sp)
; RV32I-NEXT:    sb s5, 45(sp)
; RV32I-NEXT:    sb s4, 44(sp)
; RV32I-NEXT:    sb zero, 91(sp)
; RV32I-NEXT:    sb zero, 90(sp)
; RV32I-NEXT:    sb zero, 89(sp)
; RV32I-NEXT:    sb zero, 88(sp)
; RV32I-NEXT:    sb zero, 87(sp)
; RV32I-NEXT:    sb zero, 86(sp)
; RV32I-NEXT:    sb zero, 85(sp)
; RV32I-NEXT:    sb zero, 84(sp)
; RV32I-NEXT:    sb zero, 83(sp)
; RV32I-NEXT:    sb zero, 82(sp)
; RV32I-NEXT:    sb zero, 81(sp)
; RV32I-NEXT:    sb zero, 80(sp)
; RV32I-NEXT:    sb zero, 79(sp)
; RV32I-NEXT:    sb zero, 78(sp)
; RV32I-NEXT:    sb zero, 77(sp)
; RV32I-NEXT:    sb zero, 76(sp)
; RV32I-NEXT:    sb zero, 75(sp)
; RV32I-NEXT:    sb zero, 74(sp)
; RV32I-NEXT:    sb zero, 73(sp)
; RV32I-NEXT:    sb zero, 72(sp)
; RV32I-NEXT:    sb zero, 71(sp)
; RV32I-NEXT:    sb zero, 70(sp)
; RV32I-NEXT:    sb zero, 69(sp)
; RV32I-NEXT:    sb zero, 68(sp)
; RV32I-NEXT:    sb zero, 67(sp)
; RV32I-NEXT:    sb zero, 66(sp)
; RV32I-NEXT:    sb zero, 65(sp)
; RV32I-NEXT:    sb zero, 64(sp)
; RV32I-NEXT:    sb zero, 63(sp)
; RV32I-NEXT:    sb zero, 62(sp)
; RV32I-NEXT:    sb zero, 61(sp)
; RV32I-NEXT:    sb zero, 60(sp)
; RV32I-NEXT:    sb s3, 43(sp)
; RV32I-NEXT:    sb s2, 42(sp)
; RV32I-NEXT:    sb s1, 41(sp)
; RV32I-NEXT:    sb s0, 40(sp)
; RV32I-NEXT:    sb t6, 39(sp)
; RV32I-NEXT:    sb t5, 38(sp)
; RV32I-NEXT:    sb t4, 37(sp)
; RV32I-NEXT:    sb t3, 36(sp)
; RV32I-NEXT:    sb t2, 35(sp)
; RV32I-NEXT:    sb t1, 34(sp)
; RV32I-NEXT:    lw a0, 4(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sb a0, 33(sp)
; RV32I-NEXT:    lw a0, 8(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sb a0, 32(sp)
; RV32I-NEXT:    lw a0, 12(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sb a0, 31(sp)
; RV32I-NEXT:    lw a0, 16(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sb a0, 30(sp)
; RV32I-NEXT:    lw a0, 20(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sb a0, 29(sp)
; RV32I-NEXT:    lw a0, 24(sp) # 4-byte Folded Reload
; RV32I-NEXT:    sb a0, 28(sp)
; RV32I-NEXT:    slli a0, t0, 24
; RV32I-NEXT:    srli a0, a0, 27
; RV32I-NEXT:    addi a4, sp, 28
; RV32I-NEXT:    add a4, a4, a0
; RV32I-NEXT:    lbu a0, 5(a4)
; RV32I-NEXT:    lbu a1, 4(a4)
; RV32I-NEXT:    lbu a3, 6(a4)
; RV32I-NEXT:    lbu a5, 7(a4)
; RV32I-NEXT:    slli a0, a0, 8
; RV32I-NEXT:    or a0, a0, a1
; RV32I-NEXT:    slli a3, a3, 16
; RV32I-NEXT:    slli a5, a5, 24
; RV32I-NEXT:    or a3, a5, a3
; RV32I-NEXT:    or t5, a3, a0
; RV32I-NEXT:    andi a3, t0, 7
; RV32I-NEXT:    lbu a0, 9(a4)
; RV32I-NEXT:    lbu a1, 8(a4)
; RV32I-NEXT:    lbu a5, 10(a4)
; RV32I-NEXT:    lbu a6, 11(a4)
; RV32I-NEXT:    slli a0, a0, 8
; RV32I-NEXT:    or a0, a0, a1
; RV32I-NEXT:    slli a5, a5, 16
; RV32I-NEXT:    slli a6, a6, 24
; RV32I-NEXT:    or a1, a6, a5
; RV32I-NEXT:    or a6, a1, a0
; RV32I-NEXT:    slli a0, a6, 1
; RV32I-NEXT:    not t1, a3
; RV32I-NEXT:    sll a0, a0, t1
; RV32I-NEXT:    lbu a1, 1(a4)
; RV32I-NEXT:    lbu a5, 0(a4)
; RV32I-NEXT:    lbu a7, 2(a4)
; RV32I-NEXT:    lbu t0, 3(a4)
; RV32I-NEXT:    slli a1, a1, 8
; RV32I-NEXT:    or a1, a1, a5
; RV32I-NEXT:    slli a7, a7, 16
; RV32I-NEXT:    slli t0, t0, 24
; RV32I-NEXT:    or a5, t0, a7
; RV32I-NEXT:    or t0, a5, a1
; RV32I-NEXT:    slli a1, t5, 1
; RV32I-NEXT:    xori t2, a3, 31
; RV32I-NEXT:    sll a1, a1, t2
; RV32I-NEXT:    lbu a5, 13(a4)
; RV32I-NEXT:    lbu a7, 12(a4)
; RV32I-NEXT:    lbu t3, 14(a4)
; RV32I-NEXT:    lbu t4, 15(a4)
; RV32I-NEXT:    slli a5, a5, 8
; RV32I-NEXT:    or a5, a5, a7
; RV32I-NEXT:    slli t3, t3, 16
; RV32I-NEXT:    slli t4, t4, 24
; RV32I-NEXT:    or a7, t4, t3
; RV32I-NEXT:    or t3, a7, a5
; RV32I-NEXT:    lbu a5, 17(a4)
; RV32I-NEXT:    lbu a7, 16(a4)
; RV32I-NEXT:    lbu t4, 18(a4)
; RV32I-NEXT:    lbu t6, 19(a4)
; RV32I-NEXT:    slli a5, a5, 8
; RV32I-NEXT:    or a5, a5, a7
; RV32I-NEXT:    slli t4, t4, 16
; RV32I-NEXT:    slli t6, t6, 24
; RV32I-NEXT:    or a7, t6, t4
; RV32I-NEXT:    or t4, a7, a5
; RV32I-NEXT:    slli a5, t4, 1
; RV32I-NEXT:    sll a7, a5, t1
; RV32I-NEXT:    lbu a5, 21(a4)
; RV32I-NEXT:    lbu t6, 20(a4)
; RV32I-NEXT:    lbu s0, 22(a4)
; RV32I-NEXT:    lbu s1, 23(a4)
; RV32I-NEXT:    slli a5, a5, 8
; RV32I-NEXT:    or a5, a5, t6
; RV32I-NEXT:    slli s0, s0, 16
; RV32I-NEXT:    slli s1, s1, 24
; RV32I-NEXT:    or s0, s1, s0
; RV32I-NEXT:    or s0, s0, a5
; RV32I-NEXT:    lbu a5, 25(a4)
; RV32I-NEXT:    lbu t6, 24(a4)
; RV32I-NEXT:    lbu s1, 26(a4)
; RV32I-NEXT:    lbu s2, 27(a4)
; RV32I-NEXT:    slli a5, a5, 8
; RV32I-NEXT:    or a5, a5, t6
; RV32I-NEXT:    slli s1, s1, 16
; RV32I-NEXT:    slli s2, s2, 24
; RV32I-NEXT:    or t6, s2, s1
; RV32I-NEXT:    or t6, t6, a5
; RV32I-NEXT:    lbu a5, 29(a4)
; RV32I-NEXT:    lbu s1, 28(a4)
; RV32I-NEXT:    slli s2, t6, 1
; RV32I-NEXT:    sll t1, s2, t1
; RV32I-NEXT:    slli a5, a5, 8
; RV32I-NEXT:    or a5, a5, s1
; RV32I-NEXT:    lbu s1, 30(a4)
; RV32I-NEXT:    lbu a4, 31(a4)
; RV32I-NEXT:    slli s2, t3, 1
; RV32I-NEXT:    sll s2, s2, t2
; RV32I-NEXT:    slli s1, s1, 16
; RV32I-NEXT:    slli a4, a4, 24
; RV32I-NEXT:    or a4, a4, s1
; RV32I-NEXT:    slli s1, s0, 1
; RV32I-NEXT:    sll s1, s1, t2
; RV32I-NEXT:    or s3, a4, a5
; RV32I-NEXT:    slli a4, s3, 1
; RV32I-NEXT:    sll t2, a4, t2
; RV32I-NEXT:    srl a4, t5, a3
; RV32I-NEXT:    srl a5, t0, a3
; RV32I-NEXT:    srl t0, t3, a3
; RV32I-NEXT:    srl a6, a6, a3
; RV32I-NEXT:    srl t3, s0, a3
; RV32I-NEXT:    srl t4, t4, a3
; RV32I-NEXT:    srl t5, t6, a3
; RV32I-NEXT:    srl a3, s3, a3
; RV32I-NEXT:    srli t6, t5, 16
; RV32I-NEXT:    sb t6, 26(a2)
; RV32I-NEXT:    or t2, t5, t2
; RV32I-NEXT:    sb t5, 24(a2)
; RV32I-NEXT:    srli t5, t5, 8
; RV32I-NEXT:    sb t5, 25(a2)
; RV32I-NEXT:    srli t5, a3, 24
; RV32I-NEXT:    sb t5, 31(a2)
; RV32I-NEXT:    srli t5, a3, 16
; RV32I-NEXT:    sb t5, 30(a2)
; RV32I-NEXT:    sb a3, 28(a2)
; RV32I-NEXT:    srli a3, a3, 8
; RV32I-NEXT:    sb a3, 29(a2)
; RV32I-NEXT:    srli a3, t4, 16
; RV32I-NEXT:    sb a3, 18(a2)
; RV32I-NEXT:    or a3, t4, s1
; RV32I-NEXT:    sb t4, 16(a2)
; RV32I-NEXT:    srli t4, t4, 8
; RV32I-NEXT:    sb t4, 17(a2)
; RV32I-NEXT:    srli t4, t3, 16
; RV32I-NEXT:    sb t4, 22(a2)
; RV32I-NEXT:    or t1, t3, t1
; RV32I-NEXT:    sb t3, 20(a2)
; RV32I-NEXT:    srli t3, t3, 8
; RV32I-NEXT:    sb t3, 21(a2)
; RV32I-NEXT:    srli t3, a6, 16
; RV32I-NEXT:    sb t3, 10(a2)
; RV32I-NEXT:    or t3, a6, s2
; RV32I-NEXT:    sb a6, 8(a2)
; RV32I-NEXT:    srli a6, a6, 8
; RV32I-NEXT:    sb a6, 9(a2)
; RV32I-NEXT:    srli a6, t0, 16
; RV32I-NEXT:    sb a6, 14(a2)
; RV32I-NEXT:    or a6, t0, a7
; RV32I-NEXT:    sb t0, 12(a2)
; RV32I-NEXT:    srli a7, t0, 8
; RV32I-NEXT:    sb a7, 13(a2)
; RV32I-NEXT:    srli a7, a5, 16
; RV32I-NEXT:    sb a7, 2(a2)
; RV32I-NEXT:    or a1, a5, a1
; RV32I-NEXT:    sb a5, 0(a2)
; RV32I-NEXT:    srli a5, a5, 8
; RV32I-NEXT:    sb a5, 1(a2)
; RV32I-NEXT:    srli a5, a4, 16
; RV32I-NEXT:    sb a5, 6(a2)
; RV32I-NEXT:    or a0, a4, a0
; RV32I-NEXT:    sb a4, 4(a2)
; RV32I-NEXT:    srli a4, a4, 8
; RV32I-NEXT:    sb a4, 5(a2)
; RV32I-NEXT:    srli a4, t2, 24
; RV32I-NEXT:    sb a4, 27(a2)
; RV32I-NEXT:    srli a3, a3, 24
; RV32I-NEXT:    sb a3, 19(a2)
; RV32I-NEXT:    srli a3, t1, 24
; RV32I-NEXT:    sb a3, 23(a2)
; RV32I-NEXT:    srli a3, t3, 24
; RV32I-NEXT:    sb a3, 11(a2)
; RV32I-NEXT:    srli a3, a6, 24
; RV32I-NEXT:    sb a3, 15(a2)
; RV32I-NEXT:    srli a1, a1, 24
; RV32I-NEXT:    sb a1, 3(a2)
; RV32I-NEXT:    srli a0, a0, 24
; RV32I-NEXT:    sb a0, 7(a2)
; RV32I-NEXT:    lw ra, 140(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s0, 136(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s1, 132(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s2, 128(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s3, 124(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s4, 120(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s5, 116(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s6, 112(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s7, 108(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s8, 104(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s9, 100(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s10, 96(sp) # 4-byte Folded Reload
; RV32I-NEXT:    lw s11, 92(sp) # 4-byte Folded Reload
; RV32I-NEXT:    addi sp, sp, 144
; RV32I-NEXT:    ret
  %src = load i256, ptr %src.ptr, align 1
  %bitOff = load i256, ptr %bitOff.ptr, align 1
  %res = lshr i256 %src, %bitOff
  store i256 %res, ptr %dst, align 1
  ret void
}
