; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/hoist-alloca.ll
; REQUIRES: asserts
; XFAIL: *
; XFAIL due to change over to RVY capability formats.
; Check that we can hoist the csetbounds for a local alloca outside of loops
; We know that it's always tagged and unsealed so machinelicm should be able to
; to hoist the csetbounds instructions.
; TODO: for MIPS "simple-register-coalescing" moves the CheriBoundedStackPseudoImm back into the loop.
; In general this will be faster than loading from the stack, but it's probably worse
; than using a callee-saved register for loops with many iterations.

; Generated from this code:
; void call(int *src, int *dst);
;
; void hoist_alloca_uncond(int cond) {
;   int buf1[123];
;   int buf2[22];
;   for (int i = 0; i < 100; i++) {
;     call(buf1, buf2);
;   }
; }
;
; void hoist_alloca_cond(int cond) {
;   int buf1[123];
;   int buf2[22];
;   for (int i = 0; i < 100; i++) {
;     if (cond) {
;       call(buf1, buf2);
;     }
;   }
; }

; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -o %t.mir -stop-before=early-machinelicm < %s
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -run-pass=early-machinelicm -debug-only=machinelicm %t.mir -o /dev/null 2>%t.dbg
; RUN: FileCheck --input-file=%t.dbg --check-prefix=MACHINELICM-DBG %s
; Check that MachineLICM hoists the CheriBoundedStackPseudoImm (MIPS) / IncOffset+SetBoundsImm (RISCV) instructions
; MACHINELICM-DBG-LABEL: ******** Pre-regalloc Machine LICM: hoist_alloca_uncond
; MACHINELICM-DBG: Hoisting [[INC:%[0-9]+]]:ygpr = CIncOffsetImm %stack.0.buf1, 0
; MACHINELICM-DBG-NEXT:  from %bb.2 to %bb.0
; MACHINELICM-DBG: Hoisting [[BOUNDS:%[0-9]+]]:ygpr = CSetBoundsImm [[INC]]:ygpr, 512
; MACHINELICM-DBG-NEXT:  from %bb.2 to %bb.0
; MACHINELICM-DBG: Hoisting [[INC:%[0-9]+]]:ygpr = CIncOffsetImm %stack.1.buf2, 0
; MACHINELICM-DBG-NEXT:  from %bb.2 to %bb.0
; MACHINELICM-DBG: Hoisting [[BOUNDS:%[0-9]+]]:ygpr = CSetBoundsImm [[INC]]:ygpr, 88
; MACHINELICM-DBG-NEXT:  from %bb.2 to %bb.0
; MACHINELICM-DBG-LABEL: ******** Pre-regalloc Machine LICM: hoist_alloca_cond
; MACHINELICM-DBG: Hoisting [[INC:%[0-9]+]]:ygpr = CIncOffsetImm %stack.0.buf1, 0
; MACHINELICM-DBG-NEXT:  from %bb.3 to %bb.0
; MACHINELICM-DBG: Hoisting [[BOUNDS:%[0-9]+]]:ygpr = CSetBoundsImm [[INC]]:ygpr, 512
; MACHINELICM-DBG-NEXT:  from %bb.3 to %bb.0
; MACHINELICM-DBG: Hoisting [[INC:%[0-9]+]]:ygpr = CIncOffsetImm %stack.1.buf2, 0
; MACHINELICM-DBG-NEXT:  from %bb.3 to %bb.0
; MACHINELICM-DBG: Hoisting [[BOUNDS:%[0-9]+]]:ygpr = CSetBoundsImm [[INC]]:ygpr, 88
; MACHINELICM-DBG-NEXT:  from %bb.3 to %bb.0

; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -O1 -o - < %s | FileCheck %s

define void @hoist_alloca_uncond(i32 signext %cond) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: hoist_alloca_uncond:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -704
; CHECK-NEXT:    csc ra, 696(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s0, 688(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s1, 680(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s2, 672(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s3, 664(sp) # 8-byte Folded Spill
; CHECK-NEXT:    cincoffset s0, sp, 704
; CHECK-NEXT:    andi a0, sp, -64
; CHECK-NEXT:    csetaddr sp, sp, a0
; CHECK-NEXT:    li s3, 100
; CHECK-NEXT:    cincoffset a0, sp, 128
; CHECK-NEXT:    cincoffset a1, sp, 40
; CHECK-NEXT:    csetbounds s1, a0, 512
; CHECK-NEXT:    csetbounds s2, a1, 88
; CHECK-NEXT:  .LBB0_1: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmove a0, s1
; CHECK-NEXT:    cmove a1, s2
; CHECK-NEXT:    ccall call
; CHECK-NEXT:    addi s3, s3, -1
; CHECK-NEXT:    bnez s3, .LBB0_1
; CHECK-NEXT:  # %bb.2: # %for.cond.cleanup
; CHECK-NEXT:    cincoffset sp, s0, -704
; CHECK-NEXT:    clc ra, 696(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s0, 688(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s1, 680(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s2, 672(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s3, 664(sp) # 8-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 704
; CHECK-NEXT:    cret
entry:
  %buf1 = alloca [123 x i32], align 4, addrspace(200)
  %buf2 = alloca [22 x i32], align 4, addrspace(200)
  br label %for.body

for.cond.cleanup:
  ret void

for.body:
  %i.04 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %arraydecay = getelementptr inbounds [123 x i32], [123 x i32] addrspace(200)* %buf1, i64 0, i64 0
  %arraydecay1 = getelementptr inbounds [22 x i32], [22 x i32] addrspace(200)* %buf2, i64 0, i64 0
  call void @call(i32 addrspace(200)* nonnull %arraydecay, i32 addrspace(200)* nonnull %arraydecay1)
  %inc = add nuw nsw i32 %i.04, 1
  %exitcond.not = icmp eq i32 %inc, 100
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

declare void @call(i32 addrspace(200)*, i32 addrspace(200)*) local_unnamed_addr addrspace(200) nounwind

define void @hoist_alloca_cond(i32 signext %cond) local_unnamed_addr addrspace(200) nounwind {
; CHECK-LABEL: hoist_alloca_cond:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    cincoffset sp, sp, -704
; CHECK-NEXT:    csc ra, 696(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s0, 688(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s1, 680(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s2, 672(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s3, 664(sp) # 8-byte Folded Spill
; CHECK-NEXT:    csc s4, 656(sp) # 8-byte Folded Spill
; CHECK-NEXT:    cincoffset s0, sp, 704
; CHECK-NEXT:    andi a1, sp, -64
; CHECK-NEXT:    csetaddr sp, sp, a1
; CHECK-NEXT:    mv s1, a0
; CHECK-NEXT:    li s4, 100
; CHECK-NEXT:    cincoffset a0, sp, 128
; CHECK-NEXT:    cincoffset a1, sp, 40
; CHECK-NEXT:    csetbounds s2, a0, 512
; CHECK-NEXT:    csetbounds s3, a1, 88
; CHECK-NEXT:    j .LBB1_2
; CHECK-NEXT:  .LBB1_1: # %for.inc
; CHECK-NEXT:    # in Loop: Header=BB1_2 Depth=1
; CHECK-NEXT:    addi s4, s4, -1
; CHECK-NEXT:    beqz s4, .LBB1_4
; CHECK-NEXT:  .LBB1_2: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    beqz s1, .LBB1_1
; CHECK-NEXT:  # %bb.3: # %if.then
; CHECK-NEXT:    # in Loop: Header=BB1_2 Depth=1
; CHECK-NEXT:    cmove a0, s2
; CHECK-NEXT:    cmove a1, s3
; CHECK-NEXT:    ccall call
; CHECK-NEXT:    j .LBB1_1
; CHECK-NEXT:  .LBB1_4: # %for.cond.cleanup
; CHECK-NEXT:    cincoffset sp, s0, -704
; CHECK-NEXT:    clc ra, 696(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s0, 688(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s1, 680(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s2, 672(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s3, 664(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clc s4, 656(sp) # 8-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 704
; CHECK-NEXT:    cret
entry:
  %buf1 = alloca [123 x i32], align 4, addrspace(200)
  %buf2 = alloca [22 x i32], align 4, addrspace(200)
  %tobool.not = icmp eq i32 %cond, 0
  br label %for.body

for.cond.cleanup:
  ret void

for.body:
  %i.04 = phi i32 [ 0, %entry ], [ %inc, %for.inc ]
  br i1 %tobool.not, label %for.inc, label %if.then

if.then:
  %arraydecay = getelementptr inbounds [123 x i32], [123 x i32] addrspace(200)* %buf1, i64 0, i64 0
  %arraydecay1 = getelementptr inbounds [22 x i32], [22 x i32] addrspace(200)* %buf2, i64 0, i64 0
  call void @call(i32 addrspace(200)* nonnull %arraydecay, i32 addrspace(200)* nonnull %arraydecay1)
  br label %for.inc

for.inc:
  %inc = add nuw nsw i32 %i.04, 1
  %exitcond.not = icmp eq i32 %inc, 100
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
