; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 2
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/memcpy-preserve-tags-size-not-multiple.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -o - -O0 -verify-machineinstrs %s | FileCheck %s -check-prefixes CHECK
; Check that we can inline memmove/memcpy despite having the must_preserve_cheri_tags property and the size not
; being a multiple of CAP_SIZE. Since the pointers are aligned we can start with capability copies and use
; word/byte copies for the trailing bytes.
declare void @llvm.memmove.p200i8.p200i8.i64(i8 addrspace(200)* nocapture, i8 addrspace(200)* nocapture readonly, i64, i1) addrspace(200)
declare void @llvm.memcpy.p200i8.p200i8.i64(i8 addrspace(200)* nocapture, i8 addrspace(200)* nocapture readonly, i64, i1) addrspace(200)

define void @test_string_memmove(i8 addrspace(200)* %dst, i8 addrspace(200)* %src) addrspace(200) nounwind {
  ; Note: has must_preserve_cheri_tags, but this memmove can still be inlined since it's aligned
; CHECK-LABEL: test_string_memmove:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmove a7, a1
; CHECK-NEXT:    cmove a1, a0
; CHECK-NEXT:    clc a0, 0(a7)
; CHECK-NEXT:    clc a2, 8(a7)
; CHECK-NEXT:    clc a3, 16(a7)
; CHECK-NEXT:    clc a4, 24(a7)
; CHECK-NEXT:    clc a5, 32(a7)
; CHECK-NEXT:    clw a6, 40(a7)
; CHECK-NEXT:    clb a7, 44(a7)
; CHECK-NEXT:    csb a7, 44(a1)
; CHECK-NEXT:    csw a6, 40(a1)
; CHECK-NEXT:    csc a5, 32(a1)
; CHECK-NEXT:    csc a4, 24(a1)
; CHECK-NEXT:    csc a3, 16(a1)
; CHECK-NEXT:    csc a2, 8(a1)
; CHECK-NEXT:    csc a0, 0(a1)
; CHECK-NEXT:    cret
  call void @llvm.memmove.p200i8.p200i8.i64(i8 addrspace(200)* align 16 %dst, i8 addrspace(200)* align 16 %src, i64 45, i1 false) must_preserve_cheri_tags
  ret void
}

define void @test_string_memcpy(i8 addrspace(200)* %dst, i8 addrspace(200)* %src) addrspace(200) nounwind {
  ; Note: has must_preserve_cheri_tags, but this memcpy can still be inlined since it's aligned
; CHECK-LABEL: test_string_memcpy:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cincoffset sp, sp, -16
; CHECK-NEXT:    csc a1, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    cmove a1, a0
; CHECK-NEXT:    clc a0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    clb a2, 44(a0)
; CHECK-NEXT:    csb a2, 44(a1)
; CHECK-NEXT:    clw a2, 40(a0)
; CHECK-NEXT:    csw a2, 40(a1)
; CHECK-NEXT:    clc a2, 32(a0)
; CHECK-NEXT:    csc a2, 32(a1)
; CHECK-NEXT:    clc a2, 24(a0)
; CHECK-NEXT:    csc a2, 24(a1)
; CHECK-NEXT:    clc a2, 16(a0)
; CHECK-NEXT:    csc a2, 16(a1)
; CHECK-NEXT:    clc a2, 8(a0)
; CHECK-NEXT:    csc a2, 8(a1)
; CHECK-NEXT:    clc a0, 0(a0)
; CHECK-NEXT:    csc a0, 0(a1)
; CHECK-NEXT:    cincoffset sp, sp, 16
; CHECK-NEXT:    cret
  call void @llvm.memcpy.p200i8.p200i8.i64(i8 addrspace(200)* align 16 %dst, i8 addrspace(200)* align 16 %src, i64 45, i1 false) must_preserve_cheri_tags
  ret void
}
