; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/stack-bounds-opaque-spill-too-early.ll
;; After merging to LLVM 15 the stack bounds pass the switch to opqaue pointers caused
;; miscompilations in the stack bounding pass (the unbounded value was used instead of
;; the bounded one due to the removal of the bitcast instructions).
; RUN: opt -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f -passes=cheri-bound-allocas -o - -S %s | FileCheck %s
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f %s -o - | FileCheck %s -check-prefix ASM
target datalayout = "e-m:e-pf200:64:64:64:32-p:32:32-i64:64-n32-S128-A200-P200-G200"

declare void @llvm.lifetime.start.p200(ptr addrspace(200) nocapture) addrspace(200)

declare ptr addrspace(200) @cheribsdtest_dynamic_identity_cap(ptr addrspace(200) noundef) addrspace(200)

declare void @cheribsdtest_check_cap_eq(ptr addrspace(200) noundef, ptr addrspace(200) noundef) addrspace(200)

define dso_local void @lazy_bind_args() addrspace(200) nounwind {
; ASM-LABEL: lazy_bind_args:
; ASM:       # %bb.0: # %entry
; ASM-NEXT:    cincoffset sp, sp, -16
; ASM-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; ASM-NEXT:    cincoffset a0, sp, 0
; ASM-NEXT:    csetbounds a0, a0, 8
; ASM-NEXT:    csc a0, 0(sp)
; ASM-NEXT:    ccall cheribsdtest_dynamic_identity_cap
; ASM-NEXT:    clc a1, 0(sp)
; ASM-NEXT:    cmove a2, a0
; ASM-NEXT:    cmove a0, a1
; ASM-NEXT:    cmove a1, a2
; ASM-NEXT:    ccall cheribsdtest_check_cap_eq
; ASM-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; ASM-NEXT:    cincoffset sp, sp, 16
; ASM-NEXT:    cret
; CHECK-LABEL: define dso_local void @lazy_bind_args
; CHECK-SAME: () addrspace(200) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CAP:%.*]] = alloca ptr addrspace(200), align 8, addrspace(200)
; CHECK-NEXT:    call addrspace(200) void @llvm.lifetime.start.p200(ptr addrspace(200) nonnull [[CAP]])
; CHECK-NEXT:    [[TMP0:%.*]] = call addrspace(200) ptr addrspace(200) @llvm.cheri.bounded.stack.cap.i32(ptr addrspace(200) [[CAP]], i32 8)
; CHECK-NEXT:    store ptr addrspace(200) [[TMP0]], ptr addrspace(200) [[CAP]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = call addrspace(200) ptr addrspace(200) @llvm.cheri.bounded.stack.cap.i32(ptr addrspace(200) [[CAP]], i32 8)
; CHECK-NEXT:    [[CALL:%.*]] = call addrspace(200) ptr addrspace(200) @cheribsdtest_dynamic_identity_cap(ptr addrspace(200) noundef nonnull [[TMP1]])
; CHECK-NEXT:    [[TMP2:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[CAP]], align 8
; CHECK-NEXT:    call addrspace(200) void @cheribsdtest_check_cap_eq(ptr addrspace(200) noundef [[TMP2]], ptr addrspace(200) noundef [[CALL]])
; CHECK-NEXT:    ret void
entry:
  %cap = alloca ptr addrspace(200), align 8, addrspace(200)
  call addrspace(200) void @llvm.lifetime.start.p200(ptr addrspace(200) nonnull %cap)
  store ptr addrspace(200) %cap, ptr addrspace(200) %cap, align 8
  %call = call addrspace(200) ptr addrspace(200) @cheribsdtest_dynamic_identity_cap(ptr addrspace(200) noundef nonnull %cap)
  %0 = load ptr addrspace(200), ptr addrspace(200) %cap, align 8
  call addrspace(200) void @cheribsdtest_check_cap_eq(ptr addrspace(200) noundef %0, ptr addrspace(200) noundef %call)
  ret void
}
