; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; DO NOT EDIT -- This file was generated from test/CodeGen/CHERI-Generic/Inputs/unaligned-loads-stores-purecap.ll
; RUN: llc -mtriple=riscv32 --relocation-model=pic -target-abi il32pc64f -mattr=+xcheri,+xcheripurecap,+f %s -o - | FileCheck %s

@a1 = addrspace(200) global i64 0, align 1
@a2 = addrspace(200) global i64 0, align 2
@a4 = addrspace(200) global i64 0, align 4
@a8 = addrspace(200) global i64 0, align 8

define i64 @load_global_i64_align_1(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: load_global_i64_align_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB0_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %got_pcrel_hi(a1)
; CHECK-NEXT:    clc a0, %pcrel_lo(.LBB0_1)(a0)
; CHECK-NEXT:    clbu a1, 1(a0)
; CHECK-NEXT:    clbu a2, 0(a0)
; CHECK-NEXT:    clbu a3, 2(a0)
; CHECK-NEXT:    clbu a4, 3(a0)
; CHECK-NEXT:    clbu a5, 4(a0)
; CHECK-NEXT:    slli a1, a1, 8
; CHECK-NEXT:    clbu a6, 5(a0)
; CHECK-NEXT:    or a1, a1, a2
; CHECK-NEXT:    clbu a2, 6(a0)
; CHECK-NEXT:    clbu a0, 7(a0)
; CHECK-NEXT:    slli a3, a3, 16
; CHECK-NEXT:    slli a4, a4, 24
; CHECK-NEXT:    or a3, a4, a3
; CHECK-NEXT:    slli a6, a6, 8
; CHECK-NEXT:    slli a2, a2, 16
; CHECK-NEXT:    slli a0, a0, 24
; CHECK-NEXT:    or a4, a6, a5
; CHECK-NEXT:    or a2, a0, a2
; CHECK-NEXT:    or a0, a3, a1
; CHECK-NEXT:    or a1, a2, a4
; CHECK-NEXT:    cret
  %ret = load i64, i64 addrspace(200)* @a1, align 1
  ret i64 %ret
}

define i64 @load_global_i64_align_2(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: load_global_i64_align_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB1_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %got_pcrel_hi(a2)
; CHECK-NEXT:    clc a0, %pcrel_lo(.LBB1_1)(a0)
; CHECK-NEXT:    clhu a1, 2(a0)
; CHECK-NEXT:    clhu a2, 6(a0)
; CHECK-NEXT:    clhu a3, 0(a0)
; CHECK-NEXT:    clhu a4, 4(a0)
; CHECK-NEXT:    slli a0, a1, 16
; CHECK-NEXT:    slli a1, a2, 16
; CHECK-NEXT:    or a0, a0, a3
; CHECK-NEXT:    or a1, a1, a4
; CHECK-NEXT:    cret
  %ret = load i64, i64 addrspace(200)* @a2, align 2
  ret i64 %ret
}

define i64 @load_global_i64_align_4(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: load_global_i64_align_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB2_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a1, %got_pcrel_hi(a4)
; CHECK-NEXT:    clc a1, %pcrel_lo(.LBB2_1)(a1)
; CHECK-NEXT:    clw a0, 0(a1)
; CHECK-NEXT:    clw a1, 4(a1)
; CHECK-NEXT:    cret
  %ret = load i64, i64 addrspace(200)* @a4, align 4
  ret i64 %ret
}

define i64 @load_global_i64_align_8(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: load_global_i64_align_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB3_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a1, %got_pcrel_hi(a8)
; CHECK-NEXT:    clc a1, %pcrel_lo(.LBB3_1)(a1)
; CHECK-NEXT:    clw a0, 0(a1)
; CHECK-NEXT:    clw a1, 4(a1)
; CHECK-NEXT:    cret
  %ret = load i64, i64 addrspace(200)* @a8, align 8
  ret i64 %ret
}

define void @store_global_i64_align_1(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: store_global_i64_align_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB4_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a2, %got_pcrel_hi(a1)
; CHECK-NEXT:    clc a2, %pcrel_lo(.LBB4_1)(a2)
; CHECK-NEXT:    srli a3, a1, 24
; CHECK-NEXT:    csb a3, 7(a2)
; CHECK-NEXT:    srli a3, a1, 16
; CHECK-NEXT:    csb a1, 4(a2)
; CHECK-NEXT:    csb a0, 0(a2)
; CHECK-NEXT:    csb a3, 6(a2)
; CHECK-NEXT:    srli a1, a1, 8
; CHECK-NEXT:    srli a3, a0, 24
; CHECK-NEXT:    csb a1, 5(a2)
; CHECK-NEXT:    csb a3, 3(a2)
; CHECK-NEXT:    srli a1, a0, 16
; CHECK-NEXT:    srli a0, a0, 8
; CHECK-NEXT:    csb a1, 2(a2)
; CHECK-NEXT:    csb a0, 1(a2)
; CHECK-NEXT:    cret
  store i64 %y, i64 addrspace(200)* @a1, align 1
  ret void
}

define void @store_global_i64_align_2(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: store_global_i64_align_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB5_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a2, %got_pcrel_hi(a2)
; CHECK-NEXT:    clc a2, %pcrel_lo(.LBB5_1)(a2)
; CHECK-NEXT:    csh a1, 4(a2)
; CHECK-NEXT:    srli a1, a1, 16
; CHECK-NEXT:    csh a0, 0(a2)
; CHECK-NEXT:    srli a0, a0, 16
; CHECK-NEXT:    csh a1, 6(a2)
; CHECK-NEXT:    csh a0, 2(a2)
; CHECK-NEXT:    cret
  store i64 %y, i64 addrspace(200)* @a2, align 2
  ret void
}

define void @store_global_i64_align_4(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: store_global_i64_align_4:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB6_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a2, %got_pcrel_hi(a4)
; CHECK-NEXT:    clc a2, %pcrel_lo(.LBB6_1)(a2)
; CHECK-NEXT:    csw a1, 4(a2)
; CHECK-NEXT:    csw a0, 0(a2)
; CHECK-NEXT:    cret
  store i64 %y, i64 addrspace(200)* @a4, align 4
  ret void
}

define void @store_global_i64_align_8(i64 %y) addrspace(200) nounwind {
; CHECK-LABEL: store_global_i64_align_8:
; CHECK:       # %bb.0:
; CHECK-NEXT:  .LBB7_1: # Label of block must be emitted
; CHECK-NEXT:    auipcc a2, %got_pcrel_hi(a8)
; CHECK-NEXT:    clc a2, %pcrel_lo(.LBB7_1)(a2)
; CHECK-NEXT:    csw a1, 4(a2)
; CHECK-NEXT:    csw a0, 0(a2)
; CHECK-NEXT:    cret
  store i64 %y, i64 addrspace(200)* @a8, align 8
  ret void
}
