; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt --passes=instcombine -S %s | FileCheck %s
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

define dso_local noundef i32 @sum_me() unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: define dso_local noundef i32 @sum_me(
; CHECK-SAME: ) unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[START:.*:]]
; CHECK-NEXT:    tail call void @_RNvCs8d4ROkmze3o_7___rustc35___rust_no_alloc_shim_is_unstable_v2() #[[ATTR5:[0-9]+]]
; CHECK-NEXT:    br i1 false, label %[[BB3:.*]], label %[[BB5_I:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    unreachable
; CHECK:       [[BB5_I]]:
; CHECK-NEXT:    ret i32 6
;
start:
  tail call addrspace(200) void @_RNvCs8d4ROkmze3o_7___rustc35___rust_no_alloc_shim_is_unstable_v2() #5
  %0 = tail call noundef align 4 dereferenceable_or_null(12) addrspace(200) ptr addrspace(200) @_RNvCs8d4ROkmze3o_7___rustc12___rust_alloc(i32 noundef signext 12, i32 noundef signext 4) #5
  %1 = tail call addrspace(200) i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) %0)
  %2 = icmp eq i32 %1, 0
  br i1 %2, label %bb3, label %bb5.i

bb3:                                              ; preds = %start
  tail call addrspace(200) void @_RNvNtCs2n8kLYkaXas_5alloc5alloc18handle_alloc_error(i32 noundef 4, i32 noundef 12) #6
  unreachable

bb5.i:                                            ; preds = %start
  tail call addrspace(200) void @_RNvCs8d4ROkmze3o_7___rustc14___rust_dealloc(ptr addrspace(200) noundef nonnull %0, i32 noundef signext 12, i32 noundef signext range(i32 1, -2147483647) 4) #5
  ret i32 6
}

; Function Attrs: nounwind
declare dso_local void @_RNvCs8d4ROkmze3o_7___rustc35___rust_no_alloc_shim_is_unstable_v2() unnamed_addr addrspace(200) #0

; Function Attrs: nounwind allockind("alloc,uninitialized,aligned") allocsize(0)
declare dso_local noalias noundef ptr addrspace(200) @_RNvCs8d4ROkmze3o_7___rustc12___rust_alloc(i32 noundef signext, i32 allocalign noundef signext) unnamed_addr addrspace(200) #1

; Function Attrs: mustprogress nofree nosync nounwind willreturn memory(none)
declare i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200)) addrspace(200) #2

; Function Attrs: nounwind allockind("free")
declare dso_local void @_RNvCs8d4ROkmze3o_7___rustc14___rust_dealloc(ptr addrspace(200) allocptr noundef, i32 noundef signext, i32 noundef signext) unnamed_addr addrspace(200) #3

; Function Attrs: cold minsize noreturn nounwind optsize
declare dso_local void @_RNvNtCs2n8kLYkaXas_5alloc5alloc18handle_alloc_error(i32 noundef range(i32 1, -2147483647), i32 noundef) unnamed_addr addrspace(200) #4

attributes #0 = { nounwind "target-cpu"="cheriot" "target-features"="+32bit,+c,+zca,+e,+m,+xcheriot" }
attributes #1 = { nounwind allockind("alloc,uninitialized,aligned") allocsize(0) "alloc-family"="__rust_alloc" "alloc-variant-zeroed"="_RNvCs8d4ROkmze3o_7___rustc19___rust_alloc_zeroed" "target-cpu"="cheriot" "target-features"="+32bit,+c,+zca,+e,+m,+xcheriot" }
attributes #2 = { mustprogress nofree nosync nounwind willreturn memory(none) }
attributes #3 = { nounwind allockind("free") "alloc-family"="__rust_alloc" "target-cpu"="cheriot" "target-features"="+32bit,+c,+zca,+e,+m,+xcheriot" }
attributes #4 = { cold minsize noreturn nounwind optsize "target-cpu"="cheriot" "target-features"="+32bit,+c,+zca,+e,+m,+xcheriot" }
attributes #5 = { nounwind }
