; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S %s -o - | FileCheck %s
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

define i32 @bar(i32 %x) addrspace(200) {
; CHECK-LABEL: define i32 @bar(
; CHECK-SAME: i32 [[X:%.*]]) addrspace(200) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SHR:%.*]] = and i32 [[X]], 2147483647
; CHECK-NEXT:    ret i32 [[SHR]]
;
entry:
  %shl.i = shl i32 %x, 1
  %0 = getelementptr i8, ptr addrspace(200) null, i32 %shl.i
  %1 = getelementptr i8, ptr addrspace(200) %0, i32 1
  %2 = tail call addrspace(200) i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200) %1)
  %shr = lshr i32 %2, 1
  ret i32 %shr
}

declare i32 @llvm.cheri.cap.address.get.i32(ptr addrspace(200)) addrspace(200)

define i32 @baz(i32 %x) addrspace(200) {
; CHECK-LABEL: define i32 @baz(
; CHECK-SAME: i32 [[X:%.*]]) addrspace(200) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[SHL:%.*]] = and i32 [[X]], 2147483647
; CHECK-NEXT:    ret i32 [[SHL]]
;
entry:
  %shl = and i32 %x, 2147483647
  ret i32 %shl
}

