; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc --filetype=asm --code-model=small --mcpu=cheriot --mtriple=riscv32-unknown-unknown -target-abi cheriot  %s -mattr=+xcheri,+xcheripurecap -verify-machineinstrs -o - | FileCheck %s
; ModuleID = 'ccall.c'
source_filename = "ccall.c"
target datalayout = "e-m:e-pf200:64:64:64:32-p:32:32-i64:64-n32-S128-A200-P200-G200"
target triple = "riscv32-unknown-unknown"

@testcall6.stack_arg = internal addrspace(200) global i32 0, align 4
@testcall8.stack_arg = internal addrspace(200) global i32 0, align 4

; Function Attrs: minsize mustprogress nofree norecurse nosync nounwind optsize readnone willreturn
define dso_local cheriot_compartmentcalleecc i32 @test2(i32 %a0, i32 %a1) local_unnamed_addr addrspace(200) #0 {
; Check that we have the first two arguments in the right registers.
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    ct.cret
entry:
  %add = add nsw i32 %a1, %a0
  ret i32 %add
}

; Function Attrs: minsize mustprogress nofree norecurse nosync nounwind optsize readonly willreturn
define dso_local cheriot_compartmentcalleecc i32 @test6(i32 addrspace(200)* nocapture readonly %a0, i32 addrspace(200)* nocapture readonly %a1, i32 addrspace(200)* nocapture readonly %a2, i32 addrspace(200)* nocapture readonly %a3, i32 addrspace(200)* nocapture readonly %a4, i32 addrspace(200)* nocapture readonly %a5) local_unnamed_addr addrspace(200) #1 {
; Check that we are loading the last register argument
; CHECK-LABEL: test6:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.clw a0, 0(a0)
; CHECK-NEXT:    ct.clw a1, 0(a1)
; CHECK-NEXT:    ct.clw a2, 0(a2)
; CHECK-NEXT:    ct.clw a3, 0(a3)
; CHECK-NEXT:    ct.clw a4, 0(a4)
; CHECK-NEXT:    ct.clw a5, 0(a5)
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    add a2, a2, a3
; CHECK-NEXT:    add a0, a0, a2
; CHECK-NEXT:    add a4, a4, a5
; CHECK-NEXT:    add a0, a0, a4
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i32, i32 addrspace(200)* %a0, align 4, !tbaa !5
  %1 = load i32, i32 addrspace(200)* %a1, align 4, !tbaa !5
  %add = add nsw i32 %1, %0
  %2 = load i32, i32 addrspace(200)* %a2, align 4, !tbaa !5
  %add1 = add nsw i32 %add, %2
  %3 = load i32, i32 addrspace(200)* %a3, align 4, !tbaa !5
  %add2 = add nsw i32 %add1, %3
  %4 = load i32, i32 addrspace(200)* %a4, align 4, !tbaa !5
  %add3 = add nsw i32 %add2, %4
  %5 = load i32, i32 addrspace(200)* %a5, align 4, !tbaa !5
  %add4 = add nsw i32 %add3, %5
  ret i32 %add4
}

; Function Attrs: minsize mustprogress nofree norecurse nosync nounwind optsize readonly willreturn
define dso_local cheriot_compartmentcalleecc i32 @test8(i32 addrspace(200)* nocapture readonly %a0, i32 addrspace(200)* nocapture readonly %a1, i32 addrspace(200)* nocapture readonly %a2, i32 addrspace(200)* nocapture readonly %a3, i32 addrspace(200)* nocapture readonly %a4, i32 addrspace(200)* nocapture readonly %a5, i32 addrspace(200)* nocapture readonly %a6, i32 addrspace(200)* nocapture readonly %a7) local_unnamed_addr addrspace(200) #1 {
; Check that the last argument (used in the multiply) is loaded from offset 8
; in the stack-argument capability.
; CHECK-LABEL: test8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cgetbase t2, t0
; CHECK-NEXT:    bne t0, t2, .LBB2_6
; CHECK-NEXT:    blt t0, sp, .LBB2_6
; CHECK-NEXT:    # %bb.1:
; CHECK-NEXT:    ct.cgetlen t1, t0
; CHECK-NEXT:    li t2, 16
; CHECK-NEXT:    blt t1, t2, .LBB2_6
; CHECK-NEXT:    # %bb.2:
; CHECK-NEXT:    ct.cgetperm t1, t0
; CHECK-NEXT:    li t2, 126
; CHECK-NEXT:    bne t1, t2, .LBB2_6
; CHECK-NEXT:    # %bb.3:
; CHECK-NEXT:    ct.cgettag      t1, t0
; CHECK-NEXT:    beqz    t1, .LBB2_6
; CHECK-NEXT:    # %bb.4:
; CHECK-NEXT:    ct.cgettype     t1, t0
; CHECK-NEXT:    bnez    t1, .LBB2_6
; CHECK-NEXT:    # %bb.5:
; CHECK-NEXT:    ct.clc t1, 8(t0)
; CHECK-NEXT:    ct.clc t0, 0(t0)
; CHECK-NEXT:    ct.clw a0, 0(a0)
; CHECK-NEXT:    ct.clw a1, 0(a1)
; CHECK-NEXT:    ct.clw a2, 0(a2)
; CHECK-NEXT:    ct.clw a3, 0(a3)
; CHECK-NEXT:    ct.clw a4, 0(a4)
; CHECK-NEXT:    ct.clw a5, 0(a5)
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    add a2, a2, a3
; CHECK-NEXT:    ct.clw a1, 0(t0)
; CHECK-NEXT:    add a0, a0, a2
; CHECK-NEXT:    ct.clw a2, 0(t1)
; CHECK-NEXT:    add a4, a4, a5
; CHECK-NEXT:    add a0, a0, a4
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    mul a0, a0, a2
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    ct.cret
; CHECK-NEXT:  .LBB2_6:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i32, i32 addrspace(200)* %a0, align 4, !tbaa !5
  %1 = load i32, i32 addrspace(200)* %a1, align 4, !tbaa !5
  %add = add nsw i32 %1, %0
  %2 = load i32, i32 addrspace(200)* %a2, align 4, !tbaa !5
  %add1 = add nsw i32 %add, %2
  %3 = load i32, i32 addrspace(200)* %a3, align 4, !tbaa !5
  %add2 = add nsw i32 %add1, %3
  %4 = load i32, i32 addrspace(200)* %a4, align 4, !tbaa !5
  %add3 = add nsw i32 %add2, %4
  %5 = load i32, i32 addrspace(200)* %a5, align 4, !tbaa !5
  %add4 = add nsw i32 %add3, %5
  %6 = load i32, i32 addrspace(200)* %a6, align 4, !tbaa !5
  %add5 = add nsw i32 %add4, %6
  %7 = load i32, i32 addrspace(200)* %a7, align 4, !tbaa !5
  %mul = mul nsw i32 %add5, %7
  ret i32 %mul
}

; Function Attrs: argmemonly mustprogress nofree nosync nounwind willreturn
declare void @llvm.lifetime.start.p200i8(i64 immarg, i8 addrspace(200)* nocapture) addrspace(200) #3

; Function Attrs: minsize optsize
declare dso_local cheriot_compartmentcallcc i32 @test6callee(i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*) local_unnamed_addr addrspace(200) #4

; Function Attrs: argmemonly mustprogress nofree nosync nounwind willreturn
declare void @llvm.lifetime.end.p200i8(i64 immarg, i8 addrspace(200)* nocapture) addrspace(200) #3

; Function Attrs: minsize nounwind optsize
define dso_local i32 @testcall8() local_unnamed_addr addrspace(200) #2 {
; CHECK-LABEL: testcall8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -64
; CHECK-NEXT:    ct.csc ra, 56(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.cincoffset a0, sp, 24
; CHECK-NEXT:    ct.csetbounds a0, a0, 32
; CHECK-NEXT:    ct.cincoffset a1, a0, 4
; CHECK-NEXT:    ct.cincoffset a2, a0, 8
; CHECK-NEXT:    ct.cincoffset a3, a0, 12
; CHECK-NEXT:    ct.cincoffset a4, a0, 16
; CHECK-NEXT:    ct.cincoffset a5, a0, 20
; CHECK-NEXT:    ct.cincoffset t1, a0, 24
; CHECK-NEXT:  .LBB3_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data t0, %cheriot_compartment_data_hi(testcall8.stack_arg)
; CHECK-NEXT:    ct.cincoffset t0, t0, %cheriot_compartment_lo_i(.LBB3_1)
; CHECK-NEXT:    ct.csetbounds t0, t0, %cheriot_compartment_size(testcall8.stack_arg)
; CHECK-NEXT:    ct.csc t0, 8(sp)
; CHECK-NEXT:    ct.csetbounds t0, sp, 16
; CHECK-NEXT:    ct.csc t1, 0(sp)
; CHECK-NEXT:  .LBB3_3: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t1, %cheriot_compartment_code_hi(__import_other_test8callee)
; CHECK-NEXT:    ct.clc t1, %cheriot_compartment_lo_i(.LBB3_3)(t1)
; CHECK-NEXT:  .LBB3_2: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(.compartment_switcher)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB3_2)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.clc ra, 56(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 64
; CHECK-NEXT:    ct.cret
entry:
  ; Check that we have the right relocations and stack layout.
  %args = alloca [8 x i32], align 4, addrspace(200)
  %0 = bitcast [8 x i32] addrspace(200)* %args to i8 addrspace(200)*
  call void @llvm.lifetime.start.p200i8(i64 32, i8 addrspace(200)* nonnull %0) #5
  %arrayidx = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 0
  %arrayidx1 = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 1
  %arrayidx2 = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 2
  %arrayidx3 = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 3
  %arrayidx4 = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 4
  %arrayidx5 = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 5
  %arrayidx6 = getelementptr inbounds [8 x i32], [8 x i32] addrspace(200)* %args, i32 0, i32 6
  %call = call cheriot_compartmentcallcc i32 @test8callee(i32 addrspace(200)* nonnull %arrayidx, i32 addrspace(200)* nonnull %arrayidx1, i32 addrspace(200)* nonnull %arrayidx2, i32 addrspace(200)* nonnull %arrayidx3, i32 addrspace(200)* nonnull %arrayidx4, i32 addrspace(200)* nonnull %arrayidx5, i32 addrspace(200)* nonnull %arrayidx6, i32 addrspace(200)* nonnull @testcall8.stack_arg) #6
  call void @llvm.lifetime.end.p200i8(i64 32, i8 addrspace(200)* nonnull %0) #5
  ret i32 %call
}

; Function Attrs: minsize optsize
declare dso_local cheriot_compartmentcallcc i32 @test8callee(i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*, i32 addrspace(200)*) local_unnamed_addr addrspace(200) #4

attributes #0 = { minsize mustprogress nofree norecurse nosync nounwind optsize readnone willreturn "cheri-compartment"="example" "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+xcheri,-64bit,-relax,-save-restore" }
attributes #1 = { minsize mustprogress nofree norecurse nosync nounwind optsize readonly willreturn "cheri-compartment"="example" "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+xcheri,-64bit,-relax,-save-restore" }
attributes #2 = { minsize nounwind optsize "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+xcheri,-64bit,-relax,-save-restore" }
attributes #3 = { argmemonly mustprogress nofree nosync nounwind willreturn }
attributes #4 = { minsize optsize "cheri-compartment"="other" "frame-pointer"="none" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+xcheri,-64bit,-relax,-save-restore,+xcheri-norvc" }
attributes #5 = { nounwind }
attributes #6 = { minsize nounwind optsize }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"cheriot"}
!2 = !{i32 1, !"Code Model", i32 1}
!3 = !{i32 1, !"SmallDataLimit", i32 8}
!4 = !{!"clang version 13.0.0 (git@ssh.dev.azure.com:v3/Portmeirion/CHERI-MCU/LLVM 510563e51e3d10ea94e5d2f31575f8cd00dc5857)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}

; Check that we have the right import and export tables.

; CHECK:        .section        .compartment_exports,"aR",@progbits
; CHECK:        .type   __export_example_test2,@object
; CHECK:        .globl  __export_example_test2
; CHECK:        .p2align        2
; CHECK:__export_example_test2:
; CHECK:        .half   test2-__compartment_pcc_start
; CHECK:        .byte   0
; CHECK:        .byte   2
; CHECK:        .size   __export_example_test2, 4
; CHECK:        .type   __export_example_test6,@object
; CHECK:        .globl  __export_example_test6
; CHECK:        .p2align        2
; CHECK:__export_example_test6:
; CHECK:        .half   test6-__compartment_pcc_start
; CHECK:        .byte   0
; CHECK:        .byte   6
; CHECK:        .size   __export_example_test6, 4
; CHECK:        .type   __export_example_test8,@object
; CHECK:        .globl  __export_example_test8
; CHECK:        .p2align        2
; CHECK:__export_example_test8:
; CHECK:        .half   test8-__compartment_pcc_start
; CHECK:        .byte   0
; CHECK:        .byte   7
; CHECK:        .size   __export_example_test8, 4
; CHECK:        .section        .compartment_imports.test8callee,"aG",@progbits,__import_other_test8callee,comdat
; CHECK:        .type   __import_other_test8callee,@object
; CHECK:        .weak  __import_other_test8callee
; CHECK:        .p2align        3
; CHECK:__import_other_test8callee:
; CHECK:        .word   __export_other_test8callee
; This is not a libcall, so it shouldn't have any add to set low bits in this
; pointer.
; CHECK-NOT: +
; CHECK:        .word   0
; CHECK:        .size   __import_other_test8callee, 8
