; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --filetype=asm --mcpu=cheriot --mtriple=riscv32-unknown-cheriotrtos -target-abi cheriot  %s -mattr=+xcheri,+xcheripurecap,+xcheriot -verify-machineinstrs -o - | FileCheck %s
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

@gv_u8 = external addrspace(200) global i8, align 1
@gv_s8 = external addrspace(200) global i8, align 1
@gv_u16 = external addrspace(200) global i16, align 2
@gv_s16 = external addrspace(200) global i16, align 2
@gv_u32 = external addrspace(200) global i32, align 4
@gv_s32 = external addrspace(200) global i32, align 4
@gv_u64 = external addrspace(200) global i64, align 8
@gv_s64 = external addrspace(200) global i64, align 8

@gv_cap = external addrspace(200) global ptr addrspace(200), align 8

@ig_s32 = internal addrspace(200) global i32 zeroinitializer, align 4

@cst_u8 = addrspace(200) constant i8 0, align 1
@cst_s8 = addrspace(200) constant i8 0, align 1
@cst_u16 = addrspace(200) constant i16 0, align 2
@cst_s16 = addrspace(200) constant i16 0, align 2
@cst_u32 = addrspace(200) constant i32 0, align 4
@cst_s32 = addrspace(200) constant i32 0, align 4
@cst_u64 = addrspace(200) constant i64 0, align 8
@cst_s64 = addrspace(200) constant i64 0, align 8

define i8 @load_u8() addrspace(200) {
; CHECK-LABEL: load_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB0_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc.data a0, %cheriot_compartment_data_hi(gv_u8)
; CHECK-NEXT:    clb a0, %cheriot_compartment_lo_i(.LBB0_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i8, ptr addrspace(200) @gv_u8, align 1
  ret i8 %0
}

define void @store_u8() addrspace(200) {
; CHECK-LABEL: store_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:  .LBB1_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_u8)
; CHECK-NEXT:    ct.csb a0, %cheriot_compartment_lo_s(.LBB1_1)(a1)
; CHECK-NEXT:    ct.cret
entry:
  store i8 3, ptr addrspace(200) @gv_u8, align 1
  ret void
}

define i8 @load_s8() addrspace(200) {
; CHECK-LABEL: load_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB2_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc.data a0, %cheriot_compartment_data_hi(gv_s8)
; CHECK-NEXT:    clb a0, %cheriot_compartment_lo_i(.LBB2_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i8, ptr addrspace(200) @gv_s8, align 1
  ret i8 %0
}

define void @store_s8() addrspace(200) {
; CHECK-LABEL: store_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:  .LBB3_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_s8)
; CHECK-NEXT:    ct.csb a0, %cheriot_compartment_lo_s(.LBB3_1)(a1)
; CHECK-NEXT:    ct.cret
entry:
  store i8 3, ptr addrspace(200) @gv_s8, align 1
  ret void
}

define i16 @load_u16() addrspace(200) {
; CHECK-LABEL: load_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB4_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc.data a0, %cheriot_compartment_data_hi(gv_u16)
; CHECK-NEXT:    clh a0, %cheriot_compartment_lo_i(.LBB4_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i16, ptr addrspace(200) @gv_u16, align 2
  ret i16 %0
}

define void @store_u16() addrspace(200) {
; CHECK-LABEL: store_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:  .LBB5_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_u16)
; CHECK-NEXT:    ct.csh a0, %cheriot_compartment_lo_s(.LBB5_1)(a1)
; CHECK-NEXT:    ct.cret
entry:
  store i16 3, ptr addrspace(200) @gv_u16, align 2
  ret void
}

define i16 @load_s16() addrspace(200) {
; CHECK-LABEL: load_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB6_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc.data a0, %cheriot_compartment_data_hi(gv_s16)
; CHECK-NEXT:    clh a0, %cheriot_compartment_lo_i(.LBB6_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i16, ptr addrspace(200) @gv_s16, align 2
  ret i16 %0
}

define void @store_s16() addrspace(200) {
; CHECK-LABEL: store_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:  .LBB7_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_s16)
; CHECK-NEXT:    ct.csh a0, %cheriot_compartment_lo_s(.LBB7_1)(a1)
; CHECK-NEXT:    ct.cret
entry:
  store i16 3, ptr addrspace(200) @gv_s16, align 2
  ret void
}

define i32 @load_u32() addrspace(200) {
; CHECK-LABEL: load_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB8_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc.data a0, %cheriot_compartment_data_hi(gv_u32)
; CHECK-NEXT:    clw a0, %cheriot_compartment_lo_i(.LBB8_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i32, ptr addrspace(200) @gv_u32, align 4
  ret i32 %0
}

define void @store_u32() addrspace(200) {
; CHECK-LABEL: store_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:  .LBB9_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_u32)
; CHECK-NEXT:    ct.csw a0, %cheriot_compartment_lo_s(.LBB9_1)(a1)
; CHECK-NEXT:    ct.cret
entry:
  store i32 3, ptr addrspace(200) @gv_u32, align 4
  ret void
}

define i32 @load_s32() addrspace(200) {
; CHECK-LABEL: load_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB10_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    auipcc.data a0, %cheriot_compartment_data_hi(gv_s32)
; CHECK-NEXT:    clw a0, %cheriot_compartment_lo_i(.LBB10_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i32, ptr addrspace(200) @gv_s32, align 4
  ret i32 %0
}

define void @store_s32() addrspace(200) {
; CHECK-LABEL: store_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    li a0, 3
; CHECK-NEXT:  .LBB11_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_s32)
; CHECK-NEXT:    ct.csw a0, %cheriot_compartment_lo_s(.LBB11_1)(a1)
; CHECK-NEXT:    ct.cret
entry:
  store i32 3, ptr addrspace(200) @gv_s32, align 4
  ret void
}

define i64 @load_u64() addrspace(200) {
; CHECK-LABEL: load_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB12_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_u64)
; CHECK-NEXT:    ct.cincoffset a1, a1, %cheriot_compartment_lo_i(.LBB12_1)
; CHECK-NEXT:    ct.csetbounds a1, a1, %cheriot_compartment_size(gv_u64)
; CHECK-NEXT:    ct.clw a0, 0(a1)
; CHECK-NEXT:    ct.clw a1, 4(a1)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i64, ptr addrspace(200) @gv_u64, align 8
  ret i64 %0
}

define void @store_u64() addrspace(200) {
; CHECK-LABEL: store_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB13_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a0, %cheriot_compartment_data_hi(gv_u64)
; CHECK-NEXT:    ct.cincoffset a0, a0, %cheriot_compartment_lo_i(.LBB13_1)
; CHECK-NEXT:    ct.csetbounds a0, a0, %cheriot_compartment_size(gv_u64)
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    ct.csw zero, 4(a0)
; CHECK-NEXT:    ct.csw a1, 0(a0)
; CHECK-NEXT:    ct.cret
entry:
  store i64 3, ptr addrspace(200) @gv_u64, align 8
  ret void
}

define i64 @load_s64() addrspace(200) {
; CHECK-LABEL: load_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB14_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a1, %cheriot_compartment_data_hi(gv_s64)
; CHECK-NEXT:    ct.cincoffset a1, a1, %cheriot_compartment_lo_i(.LBB14_1)
; CHECK-NEXT:    ct.csetbounds a1, a1, %cheriot_compartment_size(gv_s64)
; CHECK-NEXT:    ct.clw a0, 0(a1)
; CHECK-NEXT:    ct.clw a1, 4(a1)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load i64, ptr addrspace(200) @gv_s64, align 8
  ret i64 %0
}

define void @store_s64() addrspace(200) {
; CHECK-LABEL: store_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB15_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a0, %cheriot_compartment_data_hi(gv_s64)
; CHECK-NEXT:    ct.cincoffset a0, a0, %cheriot_compartment_lo_i(.LBB15_1)
; CHECK-NEXT:    ct.csetbounds a0, a0, %cheriot_compartment_size(gv_s64)
; CHECK-NEXT:    li a1, 3
; CHECK-NEXT:    ct.csw zero, 4(a0)
; CHECK-NEXT:    ct.csw a1, 0(a0)
; CHECK-NEXT:    ct.cret
entry:
  store i64 3, ptr addrspace(200) @gv_s64, align 8
  ret void
}

define ptr addrspace(200) @load_cap() addrspace(200) {
; CHECK-LABEL: load_cap:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB16_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a0, %cheriot_compartment_data_hi(gv_cap)
; CHECK-NEXT:    ct.clc a0, %cheriot_compartment_lo_i(.LBB16_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load ptr addrspace(200), ptr addrspace(200) @gv_cap, align 8
  ret ptr addrspace(200) %0
}

define void @store_cap() addrspace(200) {
; CHECK-LABEL: store_cap:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB17_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a0, %cheriot_compartment_data_hi(gv_cap)
; CHECK-NEXT:    ct.csc zero, %cheriot_compartment_lo_s(.LBB17_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  store ptr addrspace(200) null, ptr addrspace(200) @gv_cap, align 8
  ret void
}

define i8 @load_cst_u8() addrspace(200) {
; CHECK-LABEL: load_cst_u8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB18_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_u8)
; CHECK-NEXT:    ct.clb a0, %cheriot_compartment_lo_i(.LBB18_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i8, ptr addrspace(200) @cst_u8, align 1
  ret i8 %0
}

define i8 @load_cst_s8() addrspace(200) {
; CHECK-LABEL: load_cst_s8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB19_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_s8)
; CHECK-NEXT:    ct.clb a0, %cheriot_compartment_lo_i(.LBB19_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i8, ptr addrspace(200) @cst_s8, align 1
  ret i8 %0
}

define i16 @load_cst_u16() addrspace(200) {
; CHECK-LABEL: load_cst_u16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB20_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_u16)
; CHECK-NEXT:    ct.clh a0, %cheriot_compartment_lo_i(.LBB20_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i16, ptr addrspace(200) @cst_u16, align 2
  ret i16 %0
}

define i16 @load_cst_s16() addrspace(200) {
; CHECK-LABEL: load_cst_s16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB21_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_s16)
; CHECK-NEXT:    ct.clh a0, %cheriot_compartment_lo_i(.LBB21_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i16, ptr addrspace(200) @cst_s16, align 2
  ret i16 %0
}

define i32 @load_cst_u32() addrspace(200) {
; CHECK-LABEL: load_cst_u32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB22_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_u32)
; CHECK-NEXT:    ct.clw a0, %cheriot_compartment_lo_i(.LBB22_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i32, ptr addrspace(200) @cst_u32, align 4
  ret i32 %0
}

define i32 @load_cst_s32() addrspace(200) {
; CHECK-LABEL: load_cst_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB23_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_s32)
; CHECK-NEXT:    ct.clw a0, %cheriot_compartment_lo_i(.LBB23_1)(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i32, ptr addrspace(200) @cst_s32, align 4
  ret i32 %0
}

define i64 @load_cst_u64() addrspace(200) {
; CHECK-LABEL: load_cst_u64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB24_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_u64)
; CHECK-NEXT:    ct.cincoffset a0, a0, %cheriot_compartment_lo_i(.LBB24_1)
; CHECK-NEXT:    ct.clw a1, 4(a0)
; CHECK-NEXT:    ct.clw a0, 0(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i64, ptr addrspace(200) @cst_u64, align 8
  ret i64 %0
}

define i64 @load_cst_s64() addrspace(200) {
; CHECK-LABEL: load_cst_s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB25_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc a0, %cheriot_compartment_code_hi(cst_s64)
; CHECK-NEXT:    ct.cincoffset a0, a0, %cheriot_compartment_lo_i(.LBB25_1)
; CHECK-NEXT:    ct.clw a1, 4(a0)
; CHECK-NEXT:    ct.clw a0, 0(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load volatile i64, ptr addrspace(200) @cst_s64, align 8
  ret i64 %0
}

define ptr addrspace(200) @redundant_csetbounds() addrspace(200) {
; CHECK-LABEL: redundant_csetbounds:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB26_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc.data a0, %cheriot_compartment_data_hi(ig_s32)
; CHECK-NEXT:    ct.cincoffset a0, a0, %cheriot_compartment_lo_i(.LBB26_1)
; CHECK-NEXT:    ct.csetbounds a0, a0, 4
; CHECK-NEXT:    ct.cret
entry:
  %0 = tail call fastcc addrspace(200) ptr addrspace(200) @llvm.cheri.cap.bounds.set.i32(ptr addrspace(200) @ig_s32, i32 4)
  ret ptr addrspace(200) %0
}
