; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --filetype=asm --mcpu=cheriot --mtriple=riscv32-unknown-unknown -target-abi cheriot  %s -mattr=+xcheri,+xcheripurecap,+xcheriot -o - | FileCheck %s
target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

%struct.Node = type { [8192 x i8] }

define cheriot_compartmentcalleecc void @test(ptr addrspace(200) sret(%struct.Node) %agg.result) addrspace(200) #0 {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cgetbase t2, a0
; CHECK-NEXT:    bne a0, t2, .LBB0_6
; CHECK-NEXT:    blt a0, sp, .LBB0_6
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    ct.cgetlen t1, a0
; CHECK-NEXT:    lui t2, 2
; CHECK-NEXT:    blt t1, t2, .LBB0_6
; CHECK-NEXT:  # %bb.2: # %entry
; CHECK-NEXT:    ct.cgetperm t1, a0
; CHECK-NEXT:    li t2, 126
; CHECK-NEXT:    bne t1, t2, .LBB0_6
; CHECK-NEXT:  # %bb.3: # %entry
; CHECK-NEXT:    ct.cgettag t1, a0
; CHECK-NEXT:    beqz t1, .LBB0_6
; CHECK-NEXT:  # %bb.4: # %entry
; CHECK-NEXT:    ct.cgettype t1, a0
; CHECK-NEXT:    bnez t1, .LBB0_6
; CHECK-NEXT:  # %bb.5: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    lui a2, 2
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:  .LBB0_7: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_memset)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB0_7)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    ct.cret
entry:
  tail call addrspace(200) void @llvm.memset.p200.i64(ptr addrspace(200) noundef nonnull align 1 dereferenceable(8192) %agg.result, i8 0, i64 8192, i1 false)
  ret void
}

; Function Attrs: mustprogress nocallback nofree nounwind willreturn memory(argmem: write)
declare void @llvm.memset.p200.i64(ptr addrspace(200) writeonly captures(none), i8, i64, i1 immarg) addrspace(200) #1

attributes #0 = { minsize mustprogress nofree norecurse nosync nounwind optsize willreturn memory(argmem: write) "cheri-compartment"="test_runner" "interrupt-state"="enabled" "no-builtin-longjmp" "no-builtin-printf" "no-builtin-setjmp" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+32bit,+c,+e,+m,+relax,+unaligned-scalar-mem,+xcheri,+xcheriot,+xcheripurecap,+zca,+zmmul,-a,-b,-d,-experimental-p,-experimental-smpmpmt,-experimental-svukte,-experimental-xrivosvisni,-experimental-xrivosvizip,-experimental-xsfmclic,-experimental-xsfsclic,-experimental-zibi,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvfbfa,-experimental-zvfofp8min,-experimental-zvkgs,-experimental-zvqdotq,-f,-h,-i,-q,-sdext,-sdtrig,-sha,-shcounterenw,-shgatpa,-shlcofideleg,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcntrpmf,-smcsrind,-smctr,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssctr,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xandesbfhcvt,-xandesperf,-xandesvbfhcvt,-xandesvdot,-xandesvpackfph,-xandesvsinth,-xandesvsintload,-xcheri-norvc,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscbop,-xmipscmov,-xmipsexectl,-xmipslsp,-xqccmp,-xqci,-xqcia,-xqciac,-xqcibi,-xqcibm,-xqcicli,-xqcicm,-xqcics,-xqcicsr,-xqciint,-xqciio,-xqcilb,-xqcili,-xqcilia,-xqcilo,-xqcilsm,-xqcisim,-xqcisls,-xqcisync,-xsfcease,-xsfmm128t,-xsfmm16t,-xsfmm32a16f,-xsfmm32a32f,-xsfmm32a8f,-xsfmm32a8i,-xsfmm32t,-xsfmm64a64f,-xsfmm64t,-xsfmmbase,-xsfvcp,-xsfvfbfexp16e,-xsfvfexp16e,-xsfvfexp32e,-xsfvfexpa,-xsfvfexpa64e,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xsmtvdot,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalasr,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zcb,-zcd,-zce,-zcf,-zclsd,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccamoc,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zilsd,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #1 = { mustprogress nocallback nofree nounwind willreturn memory(argmem: write) }

!llvm.module.flags = !{!0, !1, !2, !4, !5}
!llvm.ident = !{!6}
!llvm.errno.tbaa = !{!7}

!0 = !{i32 1, !"wchar_size", i32 2}
!1 = !{i32 1, !"target-abi", !"cheriot"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv32e2p0_m2p0_c2p0_zmmul1p0_zca1p0_xcheri0p0_xcheriot1p0_xcheripurecap0p0"}
!4 = !{i32 1, !"cheriot-compartment", !"test_runner"}
!5 = !{i32 8, !"SmallDataLimit", i32 0}
!6 = !{!"clang version 22.1.7 (git@github.com:resistor/llvm-project-1.git 3657a8a9a2d7fd4e9b81cd62a1054beb794c82bf)"}
!7 = !{!8, !8, i64 0}
!8 = !{!"int", !9, i64 0}
!9 = !{!"omnipotent char", !10, i64 0}
!10 = !{!"Simple C++ TBAA"}
