; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -o - %s -mcpu=cheriot --mtriple=riscv32-unknown-cheriotrtos -target-abi cheriot -mattr=+xcheri,+xcheriot,+xcheripurecap | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

%struct.TwoDoubles = type { double, double }

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test01d(double noundef returned %a) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test01d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cret
entry:
  ret double %a
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test02dd(double noundef %a, double noundef returned %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test02dd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cmove a0, a1
; CHECK-NEXT:    ct.cret
entry:
  ret double %b
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local noundef double @_Z6test03Pd(ptr addrspace(200) nocapture noundef readonly %a) local_unnamed_addr addrspace(200) #1 {
; CHECK-LABEL: _Z6test03Pd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.clc a0, 0(a0)
; CHECK-NEXT:    ct.cret
entry:
  %0 = load double, ptr addrspace(200) %a, align 8, !tbaa !6
  ret double %0
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test04v() local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test04v:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a0, 261888
; CHECK-NEXT:    ct.csethigh a0, zero, a0
; CHECK-NEXT:    ct.cret
entry:
  ret double 1.000000e+00
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test05d(double noundef %a) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test05d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a1, 261888
; CHECK-NEXT:    ct.csethigh a1, zero, a1
; CHECK-NEXT:  .LBB4_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB4_1)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %add = fadd double %a, 1.000000e+00
  ret double %add
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test06d(double noundef %a) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test06d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cmove a1, zero
; CHECK-NEXT:  .LBB5_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB5_1)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %add = fadd double %a, 0.000000e+00
  ret double %add
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test07dd(double noundef %a, double noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test07dd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cmove a1, zero
; CHECK-NEXT:  .LBB6_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB6_1)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %add = fadd double %a, 0.000000e+00
  ret double %add
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write)
define dso_local void @_Z6test08dPd(double noundef %a, ptr addrspace(200) nocapture noundef writeonly initializes((0, 8)) %b) local_unnamed_addr addrspace(200) #2 {
; CHECK-LABEL: _Z6test08dPd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.cmove s0, a1
; CHECK-NEXT:    lui a1, 261888
; CHECK-NEXT:    ct.csethigh a1, zero, a1
; CHECK-NEXT:  .LBB7_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB7_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 0(s0)
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
entry:
  %add = fadd double %a, 1.000000e+00
  store double %add, ptr addrspace(200) %b, align 8, !tbaa !6
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write)
define dso_local void @_Z6test09dPd(double noundef %a, ptr addrspace(200) nocapture noundef writeonly initializes((8, 16)) %b) local_unnamed_addr addrspace(200) #2 {
; CHECK-LABEL: _Z6test09dPd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.csc a0, 8(a1)
; CHECK-NEXT:    ct.cret
entry:
  %arrayidx = getelementptr inbounds nuw i8, ptr addrspace(200) %b, i32 8
  store double %a, ptr addrspace(200) %arrayidx, align 8, !tbaa !6
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test10dd(double noundef %a, double noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test10dd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB9_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___subdf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB9_1)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %sub = fsub double %a, %b
  ret double %sub
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test11dd(double noundef %a, double noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test11dd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB10_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___muldf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB10_1)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %mul = fmul double %a, %b
  ret double %mul
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test12dd(double noundef %a, double noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test12dd:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:  .LBB11_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___divdf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB11_1)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %div = fdiv double %a, %b
  ret double %div
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read)
define dso_local noundef double @_Z6test1310TwoDoubles(ptr addrspace(200) nocapture noundef readonly %in) local_unnamed_addr addrspace(200) #1 {
; CHECK-LABEL: _Z6test1310TwoDoubles:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.clc s0, 0(a0)
; CHECK-NEXT:    ct.clc a0, 8(a0)
; CHECK-NEXT:    ct.cmove a1, a0
; CHECK-NEXT:  .LBB12_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB12_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove a1, s0
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:  .LBB12_2: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB12_2)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %0 = load double, ptr addrspace(200) %in, align 8, !tbaa !10
  %b = getelementptr inbounds nuw i8, ptr addrspace(200) %in, i32 8
  %1 = load double, ptr addrspace(200) %b, align 8, !tbaa !12
  %2 = tail call addrspace(200) double @llvm.fmuladd.f64(double %1, double 2.000000e+00, double %0)
  ret double %2
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.fmuladd.f64(double, double, double) addrspace(200) #3

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write)
define dso_local void @_Z6test13d(ptr addrspace(200) dead_on_unwind noalias nocapture writable writeonly sret(%struct.TwoDoubles) align 8 initializes((0, 16)) %agg.result, double noundef %a) local_unnamed_addr addrspace(200) #2 {
; CHECK-LABEL: _Z6test13d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.csc a1, 0(a0)
; CHECK-NEXT:    lui a1, 262272
; CHECK-NEXT:    ct.csw a1, 12(a0)
; CHECK-NEXT:    ct.csw zero, 8(a0)
; CHECK-NEXT:    ct.cret
entry:
  store double %a, ptr addrspace(200) %agg.result, align 8, !tbaa !10
  %b = getelementptr inbounds nuw i8, ptr addrspace(200) %agg.result, i32 8
  store double 3.000000e+00, ptr addrspace(200) %b, align 8, !tbaa !12
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write)
define dso_local void @_Z6test14d(ptr addrspace(200) dead_on_unwind noalias nocapture writable writeonly sret(%struct.TwoDoubles) align 8 initializes((0, 16)) %agg.result, double noundef %a) local_unnamed_addr addrspace(200) #2 {
; CHECK-LABEL: _Z6test14d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    lui a2, 262464
; CHECK-NEXT:    ct.csw zero, 0(a0)
; CHECK-NEXT:    ct.csw a2, 4(a0)
; CHECK-NEXT:    ct.csc a1, 8(a0)
; CHECK-NEXT:    ct.cret
entry:
  store double 5.000000e+00, ptr addrspace(200) %agg.result, align 8, !tbaa !10
  %b = getelementptr inbounds nuw i8, ptr addrspace(200) %agg.result, i32 8
  store double %a, ptr addrspace(200) %b, align 8, !tbaa !12
  ret void
}

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define dso_local noundef double @_Z6test15(i32 noundef %a) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z6test15:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:  .LBB15_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___floatunsidf)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB15_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
entry:
  %b = uitofp i32 %a to double
  ret double %b
}

; Function Attrs: nounwind uwtable
define dso_local noundef double @float2double(float noundef %x) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: float2double:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:  .LBB16_1: # %start
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___extendsfdf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB16_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
start:
  %a = fpext float %x to double
  ret double %a
}

define dso_local noundef float @double2float(double noundef %x) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: double2float:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:  .LBB17_1: # %start
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___truncdfsf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB17_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
start:
  %a = fptrunc double %x to float
  ret float %a
}

define dso_local noundef double @select_on_int(double noundef %x, double noundef %y, i64 noundef %z) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: select_on_int:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    srli s0, a3, 31
; CHECK-NEXT:  .LBB18_4: # %start
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___ltdf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB18_4)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    srli a0, a0, 31
; CHECK-NEXT:    bne s0, a0, .LBB18_2
; CHECK-NEXT:  # %bb.1: # %start
; CHECK-NEXT:    ct.cmove a0, zero
; CHECK-NEXT:    j .LBB18_3
; CHECK-NEXT:  .LBB18_2:
; CHECK-NEXT:    lui a0, 261888
; CHECK-NEXT:    ct.csethigh a0, zero, a0
; CHECK-NEXT:  .LBB18_3: # %start
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
start:
  %a = icmp slt i64 %z, 0
  %b = fcmp olt double %x, %y
  %0 = xor i1 %a, %b
  %c = select i1 %0, double 1.0, double 0.0
  ret double %c
}

define dso_local void @trunc_store(ptr addrspace(200) noundef writeonly captures(none) initializes((0, 4)) %a, double noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: trunc_store:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    ct.cmove a0, a1
; CHECK-NEXT:  .LBB19_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___truncdfsf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB19_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csw a0, 0(s0)
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
entry:
  %conv = fptrunc double %b to float
  store float %conv, ptr addrspace(200) %a, align 4, !tbaa !6
  ret void
}

define dso_local void @ext_store(ptr addrspace(200) noundef writeonly captures(none) initializes((0, 8)) %a, float noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: ext_store:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:  .LBB20_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___extendsfdf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB20_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 0(s0)
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
entry:
  %conv = fpext float %b to double
  store double %conv, ptr addrspace(200) %a, align 8, !tbaa !10
  ret void
}

define dso_local void @load_ext_store(ptr addrspace(200) noundef writeonly captures(none) initializes((0, 8)) %a, ptr addrspace(200) noundef readonly captures(none) %b) local_unnamed_addr addrspace(200) #1 {
; CHECK-LABEL: load_ext_store:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.clw a1, 0(a1)
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    mv a0, a1
; CHECK-NEXT:  .LBB21_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___extendsfdf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB21_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 0(s0)
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
entry:
  %0 = load float, ptr addrspace(200) %b, align 4, !tbaa !6
  %conv = fpext float %0 to double
  store double %conv, ptr addrspace(200) %a, align 8, !tbaa !10
  ret void
}

define dso_local void @load_trunc_store(ptr addrspace(200) noundef readonly captures(none) %a, ptr addrspace(200) noundef writeonly captures(none) initializes((0, 4)) %b) local_unnamed_addr addrspace(200) #1 {
; CHECK-LABEL: load_trunc_store:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -16
; CHECK-NEXT:    ct.csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 0(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.clc a0, 0(a0)
; CHECK-NEXT:    ct.cmove s0, a1
; CHECK-NEXT:  .LBB22_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___truncdfsf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB22_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csw a0, 0(s0)
; CHECK-NEXT:    ct.clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 0(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 16
; CHECK-NEXT:    ct.cret
entry:
  %0 = load double, ptr addrspace(200) %a, align 8, !tbaa !10
  %conv = fptrunc double %0 to float
  store float %conv, ptr addrspace(200) %b, align 4, !tbaa !6
  ret void
}

define dso_local noundef double @test_frem(double noundef %a, double noundef %b) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: test_frem:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    ct.cincoffset sp, sp, -32
; CHECK-NEXT:    ct.csc ra, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s1, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.cmove s0, a1
; CHECK-NEXT:    ct.cmove s1, a0
; CHECK-NEXT:  .LBB23_1: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___divdf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB23_1)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:  .LBB23_2: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_trunc)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB23_2)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 0(sp)
; CHECK-NEXT:    ct.clb a0, 7(sp)
; CHECK-NEXT:    xori a0, a0, 128
; CHECK-NEXT:    ct.csb a0, 7(sp)
; CHECK-NEXT:    ct.clc a0, 0(sp)
; CHECK-NEXT:    ct.cmove a1, s0
; CHECK-NEXT:    ct.cmove a2, s1
; CHECK-NEXT:    ct.clc ra, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s1, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cincoffset sp, sp, 32
; CHECK-NEXT:  .LBB23_3: # %entry
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_fma)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB23_3)(t2)
; CHECK-NEXT:    ct.cjr t2
entry:
  %fmod = frem fast double %a, %b
  ret double %fmod
}

define double @test_frem_cst() addrspace(200) {
; CHECK-LABEL: test_frem_cst:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:    j .LBB24_6
; CHECK-NEXT:  # %bb.1: # %frem.compute
; CHECK-NEXT:    ct.cincoffset sp, sp, -96
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    ct.csc ra, 88(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s0, 80(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.csc s1, 72(sp) # 8-byte Folded Spill
; CHECK-NEXT:    .cfi_offset ra, -8
; CHECK-NEXT:    .cfi_offset s0, -16
; CHECK-NEXT:    .cfi_offset s1, -24
; CHECK-NEXT:    ct.cincoffset a1, sp, 64
; CHECK-NEXT:    ct.cmove a0, zero
; CHECK-NEXT:  .LBB24_10: # %frem.compute
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_frexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_10)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.clw a1, 64(sp)
; CHECK-NEXT:    ct.csw a1, 36(sp) # 4-byte Folded Spill
; CHECK-NEXT:    li a1, 26
; CHECK-NEXT:  .LBB24_11: # %frem.compute
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_ldexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_11)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    ct.cincoffset a1, sp, 68
; CHECK-NEXT:    ct.cmove a0, zero
; CHECK-NEXT:  .LBB24_12: # %frem.compute
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_frexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_12)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.clw a1, 68(sp)
; CHECK-NEXT:    addi s1, a1, -1
; CHECK-NEXT:    li a1, 1
; CHECK-NEXT:  .LBB24_13: # %frem.compute
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_ldexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_13)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove a1, a0
; CHECK-NEXT:    ct.csw s1, 4(sp) # 4-byte Folded Spill
; CHECK-NEXT:    not a0, s1
; CHECK-NEXT:    ct.clw s1, 36(sp) # 4-byte Folded Reload
; CHECK-NEXT:    add s1, s1, a0
; CHECK-NEXT:    lui a0, 261888
; CHECK-NEXT:    ct.csethigh a0, zero, a0
; CHECK-NEXT:    ct.csc a1, 24(sp) # 8-byte Folded Spill
; CHECK-NEXT:  .LBB24_14: # %frem.compute
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___divdf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_14)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 16(sp) # 8-byte Folded Spill
; CHECK-NEXT:    li a0, 26
; CHECK-NEXT:    blt a0, s1, .LBB24_8
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    ct.csc s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    mv a1, s1
; CHECK-NEXT:  .LBB24_3: # %frem.loop_exit
; CHECK-NEXT:    addi a1, a1, -25
; CHECK-NEXT:    ct.clc a0, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:  .LBB24_15: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_ldexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_15)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    ct.clc a1, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:  .LBB24_16: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___muldf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_16)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:  .LBB24_17: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_rint)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_17)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 40(sp)
; CHECK-NEXT:    ct.clb a0, 47(sp)
; CHECK-NEXT:    xori a0, a0, 128
; CHECK-NEXT:    ct.csb a0, 47(sp)
; CHECK-NEXT:    ct.clc a0, 40(sp)
; CHECK-NEXT:    ct.clc s1, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cmove a1, s1
; CHECK-NEXT:    ct.cmove a2, s0
; CHECK-NEXT:  .LBB24_18: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_fma)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_18)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    ct.cmove a1, s1
; CHECK-NEXT:  .LBB24_19: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_19)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s1, a0
; CHECK-NEXT:    ct.cmove a0, s0
; CHECK-NEXT:    ct.cmove a1, zero
; CHECK-NEXT:  .LBB24_20: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___ltdf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_20)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    bltz a0, .LBB24_5
; CHECK-NEXT:  # %bb.4: # %frem.loop_exit
; CHECK-NEXT:    ct.cmove s1, s0
; CHECK-NEXT:  .LBB24_5: # %frem.loop_exit
; CHECK-NEXT:    ct.cmove a0, s1
; CHECK-NEXT:    ct.clw a1, 4(sp) # 4-byte Folded Reload
; CHECK-NEXT:  .LBB24_21: # %frem.loop_exit
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_ldexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_21)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 48(sp)
; CHECK-NEXT:    ct.clbu a0, 55(sp)
; CHECK-NEXT:    andi a0, a0, 127
; CHECK-NEXT:    ct.csb a0, 55(sp)
; CHECK-NEXT:    ct.clc ra, 88(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s0, 80(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.clc s1, 72(sp) # 8-byte Folded Reload
; CHECK-NEXT:    .cfi_restore ra
; CHECK-NEXT:    .cfi_restore s0
; CHECK-NEXT:    .cfi_restore s1
; CHECK-NEXT:    ct.cincoffset sp, sp, 96
; CHECK-NEXT:    .cfi_def_cfa_offset 0
; CHECK-NEXT:  .LBB24_6:
; CHECK-NEXT:    lui a0, 524160
; CHECK-NEXT:    ct.csethigh a0, zero, a0
; CHECK-NEXT:    ct.cret
; CHECK-NEXT:  .LBB24_7: # %frem.loop_body
; CHECK-NEXT:    li a1, 26
; CHECK-NEXT:    ct.cmove a0, s1
; CHECK-NEXT:  .LBB24_22: # %frem.loop_body
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_ldexp)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_22)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    ct.clw a1, 36(sp) # 4-byte Folded Reload
; CHECK-NEXT:    addi s1, a1, -26
; CHECK-NEXT:    li a0, 26
; CHECK-NEXT:    bge a0, a1, .LBB24_3
; CHECK-NEXT:  .LBB24_8: # %frem.loop_body
; CHECK-NEXT:    ct.csw s1, 36(sp) # 4-byte Folded Spill
; CHECK-NEXT:    ct.cmove a0, s0
; CHECK-NEXT:    ct.clc a1, 16(sp) # 8-byte Folded Reload
; CHECK-NEXT:  .LBB24_23: # %frem.loop_body
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___muldf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_23)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:  .LBB24_24: # %frem.loop_body
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_rint)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_24)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.csc a0, 56(sp)
; CHECK-NEXT:    ct.clb a0, 63(sp)
; CHECK-NEXT:    xori a0, a0, 128
; CHECK-NEXT:    ct.csb a0, 63(sp)
; CHECK-NEXT:    ct.clc a0, 56(sp)
; CHECK-NEXT:    ct.clc s1, 24(sp) # 8-byte Folded Reload
; CHECK-NEXT:    ct.cmove a1, s1
; CHECK-NEXT:    ct.csc s0, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:    ct.cmove a2, s0
; CHECK-NEXT:  .LBB24_25: # %frem.loop_body
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls_fma)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_25)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s0, a0
; CHECK-NEXT:    ct.cmove a1, s1
; CHECK-NEXT:  .LBB24_26: # %frem.loop_body
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___adddf3)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_26)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    ct.cmove s1, a0
; CHECK-NEXT:    ct.cmove a0, s0
; CHECK-NEXT:    ct.cmove a1, zero
; CHECK-NEXT:  .LBB24_27: # %frem.loop_body
; CHECK-NEXT:    # Label of block must be emitted
; CHECK-NEXT:    ct.auipcc t2, %cheriot_compartment_code_hi(__library_import_libcalls___ltdf2)
; CHECK-NEXT:    ct.clc t2, %cheriot_compartment_lo_i(.LBB24_27)(t2)
; CHECK-NEXT:    ct.cjalr t2
; CHECK-NEXT:    bltz a0, .LBB24_7
; CHECK-NEXT:  # %bb.9: # %frem.loop_body
; CHECK-NEXT:    ct.cmove s1, s0
; CHECK-NEXT:    j .LBB24_7
start:
  %r = frem double 0.000000e+00, 0.000000e+00
  ret double %r
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) "cheri-compartment"="qoi_decode" "no-builtin-longjmp" "no-builtin-printf" "no-builtin-setjmp" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+32bit,+c,+e,+m,+relax,+unaligned-scalar-mem,+xcheri,+xcheriot,+zmmul,-a,-b,-d,-experimental-sdext,-experimental-sdtrig,-experimental-smctr,-experimental-ssctr,-experimental-svukte,-experimental-xqcia,-experimental-xqciac,-experimental-xqcicli,-experimental-xqcicm,-experimental-xqcics,-experimental-xqcicsr,-experimental-xqciint,-experimental-xqcilo,-experimental-xqcilsm,-experimental-xqcisls,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-f,-h,-i,-sha,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xcheri-norvc,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscmove,-xmipslsp,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #1 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: read) "cheri-compartment"="qoi_decode" "no-builtin-longjmp" "no-builtin-printf" "no-builtin-setjmp" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+32bit,+c,+e,+m,+relax,+unaligned-scalar-mem,+xcheri,+xcheriot,+zmmul,-a,-b,-d,-experimental-sdext,-experimental-sdtrig,-experimental-smctr,-experimental-ssctr,-experimental-svukte,-experimental-xqcia,-experimental-xqciac,-experimental-xqcicli,-experimental-xqcicm,-experimental-xqcics,-experimental-xqcicsr,-experimental-xqciint,-experimental-xqcilo,-experimental-xqcilsm,-experimental-xqcisls,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-f,-h,-i,-sha,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xcheri-norvc,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscmove,-xmipslsp,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #2 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: write) "cheri-compartment"="qoi_decode" "no-builtin-longjmp" "no-builtin-printf" "no-builtin-setjmp" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+32bit,+c,+e,+m,+relax,+unaligned-scalar-mem,+xcheri,+xcheriot,+zmmul,-a,-b,-d,-experimental-sdext,-experimental-sdtrig,-experimental-smctr,-experimental-ssctr,-experimental-svukte,-experimental-xqcia,-experimental-xqciac,-experimental-xqcicli,-experimental-xqcicm,-experimental-xqcics,-experimental-xqcicsr,-experimental-xqciint,-experimental-xqcilo,-experimental-xqcilsm,-experimental-xqcisls,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-experimental-zvbc32e,-experimental-zvkgs,-f,-h,-i,-sha,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smdbltrp,-smepmp,-smmpm,-smnpm,-smrnmi,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssdbltrp,-ssnpm,-sspm,-ssqosid,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-supm,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-svvptc,-v,-xcheri-norvc,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xmipscmove,-xmipslsp,-xsfcease,-xsfvcp,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xsifivecdiscarddlone,-xsifivecflushdlone,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zacas,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zicsr,-zifencei,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-ztso,-zvbb,-zvbc,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #3 = { mustprogress nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 2}
!1 = !{i32 1, !"target-abi", !"cheriot"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv32e2p0_m2p0_c2p0_zmmul1p0_xcheri0p0_xcheriot1p0"}
!4 = !{i32 8, !"SmallDataLimit", i32 0}
!5 = !{!"clang version 20.1.3 (git@github.com:resistor/llvm-project-1.git 5d99e3d52791d33f0f90e0e0d91152433e1cfba3)"}
!6 = !{!7, !7, i64 0}
!7 = !{!"double", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C++ TBAA"}
!10 = !{!11, !7, i64 0}
!11 = !{!"_ZTS10TwoDoubles", !7, i64 0, !7, i64 8}
!12 = !{!11, !7, i64 8}
