; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 --mcpu=cheriot -target-abi=cheriot -mattr=+xcheri,+xcheripurecap,+xcheriot -o - %s | FileCheck %s

target datalayout = "e-m:e-p:32:32-i64:64-n32-S128-pf200:64:64:64:32-A200-P200-G200"
target triple = "riscv32-unknown-cheriotrtos"

; Previously crashed due to SelectionDAG type legalization error on the PTRTOINT

define i64 @ptrtoint_i64() addrspace(200) {
; CHECK-LABEL: ptrtoint_i64:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    ct.cret
start:
  %int = ptrtoint ptr addrspace(200) null to i64
  ret i64 %int
}
