; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32cheriot --mcpu=cheriot -target-abi=cheriot -mattr=+xcheri,+xcheripurecap,+xcheriot -o - %s | FileCheck %s

define i32 @test1(i8 addrspace(200)* %cap) nounwind {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ct.cgetbase a1, ca0
; CHECK-NEXT:    sub a0, a0, a1
; CHECK-NEXT:    ct.cret
  %newcap = call i32 @llvm.cheri.cap.offset.get.i32(i8 addrspace(200)* %cap)
  ret i32 %newcap
}

declare i32 @llvm.cheri.cap.offset.get.i32(i8 addrspace(200)*)
