; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc --filetype=asm --mcpu=cheriot --mtriple=riscv32-unknown-unknown -target-abi cheriot  %s -mattr=+xcheri,+xcheripurecap,+xcheriot -o - | FileCheck %s
target datalayout = "e-m:e-pf200:64:64:64:32-p:32:32-i64:64-n32-S128-A200-P200-G200"
target triple = "riscv32-unknown-unknown"

@.str = private unnamed_addr addrspace(200) constant [16 x i8] c"Seven arguments\00", align 1

; Function Attrs: minsize mustprogress nounwind optsize
define dso_local cheriot_compartmentcalleecc noundef i32 @_Z22compartment_call_inneriiPKiiS0_ii(i32 noundef %0, i32 noundef %1, ptr addrspace(200) nocapture noundef readnone %2, i32 noundef %3, ptr addrspace(200) nocapture noundef readnone %4, i32 noundef %5, i32 noundef %6) local_unnamed_addr addrspace(200) #0 {
; CHECK-LABEL: _Z22compartment_call_inneriiPKiiS0_ii:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cgetbase t2, t0
; CHECK-NEXT:    bne t0, t2, .LBB0_6
; CHECK-NEXT:    blt t0, sp, .LBB0_6
; CHECK-NEXT:    # %bb.1:
; CHECK-NEXT:    cgetlen t1, t0
; CHECK-NEXT:    li t2, 4
; CHECK-NEXT:    blt t1, t2, .LBB0_6
; CHECK-NEXT:    # %bb.2:
; CHECK-NEXT:    cgetperm t1, t0
; CHECK-NEXT:    li t2, 126
; CHECK-NEXT:    bne t1, t2, .LBB0_6
; CHECK-NEXT:    # %bb.3:
; CHECK-NEXT:    ct.cgettag t1, t0
; CHECK-NEXT:    beqz t1, .LBB0_6
; CHECK-NEXT:    # %bb.4:
; CHECK-NEXT:    ct.cgettype t1, t0
; CHECK-NEXT:    bnez t1, .LBB0_6
; CHECK-NEXT:    # %bb.5:
; CHECK-NEXT:    cincoffset sp, sp, -16
; CHECK-NEXT:    csc ra, 8(sp) # 8-byte Folded Spill
; CHECK-NEXT:  .LBB0_7: # Label of block must be emitted
; CHECK-NEXT:    auipcc a0, %cheriot_compartment_code_hi(.L.str)
; CHECK-NEXT:    cincoffset a0, a0, %cheriot_compartment_lo_i(.LBB0_7)
; CHECK-NEXT:    csetbounds a0, a0, %cheriot_compartment_size(.L.str)
; CHECK-NEXT:    ccall _Z9debug_logIJEEvPKcDpT_
; CHECK-NEXT:    li a0, 0
; CHECK-NEXT:    li a1, 0
; CHECK-NEXT:    clc ra, 8(sp) # 8-byte Folded Reload
; CHECK-NEXT:    cincoffset sp, sp, 16
; CHECK-NEXT:    cret
; CHECK-NEXT:  .LBB0_6:
; CHECK-NEXT:    li a0, -1
; CHECK-NEXT:    li a1, -1
; CHECK-NEXT:    cret
  tail call void @_Z9debug_logIJEEvPKcDpT_(ptr addrspace(200) noundef nonnull @.str) #5
  ret i32 0
}

; Function Attrs: minsize mustprogress nounwind optsize
declare dso_local void @_Z9debug_logIJEEvPKcDpT_(ptr addrspace(200) noundef %0) addrspace(200) #1

attributes #0 = { minsize mustprogress nounwind optsize "cheri-compartment"="compartment_calls_inner" "interrupt-state"="enabled" "no-builtins" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+32bit,+c,+e,+m,+relax,+xcheri,-a,-d,-experimental-smaia,-experimental-ssaia,-experimental-zacas,-experimental-zfa,-experimental-zfbfmin,-experimental-zicond,-experimental-zihintntl,-experimental-ztso,-experimental-zvbb,-experimental-zvbc,-experimental-zvfbfmin,-experimental-zvfbfwma,-experimental-zvkg,-experimental-zvkn,-experimental-zvknc,-experimental-zvkned,-experimental-zvkng,-experimental-zvknha,-experimental-zvknhb,-experimental-zvks,-experimental-zvksc,-experimental-zvksed,-experimental-zvksg,-experimental-zvksh,-experimental-zvkt,-f,-h,-save-restore,-svinval,-svnapot,-svpbmt,-v,-xcheri-norvc,-xcvbitmanip,-xcvmac,-xsfcie,-xsfvcp,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmp,-zcmt,-zdinx,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zicbom,-zicbop,-zicboz,-zicntr,-zicsr,-zifencei,-zihintpause,-zihpm,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfh,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #1 = { minsize mustprogress nounwind optsize "cheri-compartment"="compartment_calls_inner" "no-builtins" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheriot" "target-features"="+32bit,+c,+e,+m,+relax,+xcheri,-a,-d,-experimental-smaia,-experimental-ssaia,-experimental-zacas,-experimental-zfa,-experimental-zfbfmin,-experimental-zicond,-experimental-zihintntl,-experimental-ztso,-experimental-zvbb,-experimental-zvbc,-experimental-zvfbfmin,-experimental-zvfbfwma,-experimental-zvkg,-experimental-zvkn,-experimental-zvknc,-experimental-zvkned,-experimental-zvkng,-experimental-zvknha,-experimental-zvknhb,-experimental-zvks,-experimental-zvksc,-experimental-zvksed,-experimental-zvksg,-experimental-zvksh,-experimental-zvkt,-f,-h,-save-restore,-svinval,-svnapot,-svpbmt,-v,-xcheri-norvc,-xcvbitmanip,-xcvmac,-xsfcie,-xsfvcp,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmp,-zcmt,-zdinx,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zicbom,-zicbop,-zicboz,-zicntr,-zicsr,-zifencei,-zihintpause,-zihpm,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-zve32f,-zve32x,-zve64d,-zve64f,-zve64x,-zvfh,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl32b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }

!llvm.linker.options = !{}
!llvm.module.flags = !{!0, !1, !2, !3, !4, !5}
!llvm.ident = !{!6}

!0 = !{i32 7, !"Dwarf Version", i32 5}
!1 = !{i32 2, !"Debug Info Version", i32 3}
!2 = !{i32 1, !"wchar_size", i32 2}
!3 = !{i32 1, !"target-abi", !"cheriot"}
!4 = !{i32 8, !"SmallDataLimit", i32 8}
!5 = !{i32 7, !"debug-info-assignment-tracking", i1 true}
!6 = !{!"clang version 17.0.0 (https://github.com/resistor/llvm-project-1.git eb7d8c12ab52f06ab31c1b14a2cb5e470bb2b1ce)"}
!7 = !{i64 2817213}
!8 = !{i64 2817464}
!9 = !{!10, !10, i64 0}
!10 = !{!"bool", !11, i64 0}
!11 = !{!"omnipotent char", !12, i64 0}
!12 = !{!"Simple C++ TBAA"}
