; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 --mcpu=cheriot -target-abi=cheriot -mattr=+xcheri,+xcheripurecap,+xcheriot -o - %s | FileCheck %s

define i8 addrspace(200)* @test1(i8 addrspace(200)* %cap, i32 %bounds) nounwind {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ct.csetbounds a0, a0, 3
; CHECK-NEXT:    ct.cret
  %newcap = call i8 addrspace(200)* @llvm.cheri.cap.bounds.set.exact.i32(i8 addrspace(200)* %cap, i32 3)
  ret i8 addrspace(200)* %newcap
}

define i8 addrspace(200)* @test2(i8 addrspace(200)* %cap, i32 %bounds) nounwind {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    ct.csetbounds a0, a0, 511
; CHECK-NEXT:    ct.cret
  %newcap = call i8 addrspace(200)* @llvm.cheri.cap.bounds.set.exact.i32(i8 addrspace(200)* %cap, i32 511)
  ret i8 addrspace(200)* %newcap
}

define i8 addrspace(200)* @test3(i8 addrspace(200)* %cap, i32 %bounds) nounwind {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a1, 512
; CHECK-NEXT:    ct.csetboundsexact a0, a0, a1
; CHECK-NEXT:    ct.cret
  %newcap = call i8 addrspace(200)* @llvm.cheri.cap.bounds.set.exact.i32(i8 addrspace(200)* %cap, i32 512)
  ret i8 addrspace(200)* %newcap
}

declare i8 addrspace(200)* @llvm.cheri.cap.bounds.set.exact.i32(i8 addrspace(200)*, i32)
