; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; Check that .LCPI symbols have a size associated with them.
; RUN: %riscv32_cheri_purecap_llc -mattr=+d -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=RV32
; RUN: %riscv64_cheri_purecap_llc -mattr=+d -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=RV64

define double @double_add_const(double %a) nounwind {
; RV32-LABEL: double_add_const:
; RV32:       # %bb.0:
; RV32-NEXT:  .LBB0_1: # Label of block must be emitted
; RV32-NEXT:    auipcc a0, %pcrel_hi(.LCPI0_0)
; RV32-NEXT:    cincoffset a0, a0, %pcrel_lo(.LBB0_1)
; RV32-NEXT:    cfld fa5, 0(a0)
; RV32-NEXT:    fadd.d fa0, fa0, fa5
; RV32-NEXT:    cret
;
; RV64-LABEL: double_add_const:
; RV64:       # %bb.0:
; RV64-NEXT:    li a0, 1023
; RV64-NEXT:    slli a0, a0, 52
; RV64-NEXT:    fmv.d.x fa5, a0
; RV64-NEXT:    fadd.d fa0, fa0, fa5
; RV64-NEXT:    cret
  %1 = fadd double %a, 1.0
  ret double %1
}

define float @float_add_const(float %a) nounwind {
; RV32-LABEL: float_add_const:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a0, 260096
; RV32-NEXT:    fmv.w.x fa5, a0
; RV32-NEXT:    fadd.s fa0, fa0, fa5
; RV32-NEXT:    cret
;
; RV64-LABEL: float_add_const:
; RV64:       # %bb.0:
; RV64-NEXT:    lui a0, 260096
; RV64-NEXT:    fmv.w.x fa5, a0
; RV64-NEXT:    fadd.s fa0, fa0, fa5
; RV64-NEXT:    cret
  %1 = fadd float %a, 1.0
  ret float %1
}
