; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;; The CFromPtr instruction is not part of ISAv9, check that we emit `x == 0 ? null : csetaddr(auth, x)` instead.
;; Note: Since DDC-offsetting is no longer part of ISAv9, the expansion consistently uses csetaddr and not csetoffset!
; RUN: %riscv64_cheri_purecap_llc < %s | FileCheck %s --check-prefix=ISAV9

;; (int_cheri_cap_from_ptr auth, x) -> x == 0 ? null : csetoffset(auth, x)
define dso_local i8 addrspace(200)* @cap_from_ptr(i8 addrspace(200)* addrspace(200)* %ptr, i8 addrspace(200)* %cap, i64 %offset) nounwind {
; ISAV9-LABEL: cap_from_ptr:
; ISAV9:       # %bb.0: # %entry
; ISAV9-NEXT:    cmove a3, a0
; ISAV9-NEXT:    bnez a2, .LBB0_2
; ISAV9-NEXT:  # %bb.1: # %entry
; ISAV9-NEXT:    cmove a0, zero
; ISAV9-NEXT:    csc zero, 0(a3)
; ISAV9-NEXT:    cret
; ISAV9-NEXT:  .LBB0_2:
; ISAV9-NEXT:    csetaddr a0, a1, a2
; ISAV9-NEXT:    csc a0, 0(a3)
; ISAV9-NEXT:    cret
entry:
  %new = call i8 addrspace(200)* @llvm.cheri.cap.from.pointer.i64(i8 addrspace(200)* %cap, i64 %offset)
  store i8 addrspace(200)* %new, i8 addrspace(200)* addrspace(200)* %ptr, align 16
  ret i8 addrspace(200)* %new
}

;; (int_cheri_cap_from_ptr ddc, y) -> x == 0 ? null : csetaddr(ddc, x)
define dso_local i8 addrspace(200)* @cap_from_ptr_ddc(i8 addrspace(200)* addrspace(200)* %ptr, i64 %offset) nounwind {
; ISAV9-LABEL: cap_from_ptr_ddc:
; ISAV9:       # %bb.0: # %entry
; ISAV9-NEXT:    cmove a2, a0
; ISAV9-NEXT:    cspecialr a0, ddc
; ISAV9-NEXT:    bnez a1, .LBB1_2
; ISAV9-NEXT:  # %bb.1: # %entry
; ISAV9-NEXT:    cmove a0, zero
; ISAV9-NEXT:    csc zero, 0(a2)
; ISAV9-NEXT:    cret
; ISAV9-NEXT:  .LBB1_2:
; ISAV9-NEXT:    csetaddr a0, a0, a1
; ISAV9-NEXT:    csc a0, 0(a2)
; ISAV9-NEXT:    cret
entry:
  %ddc = call i8 addrspace(200)* @llvm.cheri.ddc.get()
  %new = call i8 addrspace(200)* @llvm.cheri.cap.from.pointer.i64(i8 addrspace(200)* %ddc, i64 %offset)
  store i8 addrspace(200)* %new, i8 addrspace(200)* addrspace(200)* %ptr, align 16
  ret i8 addrspace(200)* %new
}

declare i8 addrspace(200)* @llvm.cheri.cap.from.pointer.i64(i8 addrspace(200)*, i64)
declare i8 addrspace(200)* @llvm.cheri.ddc.get()
