; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --extra_scrub
; TODO: Once https://github.com/CTSRD-CHERI/llvm-project/issues/459 has been fixed use +d and il32pc64d
; RUN: llc -mtriple=riscv32 -mattr=+f,+xcheri,+xcheripurecap -target-abi il32pc64f -verify-machineinstrs < %s \
; RUN:   | %cheri64_FileCheck --check-prefixes=CHECK,RV32IFXCHERI %s --allow-unused-prefixes
; RUN: llc -mtriple=riscv64 -mattr=+f,+xcheri,+xcheripurecap -target-abi l64pc128f -verify-machineinstrs < %s \
; RUN:   | %cheri128_FileCheck --check-prefixes=CHECK,RV64IFXCHERI %s --allow-unused-prefixes
; Previously expandUnalignedLoad() would trigger assertions for unaligned floating-point values since we were creating
; incorrect capability constants.
declare i32 @printf(i8 addrspace(200)*, ...) addrspace(200)

define i32 @unaligned_float(float addrspace(200)* nocapture readonly %arg, float %newval) unnamed_addr addrspace(200) nounwind {
; RV32IFXCHERI-LABEL: unaligned_float:
; RV32IFXCHERI:       # %bb.0: # %bb
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, -32
; RV32IFXCHERI-NEXT:    csc ra, 24(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s0, 16(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    cfsw fs0, 12(sp) # 4-byte Folded Spill
; RV32IFXCHERI-NEXT:    cmove s0, a0
; RV32IFXCHERI-NEXT:    clbu a0, 1(a0)
; RV32IFXCHERI-NEXT:    clbu a1, 2(s0)
; RV32IFXCHERI-NEXT:    clbu a2, 3(s0)
; RV32IFXCHERI-NEXT:    clbu a3, 0(s0)
; RV32IFXCHERI-NEXT:    slli a0, a0, 8
; RV32IFXCHERI-NEXT:    slli a1, a1, 16
; RV32IFXCHERI-NEXT:    slli a2, a2, 24
; RV32IFXCHERI-NEXT:    or a0, a0, a3
; RV32IFXCHERI-NEXT:    or a1, a2, a1
; RV32IFXCHERI-NEXT:    or a0, a1, a0
; RV32IFXCHERI-NEXT:    fmv.w.x fa5, a0
; RV32IFXCHERI-NEXT:    fmv.s fs0, fa0
; RV32IFXCHERI-NEXT:    fmv.s fa0, fa5
; RV32IFXCHERI-NEXT:    ccall __extendsfdf2
; RV32IFXCHERI-NEXT:    csw a1, 4(sp)
; RV32IFXCHERI-NEXT:    csw a0, 0(sp)
; RV32IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV32IFXCHERI-NEXT:    ccall printf
; RV32IFXCHERI-NEXT:    fmv.x.w a1, fs0
; RV32IFXCHERI-NEXT:    srli a2, a1, 24
; RV32IFXCHERI-NEXT:    csb a2, 3(s0)
; RV32IFXCHERI-NEXT:    srli a2, a1, 16
; RV32IFXCHERI-NEXT:    csb a2, 2(s0)
; RV32IFXCHERI-NEXT:    srli a2, a1, 8
; RV32IFXCHERI-NEXT:    csb a2, 1(s0)
; RV32IFXCHERI-NEXT:    csb a1, 0(s0)
; RV32IFXCHERI-NEXT:    clc ra, 24(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s0, 16(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    cflw fs0, 12(sp) # 4-byte Folded Reload
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, 32
; RV32IFXCHERI-NEXT:    cret
;
; RV64IFXCHERI-LABEL: unaligned_float:
; RV64IFXCHERI:       # %bb.0: # %bb
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, -64
; RV64IFXCHERI-NEXT:    csc ra, 48(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s0, 32(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    cfsw fs0, 28(sp) # 4-byte Folded Spill
; RV64IFXCHERI-NEXT:    fmv.s fs0, fa0
; RV64IFXCHERI-NEXT:    cmove s0, a0
; RV64IFXCHERI-NEXT:    clbu a0, 1(a0)
; RV64IFXCHERI-NEXT:    clbu a1, 2(s0)
; RV64IFXCHERI-NEXT:    clb a2, 3(s0)
; RV64IFXCHERI-NEXT:    clbu a3, 0(s0)
; RV64IFXCHERI-NEXT:    slli a0, a0, 8
; RV64IFXCHERI-NEXT:    slli a1, a1, 16
; RV64IFXCHERI-NEXT:    slli a2, a2, 24
; RV64IFXCHERI-NEXT:    or a0, a0, a3
; RV64IFXCHERI-NEXT:    or a1, a2, a1
; RV64IFXCHERI-NEXT:    or a0, a1, a0
; RV64IFXCHERI-NEXT:    csw a0, 8(sp)
; RV64IFXCHERI-NEXT:    cflw fa0, 8(sp)
; RV64IFXCHERI-NEXT:    ccall __extendsfdf2
; RV64IFXCHERI-NEXT:    csd a0, 0(sp)
; RV64IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV64IFXCHERI-NEXT:    ccall printf
; RV64IFXCHERI-NEXT:    cfsw fs0, 16(sp)
; RV64IFXCHERI-NEXT:    clw a1, 16(sp)
; RV64IFXCHERI-NEXT:    csb a1, 0(s0)
; RV64IFXCHERI-NEXT:    srli a2, a1, 24
; RV64IFXCHERI-NEXT:    csb a2, 3(s0)
; RV64IFXCHERI-NEXT:    srli a2, a1, 16
; RV64IFXCHERI-NEXT:    srli a1, a1, 8
; RV64IFXCHERI-NEXT:    csb a2, 2(s0)
; RV64IFXCHERI-NEXT:    csb a1, 1(s0)
; RV64IFXCHERI-NEXT:    clc ra, 48(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s0, 32(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    cflw fs0, 28(sp) # 4-byte Folded Reload
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, 64
; RV64IFXCHERI-NEXT:    cret
bb:
  %unaligned_load = load float, float addrspace(200)* %arg, align 1
  %ext = fpext float %unaligned_load to double
  %ret = tail call i32 (i8 addrspace(200)*, ...) @printf(i8 addrspace(200)* nonnull dereferenceable(1) undef, double %ext)
  store float %newval, float addrspace(200)* %arg, align 1
  ret i32 %ret
}

define i32 @unaligned_double(double addrspace(200)* nocapture readonly %arg, double %newval) unnamed_addr addrspace(200) nounwind {
; RV32IFXCHERI-LABEL: unaligned_double:
; RV32IFXCHERI:       # %bb.0: # %bb
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, -48
; RV32IFXCHERI-NEXT:    csc ra, 40(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s0, 32(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s1, 24(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s2, 16(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    mv s0, a2
; RV32IFXCHERI-NEXT:    mv s1, a1
; RV32IFXCHERI-NEXT:    cmove s2, a0
; RV32IFXCHERI-NEXT:    clhu a0, 2(a0)
; RV32IFXCHERI-NEXT:    clhu a1, 6(s2)
; RV32IFXCHERI-NEXT:    clhu a2, 0(s2)
; RV32IFXCHERI-NEXT:    clhu a3, 4(s2)
; RV32IFXCHERI-NEXT:    slli a0, a0, 16
; RV32IFXCHERI-NEXT:    slli a1, a1, 16
; RV32IFXCHERI-NEXT:    or a0, a0, a2
; RV32IFXCHERI-NEXT:    or a1, a1, a3
; RV32IFXCHERI-NEXT:    csw a1, 4(sp)
; RV32IFXCHERI-NEXT:    csw a0, 0(sp)
; RV32IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV32IFXCHERI-NEXT:    ccall printf
; RV32IFXCHERI-NEXT:    srli a1, s0, 16
; RV32IFXCHERI-NEXT:    csh s0, 4(s2)
; RV32IFXCHERI-NEXT:    csh a1, 6(s2)
; RV32IFXCHERI-NEXT:    srli a1, s1, 16
; RV32IFXCHERI-NEXT:    csh a1, 2(s2)
; RV32IFXCHERI-NEXT:    csh s1, 0(s2)
; RV32IFXCHERI-NEXT:    clc ra, 40(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s0, 32(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s1, 24(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s2, 16(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, 48
; RV32IFXCHERI-NEXT:    cret
;
; RV64IFXCHERI-LABEL: unaligned_double:
; RV64IFXCHERI:       # %bb.0: # %bb
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, -64
; RV64IFXCHERI-NEXT:    csc ra, 48(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s0, 32(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s1, 16(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    mv s0, a1
; RV64IFXCHERI-NEXT:    cmove s1, a0
; RV64IFXCHERI-NEXT:    clhu a0, 2(a0)
; RV64IFXCHERI-NEXT:    clhu a1, 4(s1)
; RV64IFXCHERI-NEXT:    clhu a2, 6(s1)
; RV64IFXCHERI-NEXT:    clhu a3, 0(s1)
; RV64IFXCHERI-NEXT:    slli a0, a0, 16
; RV64IFXCHERI-NEXT:    slli a1, a1, 32
; RV64IFXCHERI-NEXT:    slli a2, a2, 48
; RV64IFXCHERI-NEXT:    or a0, a0, a3
; RV64IFXCHERI-NEXT:    or a1, a2, a1
; RV64IFXCHERI-NEXT:    or a0, a1, a0
; RV64IFXCHERI-NEXT:    csd a0, 0(sp)
; RV64IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV64IFXCHERI-NEXT:    ccall printf
; RV64IFXCHERI-NEXT:    srli a1, s0, 48
; RV64IFXCHERI-NEXT:    srli a2, s0, 32
; RV64IFXCHERI-NEXT:    csh a1, 6(s1)
; RV64IFXCHERI-NEXT:    csh a2, 4(s1)
; RV64IFXCHERI-NEXT:    srli a1, s0, 16
; RV64IFXCHERI-NEXT:    csh a1, 2(s1)
; RV64IFXCHERI-NEXT:    csh s0, 0(s1)
; RV64IFXCHERI-NEXT:    clc ra, 48(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s0, 32(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s1, 16(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, 64
; RV64IFXCHERI-NEXT:    cret
bb:
  %unaligned_load = load double, double addrspace(200)* %arg, align 2
  %ret = tail call i32 (i8 addrspace(200)*, ...) @printf(i8 addrspace(200)* nonnull dereferenceable(1) undef, double %unaligned_load)
  store double %newval, double addrspace(200)* %arg, align 2
  ret i32 %ret
}

define i32 @unaligned_fp128(fp128 addrspace(200)* nocapture readonly %arg, fp128 %newval) unnamed_addr addrspace(200) nounwind {
; RV32IFXCHERI-LABEL: unaligned_fp128:
; RV32IFXCHERI:       # %bb.0: # %bb
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, -80
; RV32IFXCHERI-NEXT:    csc ra, 72(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s0, 64(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s1, 56(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s2, 48(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s3, 40(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s4, 32(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    cmove s0, a0
; RV32IFXCHERI-NEXT:    clw s1, 0(a1)
; RV32IFXCHERI-NEXT:    clw s2, 4(a1)
; RV32IFXCHERI-NEXT:    clw s3, 8(a1)
; RV32IFXCHERI-NEXT:    clw s4, 12(a1)
; RV32IFXCHERI-NEXT:    clw a1, 0(a0)
; RV32IFXCHERI-NEXT:    clw a2, 4(a0)
; RV32IFXCHERI-NEXT:    clw a0, 8(a0)
; RV32IFXCHERI-NEXT:    clw a3, 12(s0)
; RV32IFXCHERI-NEXT:    csw a3, 28(sp)
; RV32IFXCHERI-NEXT:    csw a0, 24(sp)
; RV32IFXCHERI-NEXT:    cincoffset a0, sp, 16
; RV32IFXCHERI-NEXT:    csw a2, 20(sp)
; RV32IFXCHERI-NEXT:    csw a1, 16(sp)
; RV32IFXCHERI-NEXT:    ccall __trunctfdf2
; RV32IFXCHERI-NEXT:    csw a1, 4(sp)
; RV32IFXCHERI-NEXT:    csw a0, 0(sp)
; RV32IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV32IFXCHERI-NEXT:    ccall printf
; RV32IFXCHERI-NEXT:    csw s4, 12(s0)
; RV32IFXCHERI-NEXT:    csw s3, 8(s0)
; RV32IFXCHERI-NEXT:    csw s2, 4(s0)
; RV32IFXCHERI-NEXT:    csw s1, 0(s0)
; RV32IFXCHERI-NEXT:    clc ra, 72(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s0, 64(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s1, 56(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s2, 48(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s3, 40(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s4, 32(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, 80
; RV32IFXCHERI-NEXT:    cret
;
; RV64IFXCHERI-LABEL: unaligned_fp128:
; RV64IFXCHERI:       # %bb.0: # %bb
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, -80
; RV64IFXCHERI-NEXT:    csc ra, 64(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s0, 48(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s1, 32(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s2, 16(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    mv s0, a2
; RV64IFXCHERI-NEXT:    mv s1, a1
; RV64IFXCHERI-NEXT:    cmove s2, a0
; RV64IFXCHERI-NEXT:    clwu a0, 4(a0)
; RV64IFXCHERI-NEXT:    clwu a1, 12(s2)
; RV64IFXCHERI-NEXT:    clwu a2, 0(s2)
; RV64IFXCHERI-NEXT:    clwu a3, 8(s2)
; RV64IFXCHERI-NEXT:    slli a0, a0, 32
; RV64IFXCHERI-NEXT:    slli a1, a1, 32
; RV64IFXCHERI-NEXT:    or a0, a0, a2
; RV64IFXCHERI-NEXT:    or a1, a1, a3
; RV64IFXCHERI-NEXT:    ccall __trunctfdf2
; RV64IFXCHERI-NEXT:    csd a0, 0(sp)
; RV64IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV64IFXCHERI-NEXT:    ccall printf
; RV64IFXCHERI-NEXT:    srli a1, s0, 32
; RV64IFXCHERI-NEXT:    csw s0, 8(s2)
; RV64IFXCHERI-NEXT:    csw a1, 12(s2)
; RV64IFXCHERI-NEXT:    srli a1, s1, 32
; RV64IFXCHERI-NEXT:    csw a1, 4(s2)
; RV64IFXCHERI-NEXT:    csw s1, 0(s2)
; RV64IFXCHERI-NEXT:    clc ra, 64(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s0, 48(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s1, 32(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s2, 16(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, 80
; RV64IFXCHERI-NEXT:    cret
bb:
  %unaligned_load = load fp128, fp128 addrspace(200)* %arg, align 4
  %trunc = fptrunc fp128 %unaligned_load to double
  %ret = tail call i32 (i8 addrspace(200)*, ...) @printf(i8 addrspace(200)* nonnull dereferenceable(1) undef, double %trunc)
  store fp128 %newval, fp128 addrspace(200)* %arg, align 4
  ret i32 %ret
}

define i32 @unaligned_int(i32 addrspace(200)* nocapture readonly %arg) unnamed_addr addrspace(200) nounwind {
; RV32IFXCHERI-LABEL: unaligned_int:
; RV32IFXCHERI:       # %bb.0: # %bb
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, -32
; RV32IFXCHERI-NEXT:    csc ra, 24(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    csc s0, 16(sp) # 8-byte Folded Spill
; RV32IFXCHERI-NEXT:    cmove s0, a0
; RV32IFXCHERI-NEXT:    clbu a0, 1(a0)
; RV32IFXCHERI-NEXT:    clbu a1, 2(s0)
; RV32IFXCHERI-NEXT:    clbu a2, 3(s0)
; RV32IFXCHERI-NEXT:    clbu a3, 0(s0)
; RV32IFXCHERI-NEXT:    slli a0, a0, 8
; RV32IFXCHERI-NEXT:    slli a1, a1, 16
; RV32IFXCHERI-NEXT:    slli a2, a2, 24
; RV32IFXCHERI-NEXT:    or a0, a0, a3
; RV32IFXCHERI-NEXT:    or a1, a2, a1
; RV32IFXCHERI-NEXT:    or a0, a1, a0
; RV32IFXCHERI-NEXT:    csw a0, 0(sp)
; RV32IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV32IFXCHERI-NEXT:    ccall printf
; RV32IFXCHERI-NEXT:    csb zero, 3(s0)
; RV32IFXCHERI-NEXT:    csb zero, 2(s0)
; RV32IFXCHERI-NEXT:    li a1, 1
; RV32IFXCHERI-NEXT:    csb zero, 1(s0)
; RV32IFXCHERI-NEXT:    csb a1, 0(s0)
; RV32IFXCHERI-NEXT:    clc ra, 24(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    clc s0, 16(sp) # 8-byte Folded Reload
; RV32IFXCHERI-NEXT:    cincoffset sp, sp, 32
; RV32IFXCHERI-NEXT:    cret
;
; RV64IFXCHERI-LABEL: unaligned_int:
; RV64IFXCHERI:       # %bb.0: # %bb
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, -48
; RV64IFXCHERI-NEXT:    csc ra, 32(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    csc s0, 16(sp) # 16-byte Folded Spill
; RV64IFXCHERI-NEXT:    cmove s0, a0
; RV64IFXCHERI-NEXT:    clbu a0, 1(a0)
; RV64IFXCHERI-NEXT:    clbu a1, 2(s0)
; RV64IFXCHERI-NEXT:    clb a2, 3(s0)
; RV64IFXCHERI-NEXT:    clbu a3, 0(s0)
; RV64IFXCHERI-NEXT:    slli a0, a0, 8
; RV64IFXCHERI-NEXT:    slli a1, a1, 16
; RV64IFXCHERI-NEXT:    slli a2, a2, 24
; RV64IFXCHERI-NEXT:    or a0, a0, a3
; RV64IFXCHERI-NEXT:    or a1, a2, a1
; RV64IFXCHERI-NEXT:    or a0, a1, a0
; RV64IFXCHERI-NEXT:    csd a0, 0(sp)
; RV64IFXCHERI-NEXT:    # implicit-def: $x10_y
; RV64IFXCHERI-NEXT:    ccall printf
; RV64IFXCHERI-NEXT:    csb zero, 3(s0)
; RV64IFXCHERI-NEXT:    csb zero, 2(s0)
; RV64IFXCHERI-NEXT:    li a1, 1
; RV64IFXCHERI-NEXT:    csb zero, 1(s0)
; RV64IFXCHERI-NEXT:    csb a1, 0(s0)
; RV64IFXCHERI-NEXT:    clc ra, 32(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    clc s0, 16(sp) # 16-byte Folded Reload
; RV64IFXCHERI-NEXT:    cincoffset sp, sp, 48
; RV64IFXCHERI-NEXT:    cret
bb:
  %unaligned_load = load i32, i32 addrspace(200)* %arg, align 1
  %ret = tail call i32 (i8 addrspace(200)*, ...) @printf(i8 addrspace(200)* nonnull dereferenceable(1) undef, i32 %unaligned_load)
  store i32 1, i32 addrspace(200)* %arg, align 1
  ret i32 %ret
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
