// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %cheri_cc1 -emit-llvm -o - -O0 %s | FileCheck %s -check-prefix N64
// RUN: %cheri_purecap_cc1 -emit-llvm -o - -O0 %s | FileCheck %s -check-prefix PURECAP
typedef struct {
  _Bool volatile repr;
} atomic_b_t;

atomic_b_t value;
// N64-LABEL: @atomic_compare_exchange_weak_b(
// N64-NEXT:  entry:
// N64-NEXT:    [[EXPECTED_ADDR:%.*]] = alloca i8, align 1
// N64-NEXT:    [[DESIRED_ADDR:%.*]] = alloca i8, align 1
// N64-NEXT:    [[STOREDV:%.*]] = zext i1 [[EXPECTED:%.*]] to i8
// N64-NEXT:    store i8 [[STOREDV]], ptr [[EXPECTED_ADDR]], align 1
// N64-NEXT:    [[STOREDV1:%.*]] = zext i1 [[DESIRED:%.*]] to i8
// N64-NEXT:    store i8 [[STOREDV1]], ptr [[DESIRED_ADDR]], align 1
// N64-NEXT:    [[TMP0:%.*]] = load i8, ptr [[EXPECTED_ADDR]], align 1
// N64-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP0]], 0
// N64-NEXT:    [[STOREDV2:%.*]] = zext i1 [[LOADEDV]] to i8
// N64-NEXT:    [[TMP1:%.*]] = load i8, ptr [[DESIRED_ADDR]], align 1
// N64-NEXT:    [[LOADEDV3:%.*]] = icmp ne i8 [[TMP1]], 0
// N64-NEXT:    [[STOREDV4:%.*]] = zext i1 [[LOADEDV3]] to i8
// N64-NEXT:    [[TMP2:%.*]] = cmpxchg ptr @value, i8 [[STOREDV2]], i8 [[STOREDV4]] seq_cst seq_cst, align 1
// N64-NEXT:    [[TMP3:%.*]] = extractvalue { i8, i1 } [[TMP2]], 0
// N64-NEXT:    [[LOADEDV5:%.*]] = icmp ne i8 [[TMP3]], 0
// N64-NEXT:    ret i1 [[LOADEDV5]]
//
// PURECAP-LABEL: @atomic_compare_exchange_weak_b(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[EXPECTED_ADDR:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    [[DESIRED_ADDR:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    [[STOREDV:%.*]] = zext i1 [[EXPECTED:%.*]] to i8
// PURECAP-NEXT:    store i8 [[STOREDV]], ptr addrspace(200) [[EXPECTED_ADDR]], align 1
// PURECAP-NEXT:    [[STOREDV1:%.*]] = zext i1 [[DESIRED:%.*]] to i8
// PURECAP-NEXT:    store i8 [[STOREDV1]], ptr addrspace(200) [[DESIRED_ADDR]], align 1
// PURECAP-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[EXPECTED_ADDR]], align 1
// PURECAP-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP0]], 0
// PURECAP-NEXT:    [[STOREDV2:%.*]] = zext i1 [[LOADEDV]] to i8
// PURECAP-NEXT:    [[TMP1:%.*]] = load i8, ptr addrspace(200) [[DESIRED_ADDR]], align 1
// PURECAP-NEXT:    [[LOADEDV3:%.*]] = icmp ne i8 [[TMP1]], 0
// PURECAP-NEXT:    [[STOREDV4:%.*]] = zext i1 [[LOADEDV3]] to i8
// PURECAP-NEXT:    [[TMP2:%.*]] = cmpxchg ptr addrspace(200) @value, i8 [[STOREDV2]], i8 [[STOREDV4]] seq_cst seq_cst, align 1
// PURECAP-NEXT:    [[TMP3:%.*]] = extractvalue { i8, i1 } [[TMP2]], 0
// PURECAP-NEXT:    [[LOADEDV5:%.*]] = icmp ne i8 [[TMP3]], 0
// PURECAP-NEXT:    ret i1 [[LOADEDV5]]
//
_Bool atomic_compare_exchange_weak_b(_Bool expected, _Bool desired) {
  return __sync_val_compare_and_swap(&value.repr, expected, desired);
}

// N64-LABEL: @atomic_swap_b(
// N64-NEXT:  entry:
// N64-NEXT:    [[DESIRED_ADDR:%.*]] = alloca i8, align 1
// N64-NEXT:    [[STOREDV:%.*]] = zext i1 [[DESIRED:%.*]] to i8
// N64-NEXT:    store i8 [[STOREDV]], ptr [[DESIRED_ADDR]], align 1
// N64-NEXT:    [[TMP0:%.*]] = load i8, ptr [[DESIRED_ADDR]], align 1
// N64-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP0]], 0
// N64-NEXT:    [[STOREDV1:%.*]] = zext i1 [[LOADEDV]] to i8
// N64-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr @value, i8 [[STOREDV1]] seq_cst, align 1
// N64-NEXT:    [[LOADEDV2:%.*]] = icmp ne i8 [[TMP1]], 0
// N64-NEXT:    ret i1 [[LOADEDV2]]
//
// PURECAP-LABEL: @atomic_swap_b(
// PURECAP-NEXT:  entry:
// PURECAP-NEXT:    [[DESIRED_ADDR:%.*]] = alloca i8, align 1, addrspace(200)
// PURECAP-NEXT:    [[STOREDV:%.*]] = zext i1 [[DESIRED:%.*]] to i8
// PURECAP-NEXT:    store i8 [[STOREDV]], ptr addrspace(200) [[DESIRED_ADDR]], align 1
// PURECAP-NEXT:    [[TMP0:%.*]] = load i8, ptr addrspace(200) [[DESIRED_ADDR]], align 1
// PURECAP-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP0]], 0
// PURECAP-NEXT:    [[STOREDV1:%.*]] = zext i1 [[LOADEDV]] to i8
// PURECAP-NEXT:    [[TMP1:%.*]] = atomicrmw xchg ptr addrspace(200) @value, i8 [[STOREDV1]] seq_cst, align 1
// PURECAP-NEXT:    [[LOADEDV2:%.*]] = icmp ne i8 [[TMP1]], 0
// PURECAP-NEXT:    ret i1 [[LOADEDV2]]
//
_Bool atomic_swap_b(_Bool desired) {
  return __sync_swap(&value.repr, desired);
}
