// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-attributes --check-globals
// RUN: %cheri_purecap_cc1 -emit-llvm -O0 -o - %s | FileCheck %s

// Verify that we set no_preserve_cheri_tags on struct copies that do no contain capabilities,
// and must_preserve_cheri_tags on struct copies that do.

struct __attribute__((packed)) a { void *i; char j; };
struct __attribute__((packed)) b { long long i; char j; };

// CHECK: Function Attrs: noinline nounwind optnone
// CHECK-LABEL: @test1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[X:%.*]], ptr addrspace(200) [[X_ADDR]], align 16
// CHECK-NEXT:    store ptr addrspace(200) [[Y:%.*]], ptr addrspace(200) [[Y_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[Y_ADDR]], align 16
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 1 [[TMP0]], ptr addrspace(200) align 1 [[TMP1]], i64 17, i1 false) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret void
//
void test1(struct a *x, struct a *y) {
  *x = *y;
}

// CHECK: Function Attrs: noinline nounwind optnone
// CHECK-LABEL: @test2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca ptr addrspace(200), align 16, addrspace(200)
// CHECK-NEXT:    store ptr addrspace(200) [[X:%.*]], ptr addrspace(200) [[X_ADDR]], align 16
// CHECK-NEXT:    store ptr addrspace(200) [[Y:%.*]], ptr addrspace(200) [[Y_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr addrspace(200), ptr addrspace(200) [[Y_ADDR]], align 16
// CHECK-NEXT:    call void @llvm.memcpy.p200.p200.i64(ptr addrspace(200) align 1 [[TMP0]], ptr addrspace(200) align 1 [[TMP1]], i64 9, i1 false) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    ret void
//
void test2(struct b *x, struct b *y) {
  *x = *y;
}

//.
// CHECK: attributes #[[ATTR0:[0-9]+]] = { noinline nounwind optnone "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cheri128" "target-features"="+cheri128,+chericap" }
// CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }
// CHECK: attributes #[[ATTR2]] = { must_preserve_cheri_tags }
// CHECK: attributes #[[ATTR3]] = { no_preserve_cheri_tags }
//.
// CHECK: [[META0:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
// CHECK: [[META1:![0-9]+]] = !{!"{{.*}}clang version {{.*}}"}
//.
