// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 %s -o - "-triple" "riscv32cheriot-unknown-cheriotrtos" "-emit-llvm" "-mframe-pointer=none" "-mcmodel=small" "-target-abi" "cheriot" "-target-feature" "+xcheriot" "-Oz" "-Werror" -std=c2x | FileCheck %s

// CHECK-LABEL: define dso_local void @foo
// CHECK-SAME: (ptr addrspace(200) nofree noundef readonly captures(none) [[BAR:%.*]]) local_unnamed_addr addrspace(200) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    tail call addrspace(200) void [[BAR]]() #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    ret void
//
void foo(void (*bar)())
{
        bar();
}

// CHECK-LABEL: define dso_local cheriot_librarycallcc void @_Z3barv
// CHECK-SAME: () local_unnamed_addr addrspace(200) #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void __attribute__((cheriot_libcall)) bar()
{
        return;
}

// CHECK-LABEL: define dso_local void @test
// CHECK-SAME: () local_unnamed_addr addrspace(200) #[[ATTR1]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret void
//
void test()
{
        foo(bar);
}
