; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --extra_scrub
; REQUIRES: mips-registered-target, riscv-registered-target
; After merging to the LLVM11 branch point certain by-value arguments were no longer being copied.
; Changing the IR to use addrspace(0) and compiling for non-CHERI adds memcpy() calls, so we should do the same for purecap.
; This (incorrect) behaviour was added in a297402637b73b9d783a229e9b41c57ea7b92e2e, but we apparently never hit
; because the frontend would almost always emit a local alloca already.

; First check that non-CHERI targets add a memcpy
; RUN: sed -e 's/addrspace(200)/addrspace(0)/g' -e 's/p200i8/p0i8/g' %s | llc -mtriple riscv64-unknown-freebsd -o - -relocation-model=static | FileCheck %s --check-prefixes CHECK,RV64,RV64-STATIC --allow-unused-prefixes
; RUN: sed -e 's/addrspace(200)/addrspace(0)/g' -e 's/p200i8/p0i8/g' %s | llc -mtriple riscv64-unknown-freebsd -o - -relocation-model=pic | FileCheck %s --check-prefixes CHECK,RV64,RV64-PIC --allow-unused-prefixes
; RUN: sed -e 's/addrspace(200)/addrspace(0)/g' -e 's/p200i8/p0i8/g' %s | llc -mtriple mips64-unknown-freebsd -o - -relocation-model=pic | FileCheck %s --check-prefixes CHECK,MIPS,MIPS-PIC --allow-unused-prefixes
; Next check purecap targets:
; RUN: %riscv64_cheri_purecap_llc -o - %s | FileCheck %s --check-prefixes CHECK,PURECAP-RV64 --allow-unused-prefixes
; RUN: %cheri_purecap_llc -o - %s | FileCheck %s --check-prefixes CHECK,PURECAP-MIPS --allow-unused-prefixes

; IR originally generated from %cheri_purecap_cc1 -mrelocation-model pic -pic-level 1 -pic-is-pie -O -S %s -o - -emit-llvm
; Interestingly, the purecap RISCV IR contains a temporary alloca and MIPS also does without the pic flags (CodeGenFunction::EmitCall()).
; struct foo {
;   char data[1024];
; };
;
; extern void assert_eq(long l1, long l2);
; extern void *memset(void *, int, unsigned long);
; struct foo global_foo;
; __attribute__((noinline)) void foo_byval(struct foo f) {
;   memset(f.data, 42, sizeof(f.data));
; }
;
; void clang_purecap_byval_args(void) {
;   /* Check that structs passed by value are actually copied */
;   memset(global_foo.data, 0, sizeof(global_foo.data));
;   assert_eq(global_foo.data[0], 0);
;   foo_byval(global_foo);
;   assert_eq(global_foo.data[0], 0);
; }

%struct.foo = type { [1024 x i8] }

@global_foo = dso_local local_unnamed_addr addrspace(200) global %struct.foo zeroinitializer, align 8

declare dso_local void @foo_byval(%struct.foo addrspace(200)* nocapture byval(%struct.foo) align 8 %f) local_unnamed_addr addrspace(200) noinline nounwind writeonly
; define dso_local void @foo_byval(%struct.foo addrspace(200)* nocapture byval(%struct.foo) align 8 %f) local_unnamed_addr addrspace(200) noinline nounwind writeonly {
; entry:
;   %arraydecay = getelementptr inbounds %struct.foo, %struct.foo addrspace(200)* %f, i64 0, i32 0, i64 0
;   call void @llvm.memset.p200i8.i64(i8 addrspace(200)* nonnull align 8 dereferenceable(1024) %arraydecay, i8 42, i64 1024, i1 false)
;   ret void
; }

declare void @llvm.memset.p200i8.i64(i8 addrspace(200)* nocapture writeonly, i8, i64, i1 immarg) addrspace(200) argmemonly nounwind willreturn writeonly

define dso_local void @clang_purecap_byval_args() local_unnamed_addr addrspace(200) nounwind {
; RV64-STATIC-LABEL: clang_purecap_byval_args:
; RV64-STATIC:       # %bb.0: # %entry
; RV64-STATIC-NEXT:    addi sp, sp, -1056
; RV64-STATIC-NEXT:    sd ra, 1048(sp) # 8-byte Folded Spill
; RV64-STATIC-NEXT:    sd s0, 1040(sp) # 8-byte Folded Spill
; RV64-STATIC-NEXT:    lui s0, %hi(global_foo)
; RV64-STATIC-NEXT:    addi s0, s0, %lo(global_foo)
; RV64-STATIC-NEXT:    li a2, 1024
; RV64-STATIC-NEXT:    mv a0, s0
; RV64-STATIC-NEXT:    li a1, 0
; RV64-STATIC-NEXT:    call memset
; RV64-STATIC-NEXT:    lb a0, 0(s0)
; RV64-STATIC-NEXT:    li a1, 0
; RV64-STATIC-NEXT:    call assert_eq
; RV64-STATIC-NEXT:    addi a0, sp, 16
; RV64-STATIC-NEXT:    li a2, 1024
; RV64-STATIC-NEXT:    mv a1, s0
; RV64-STATIC-NEXT:    call memcpy
; RV64-STATIC-NEXT:    addi a0, sp, 16
; RV64-STATIC-NEXT:    call foo_byval
; RV64-STATIC-NEXT:    lb a0, 0(s0)
; RV64-STATIC-NEXT:    li a1, 0
; RV64-STATIC-NEXT:    call assert_eq
; RV64-STATIC-NEXT:    ld ra, 1048(sp) # 8-byte Folded Reload
; RV64-STATIC-NEXT:    ld s0, 1040(sp) # 8-byte Folded Reload
; RV64-STATIC-NEXT:    addi sp, sp, 1056
; RV64-STATIC-NEXT:    ret
;
; RV64-PIC-LABEL: clang_purecap_byval_args:
; RV64-PIC:       # %bb.0: # %entry
; RV64-PIC-NEXT:    addi sp, sp, -1056
; RV64-PIC-NEXT:    sd ra, 1048(sp) # 8-byte Folded Spill
; RV64-PIC-NEXT:    sd s0, 1040(sp) # 8-byte Folded Spill
; RV64-PIC-NEXT:  .Lpcrel_hi0:
; RV64-PIC-NEXT:    auipc s0, %pcrel_hi(.Lglobal_foo$local)
; RV64-PIC-NEXT:    addi s0, s0, %pcrel_lo(.Lpcrel_hi0)
; RV64-PIC-NEXT:    li a2, 1024
; RV64-PIC-NEXT:    mv a0, s0
; RV64-PIC-NEXT:    li a1, 0
; RV64-PIC-NEXT:    call memset
; RV64-PIC-NEXT:    lb a0, 0(s0)
; RV64-PIC-NEXT:    li a1, 0
; RV64-PIC-NEXT:    call assert_eq
; RV64-PIC-NEXT:    addi a0, sp, 16
; RV64-PIC-NEXT:    li a2, 1024
; RV64-PIC-NEXT:    mv a1, s0
; RV64-PIC-NEXT:    call memcpy
; RV64-PIC-NEXT:    addi a0, sp, 16
; RV64-PIC-NEXT:    call foo_byval
; RV64-PIC-NEXT:    lb a0, 0(s0)
; RV64-PIC-NEXT:    li a1, 0
; RV64-PIC-NEXT:    call assert_eq
; RV64-PIC-NEXT:    ld ra, 1048(sp) # 8-byte Folded Reload
; RV64-PIC-NEXT:    ld s0, 1040(sp) # 8-byte Folded Reload
; RV64-PIC-NEXT:    addi sp, sp, 1056
; RV64-PIC-NEXT:    ret
;
; PURECAP-RV64-LABEL: clang_purecap_byval_args:
; PURECAP-RV64:       # %bb.0: # %entry
; PURECAP-RV64-NEXT:    cincoffset sp, sp, -1072
; PURECAP-RV64-NEXT:    csc ra, 1056(sp) # 16-byte Folded Spill
; PURECAP-RV64-NEXT:    csc s0, 1040(sp) # 16-byte Folded Spill
; PURECAP-RV64-NEXT:  .LBB0_1: # %entry
; PURECAP-RV64-NEXT:    # Label of block must be emitted
; PURECAP-RV64-NEXT:    auipcc s0, %got_pcrel_hi(global_foo)
; PURECAP-RV64-NEXT:    clc s0, %pcrel_lo(.LBB0_1)(s0)
; PURECAP-RV64-NEXT:    li a2, 1024
; PURECAP-RV64-NEXT:    cmove a0, s0
; PURECAP-RV64-NEXT:    li a1, 0
; PURECAP-RV64-NEXT:    ccall memset
; PURECAP-RV64-NEXT:    clb a0, 0(s0)
; PURECAP-RV64-NEXT:    li a1, 0
; PURECAP-RV64-NEXT:    ccall assert_eq
; PURECAP-RV64-NEXT:    cincoffset a0, sp, 16
; PURECAP-RV64-NEXT:    li a2, 1024
; PURECAP-RV64-NEXT:    cmove a1, s0
; PURECAP-RV64-NEXT:    ccall memcpy
; PURECAP-RV64-NEXT:    cincoffset a0, sp, 16
; PURECAP-RV64-NEXT:    ccall foo_byval
; PURECAP-RV64-NEXT:    clb a0, 0(s0)
; PURECAP-RV64-NEXT:    li a1, 0
; PURECAP-RV64-NEXT:    ccall assert_eq
; PURECAP-RV64-NEXT:    clc ra, 1056(sp) # 16-byte Folded Reload
; PURECAP-RV64-NEXT:    clc s0, 1040(sp) # 16-byte Folded Reload
; PURECAP-RV64-NEXT:    cincoffset sp, sp, 1072
; PURECAP-RV64-NEXT:    cret
; Note: MIPS passes the first 64 byval bytes in registers
entry:
  call void @llvm.memset.p200i8.i64(i8 addrspace(200)* nonnull align 8 dereferenceable(1024) getelementptr inbounds (%struct.foo, %struct.foo addrspace(200)* @global_foo, i64 0, i32 0, i64 0), i8 0, i64 1024, i1 false)
  %0 = load i8, i8 addrspace(200)* getelementptr inbounds (%struct.foo, %struct.foo addrspace(200)* @global_foo, i64 0, i32 0, i64 0), align 8
  %conv = sext i8 %0 to i64
  call void @assert_eq(i64 signext %conv, i64 signext 0) nounwind
  call void @foo_byval(%struct.foo addrspace(200)* nonnull byval(%struct.foo) align 8 @global_foo)
  %1 = load i8, i8 addrspace(200)* getelementptr inbounds (%struct.foo, %struct.foo addrspace(200)* @global_foo, i64 0, i32 0, i64 0), align 8
  %conv1 = sext i8 %1 to i64
  call void @assert_eq(i64 signext %conv1, i64 signext 0) nounwind
  ret void
}

declare void @assert_eq(i64 signext, i64 signext) local_unnamed_addr addrspace(200) nounwind

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
; MIPS: {{.*}}
; MIPS-PIC: {{.*}}
; PURECAP-MIPS: {{.*}}
; RV64: {{.*}}
