name: PR Build and Test

on:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test PR
    runs-on: "cirun-gcp-aarch64--${{ github.run_id }}"
    container:
      image: ghcr.io/cheriot-platform/devcontainer:latest
    timeout-minutes: 360

    env:
      SCCACHE_GCS_BUCKET: ${{ vars.GCP_SCCACHE_BUCKET }}
      SCCACHE_GCS_KEY_PATH: /tmp/sccache-key.json
      SCCACHE_GCS_RW_MODE: READ_WRITE
      SCCACHE_GCS_KEY_PREFIX: ${{ github.repository }}/${{ github.event_name }}/aarch64

    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install dependencies
        run: |
          set -eo pipefail
          sudo apt-get update
          sudo apt-get install -y clang ninja-build lld cmake perl

      - name: Setup sccache
        run: |
          set -eo pipefail
          SCCACHE_VERSION=0.9.1
          curl -sSL "https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-aarch64-unknown-linux-musl.tar.gz" \
            | tar -xz --strip-components=1 -C /tmp \
                "sccache-v${SCCACHE_VERSION}-aarch64-unknown-linux-musl/sccache"
          echo '${{ secrets.GCP_SCCACHE_KEY_JSON }}' > /tmp/sccache-key.json
          /tmp/sccache --start-server
          /tmp/sccache --show-stats
          rm /tmp/sccache-key.json

      - name: Configure
        run: |
          mkdir Build
          cd Build
          cmake ../llvm \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;lldb" \
            -DLLVM_ENABLE_UNWIND_TABLES=NO \
            -DLLVM_ENABLE_LLD=ON \
            -DLLVM_PARALLEL_LINK_JOBS=1 \
            -DLLVM_APPEND_VC_REV=ON \
            -DLLVM_VC_REPOSITORY=${{ github.repository }} \
            -DLLVM_FORCE_VC_REPOSITORY=${{ github.repository }} \
            -DLLVM_VC_REVISION=${{ github.sha }} \
            -DLLVM_CCACHE_BUILD=ON \
            -DCCACHE_PROGRAM=/tmp/sccache \
            -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON \
            -G Ninja

      - name: Build
        run: |
          cd Build
          ninja test-depends

      - name: Test
        run: |
          cd Build
          ./bin/llvm-lit -v ../llvm/test/Unit ../clang/test/Unit
          ./bin/llvm-lit -v ../llvm/test/ ../clang/test/
