name: PR Build and Test

on:
  pull_request:
  merge_group:
  push:
    branches:
      - cheriot

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and test PR
    runs-on: warp-custom-gcp-aarch64-32cpu
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Install dependencies
        run: |
          set -eo pipefail
          sudo apt-get update
          sudo apt-get install -y clang ninja-build lld cmake perl

      - name: Restore sccache cache
        id: restore-sccache
        uses: WarpBuilds/cache/restore@v1
        with:
          path: ~/.cache/sccache
          # this should be empty
          key: sccache-llvm-${{ runner.arch }}-${{github.ref}}-${{github.run_id}}
          # but we might have one of these:
          restore-keys: |
            sccache-llvm-${{ runner.arch }}-${{github.ref}}
            sccache-llvm-${{ runner.arch }}

      - name: Setup sccache
        run: |
          set -eo pipefail
          SCCACHE_VERSION=0.9.1
          curl -sSL "https://github.com/mozilla/sccache/releases/download/v${SCCACHE_VERSION}/sccache-v${SCCACHE_VERSION}-aarch64-unknown-linux-musl.tar.gz" \
            | tar -xz --strip-components=1 -C /tmp \
                "sccache-v${SCCACHE_VERSION}-aarch64-unknown-linux-musl/sccache"
          echo '${{ secrets.GCP_SCCACHE_KEY_JSON }}' > /tmp/sccache-key.json
          /tmp/sccache --start-server
          /tmp/sccache --zero-stats

      - name: Configure
        run: |
          mkdir Build
          cd Build
          cmake ../llvm \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;lldb" \
            -DLLVM_ENABLE_UNWIND_TABLES=NO \
            -DLLVM_ENABLE_LLD=ON \
            -DLLVM_PARALLEL_LINK_JOBS=1 \
            -DLLVM_APPEND_VC_REV=ON \
            -DLLVM_VC_REPOSITORY=${{ github.repository }} \
            -DLLVM_FORCE_VC_REPOSITORY=${{ github.repository }} \
            -DLLVM_VC_REVISION=${{ github.sha }} \
            -DLLVM_CCACHE_BUILD=ON \
            -DCCACHE_PROGRAM=/tmp/sccache \
            -DLLVM_ENABLE_EXPENSIVE_CHECKS=ON \
            -G Ninja

      - name: Build
        run: |
          cd Build
          ninja test-depends

      - name: Test
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        run: |
          cd Build
          ./bin/llvm-lit -v ../llvm/test/Unit ../clang/test/Unit
          ./bin/llvm-lit -v ../llvm/test/ ../clang/test/

      - name: Check sccache stats
        if: always()
        run: /tmp/sccache --show-stats

      - name: Save sccache cache
        if: always()
        id: sccache-save
        uses: WarpBuilds/cache/save@v1
        with:
          path: ~/.cache/sccache
          key: sccache-llvm-${{ runner.arch }}-${{github.ref}}-${{github.run_id}}
